### ISSUE TITLE
Issue when installing

### ISSUE THREAD

**Issue by fsanzdev** [dominiksalvet/asus-fan-control#1]
**Environment**
Ubuntu 19.04

**Describe the bug**
When trying to install with
sudo gim install github.com/dominiksalvet/asus-fan-control

Get this error
E: Package 'acpi-call-dkms' has no installation candidate
make: *** [makefile:64: install-deps] Error 1
<INSTALL-FAIL> [install] github.com/dominiksalvet/asus-fan-control 2.4.1

When trying to install the package

ubuntu@ubuntu:/tmp/gim$ sudo apt install acpi-call-dkms
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package acpi-call-dkms is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'acpi-call-dkms' has no installation candidate

I had to install it downloading it as .deb

**Comment by dominiksalvet** [comment]
Hello! I am an Ubuntu 18.04 user but now I am downloading Ubuntu 19.04 for VirtualBox use to find out what can I do with that. I will let you know.

**Comment by dominiksalvet** [comment]
@fsanzdev Well, I have bad news for you. :disappointed: It works perfectly fine for me on a fresh installation of Ubuntu 19.04 (VirtualBox) as well as on Ubuntu 18.04 (real instance + VirtualBox). It does not control fan from VirtualBox instances (of course) but the installation was successful.

My Ubuntu 19.04 configuration: Minimal installation, Third party software for graphics and Wi-Fi hardware and additional media formats installed, fully updated. After installation `sudo apt install git`. Then installed [gim](https://github.com/dominiksalvet/gim) as shown on its website. The last step was `sudo gim install github.com/dominiksalvet/asus-fan-control` and everything was fine. Even the manual installation `sudo apt install acpi-call-dkms` worked.

So I suspect that the problem might be on your side. What is the output of `sudo apt update`? Maybe it will reveal the problem for us.

**Comment by dominiksalvet** [comment]
@fsanzdev Have you tried to solve the problem?

**Comment by fsanzdev** [comment]
Sorry for the late reply @dominiksalvet. I reinstalled Ubuntu 19.04 and this time it worked flawlessly.

**Comment by dominiksalvet** [comment]
@fsanzdev :tada: I am really glad to hear that! So enjoy the silence. :smiley:

**Comment by dominiksalvet** [comment]
I just wanted to add a hint that may help others in similar situations. I suspect that the problem might be solved using `sudo apt-get update` before the installation. :smile:

Have a wonderful day!
