### ISSUE TITLE
Add support for Asus ROG GU501GM

### ISSUE THREAD

**Issue by hypadr1v3** [dominiksalvet/asus-fan-control#102]
**Environment**
Currently using `asus-fan-control 3.11.0` on Arch Linux with the KDE desktop environment

**Basic configuration**
* `sudo asus-fan-control get-temps` 

```55 56 57 58 59 60 61 62```

* `sudo asus-fan-control model-info`
```
name ROGGU501GM
addresses 1335
default-temps 55 60 62 65 68 72 76 80
tested false
```

**Advanced configuration**
None used

**It does not work**
I am not sure about the reason it does not work. No error was given out from AFC.

**Additional context**
I ran `sudo afc-scout` and here are the results:

```
------ base address 1335 ------
[1334] = 54
[1335] = 55 <- possible start
[1336] = 56
[1337] = 57
[1338] = 58
[1339] = 59
[1340] = 60
[1341] = 61
[1342] = 62 <- possible end
[1343] = 63
------ base address 1431 ------
[1430] = 150
[1431] = 151 <- possible start
[1432] = 152
[1433] = 153
[1434] = 154
[1435] = 155
[1436] = 156
[1437] = 157
[1438] = 158 <- possible end
[1439] = 159
```

**Comment by dominiksalvet** [comment]
Does AFC work on your device? I suspect it has zero effect on your device...

> If you don't know whether asus-fan-control works on your device:
> 
> Try different setups of temperatures, e.g., `sudo asus-fan-control set-temps 30 35 40 45 50 55 60 65` and then `sudo asus-fan-control set-temps 60 65 70 75 80 85 90 95`. You definitely should hear the difference.

**Comment by hypadr1v3** [comment]
Yeah there is no difference at all. Tried even more extreme temps and thought I heard a slight difference but that's just bias from me.

**Comment by dominiksalvet** [comment]
Are you able to get previously set temperatures?

**Comment by hypadr1v3** [comment]
It would set them without error although nothing happened when setting them. Fans remain at the same speed as they were

**Comment by hypadr1v3** [comment]
Wait I misread your comment. No, the temps remain the same when running `get-temps` even if I set different ones

**Comment by dominiksalvet** [comment]
Yeah, unfortunately, this is one of known issues and such devices do not work with AFC. See the added issue label for more similar issues and users' contributions.

**Comment by hypadr1v3** [comment]
Hey! 
By the way, I found a program that actually is able to control the fans on my laptop

The program `asusctl` had an option for a fan profile which works!

**Comment by dominiksalvet** [comment]
Oh, that is great, thank you for sharing! Please can you tell us how did you install it?

**Comment by hypadr1v3** [comment]
Well, since I'm using Arch Linux, I installed it from the AUR using yay with `yay -S asusctl-git`
