### ISSUE TITLE
Add support for Asus zephyrus G14

### ISSUE THREAD

**Issue by arnabau** [dominiksalvet/asus-fan-control#105]
Hello everyone!

I am trying to run the script on an Asus G14 running Linux (kernel 5.11) Zorin 16. I already installed Gitpack, asus-fan-control and acpi_call with no apparent problems, but when I run asus-fan-control I get the error AE_NOT_FOUND.

I already read in the issues section that this error has no solution for now, even so I would like to know if someone has managed to solve the problem or if there is any other way to make acpi calls and change the fan values? Can it only be done via acpi_call?

**Comment by flukejones** [comment]
> Hello everyone!
> 
> I am trying to run the script on an Asus G14 running Linux (kernel 5.11) Zorin 16. I already installed Gitpack, asus-fan-control and acpi_call with no apparent problems, but when I run asus-fan-control I get the error AE_NOT_FOUND.

The ACPI method used is not in the tables. You need this patch I wrote which will be on it's way to the 5.16 kernel soon.
https://lkml.org/lkml/2021/10/23/249

**Comment by arnabau** [comment]
Thanks for the reply. I already managed to install `acpi_call` (acpi-call-dkms 1.1.0) using synaptics, and with this you can set the fan curves. It could also be installed using:

`sudo apt-get install acpi-call-dkms`
`sudo modprobe acpi_call` (to load the module)

I am using another way (and app in Rust) that does basically the same and works without problems, in fact, I'm using Fn+F5 to toggle profiles. I have not tried with `asus-fan-control` yet but it should work, 'cause the problem was the acpi call. 

As soon as I have a chance I will do some tests to see if it works

**Comment by flukejones** [comment]
@arnabau if your machine is a GA401QM I strongly suggest you use fedora (in fact you should prefer it over Ubuntu if only for the more regular kernel and graphics stack updates). Use the kernel patch + `asusctl` for far better control over your machine - https://asus-linux.org/asusctl/

**Comment by Ambershub** [comment]
Hello i have the same issue with Asus tuf FA506IV my kernel is 5.14.15-arch1-1. I try installing dkms version of acpi_cal but it doesn't change the situation (acpi call failed with 'Error: AE_NOT_FOUND'). I try to install faustus model but I couldn't install it correctly

**Comment by arnabau** [comment]
I did some tests, it definitely doesn't work with zephyrus g14 even with acpi-call-dkms installed.

**Comment by dominiksalvet** [comment]
Don't you guys have AMD processors by chance?

**Comment by nathanb9** [comment]
Yes the Zephyrus has AMD cpus

**Comment by dominiksalvet** [comment]
AFC does not work with AMD processors (rather with their accompanied HW). I have directly updated the readme file to provide this information right from the start.

Hence I am closing this issue.
