### ISSUE TITLE
Add support for FX505DT

### ISSUE THREAD

**Issue by UtkarshVerma** [dominiksalvet/asus-fan-control#108]
**Environment**
Void Linux with Linux 5.15.9 and `acpi_listen`.

**It does not work**
```
$ sudo asus-fan-control
acpi call failed with 'Error: AE_NOT_FOUND'
```

**Comment by dominiksalvet** [comment]
Unfortunately, this is a known, not yet resolved, issue. I guess you have an AMD processor, right? AFC does not seem to work with AMD processors.

**Comment by UtkarshVerma** [comment]
Yes, it's an AMD Ryzen 3550H.

**Comment by dominiksalvet** [comment]
Yeah, so I am closing this issue since AMD processors really do not work with AFC. See the updated readme for more information.
