### ISSUE TITLE
Add support for UX425

### ISSUE THREAD

**Issue by ruanformigoni** [dominiksalvet/asus-fan-control#109]
**Environment**
asus-fan-control version: 3.12

```
OS: Pop!_OS 21.10 x86_64 
Host: ZenBook UX425EA_UX425EA 1.0 
Kernel: 5.15.0-11.1-liquorix-amd64 
Resolution: 1920x1080 
DE: GNOME 40.5 
WM: Mutter 
WM Theme: Pop 
Theme: Pop-dark [GTK2/3] 
Icons: Pop [GTK2/3] 
Terminal: x-terminal-emul 
CPU: 11th Gen Intel i5-1135G7 (8) @ 2.400GHz 
GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics] 
Memory: 2494MiB / 7654MiB 
```

**Basic configuration**
If only temperatures were set and they worked, add output of:
* `sudo asus-fan-control get-temps` : `acpi call failed with 'Error: AE_NOT_FOUND'`
* `sudo asus-fan-control model-info` : 
```
name ZenBookUX425EAUX425EA
addresses 1335
default-temps 55 60 62 65 68 72 76 80
tested false
```

**It does not work**
If neither configuration was working for your device, community involvement is required. Please provide some information so the community can build on something. Why does asus-fan-control not work? What have you tried?

I've followed the instructions to install gitpack and asus-fan-control afterwards, installed the kernel module, loaded with `modprobe acpi-call`. The output of `sudo asus-fan-control` is `acpi call failed with 'Error: AE_NOT_FOUND'`.

**Comment by hack3r-0m** [comment]
any update? i have same model

**Comment by ruanformigoni** [comment]
> any update? i have same model. what is causing this error?

The fan is not detected by the `lm_sensors` package. I suspect there is no kernel support.

**Comment by dominiksalvet** [comment]
I have done some investigation, and it seems that somewhere since the 8th gen Intel processors, they have also updated the associated HW, and AFC does not work for these and newer processors. AMD processors do not work inherently since they have completely different CPU-associated HW.

I have updated some repository files (including readme) to reflect these findings.

**Comment by Ilias-El-Mhamdi** [comment]
Hello everyone, 

First of all thank you for the package and your it was very clear and easy to install ! 

I have almost the save configuration and I'am getting the same error, it's sad that it doesn't work on this configuration. Does any one of you found an alternative ? The fan is kicking at full speed at 38°C it's quite unbearable (I am on dual boot with windows).

```  
OS: Ubuntu 20.04.4 LTS x86_64 
Host: ZenBook UX425EA_UX425EA 1.0 
Kernel: 5.13.0-39-generic 
DE: GNOME 
WM: Mutter 
WM Theme: Adwaita 
CPU: 11th Gen Intel i7-1165G7 (8) @  
GPU: Intel Device 9a49 
Memory: 3262MiB / 31802MiB ```
