### ISSUE TITLE
Bug or not Work on Asus ROG Strix G531GW

### ISSUE THREAD

**Issue by Mikarox** [dominiksalvet/asus-fan-control#111]
**Environment**
sudo asus-fan-control model-info 
name ROGStrixG531GW
addresses 1335
default-temps 55 60 62 65 68 72 76 80
tested false

**Description**
im try to install in this model but i cant change the temperature
First use get-temps and get this: 

sudo asus-fan-control get-temps
55 56 57 58 59 60 61 62

and try to change them but dont effect

**Additional context**
             /////////////                mikaros@popparadox 
         /////////////////////            ------------------ 
      ///////*767////////////////         OS: Pop!_OS 21.10 x86_64 
    //////7676767676*//////////////       Host: ROG Strix G531GW 1.0 
   /////76767//7676767//////////////      Kernel: 5.15.15-76051515-generic 
  /////767676///*76767///////////////     Uptime: 9 mins 
 ///////767676///76767.///7676*///////    Packages: 2137 (dpkg), 7 (flatpak) 
/////////767676//76767///767676////////   Shell: bash 5.1.8 
//////////76767676767////76767/////////   Resolution: 1920x1080 
///////////76767676//////7676//////////   DE: GNOME 40.5 
////////////,7676,///////767///////////   WM: Mutter 
/////////////*7676///////76////////////   WM Theme: Pop 
///////////////7676////////////////////   Theme: Pop-dark [GTK2/3] 
 ///////////////7676///767////////////    Icons: Pop [GTK2/3] 
  //////////////////////'////////////     Terminal: gnome-terminal 
   //////.7676767676767676767,//////      CPU: Intel i7-9750H (12) @ 4.500GHz 
    /////767676767676767676767/////       GPU: NVIDIA GeForce RTX 2070 Mobile 
      ///////////////////////////         GPU: Intel CoffeeLake-H GT2 [UHD Graphics 630] 
         /////////////////////            Memory: 1938MiB / 15851MiB 
             /////////////

**Comment by bonearadu** [comment]
Same issue on my GL704GW. Running on Arch, Linux 5.16.2-arch1-1

**Comment by dominiksalvet** [comment]
Unfortunately, this is a known issue occurring on some models. See the freshly assigned label for more similar issues and discussions.

**Comment by dominiksalvet** [comment]
Even though you have an Intel CPU, it seems that AFC does not work on newer models. I personally still have the UX430UA with the 7th generation CPU i5-7200U, if that helps with troubleshooting.

**Comment by dominiksalvet** [comment]
All right, I have done some investigation, and it seems that somewhere since the 8th gen Intel processors, they have also updated the associated HW, and AFC does not work for these and newer processors.

I have updated some repository files (including readme) to reflect these findings.

**Comment by Mikarox** [comment]
today I stressed my computer and realized that it is not necessary to install Asus Fan control, the fans work fine.
