### ISSUE TITLE
Can't force fan speed to max all the time

### ISSUE THREAD

**Issue by LoganDark** [dominiksalvet/asus-fan-control#114]
**Description**
On Windows, I usually use [atrofac](https://github.com/cronosun/atrofac) to force my fans to run at around 130% speed at all times (YES, that is greater than 100%). But with `asus-fan-control` it only seems to support temperature thresholds, and I can only get them this low:

```
$ sudo asus-fan-control get-temps
44 44 60 60 60 60 60 60
```

**Reason**
I have my reasons for wanting the fans to run at full speed, like stopping the laptop from burning me due to the extreme heat...

**Additional context**
I am running `asus-fan-control` on a GU502LV (ROG Zephyrus M15) in AntiX Linux 21.

**Comment by dominiksalvet** [comment]
AFAIK, AFC is not able to work with higher speeds than 100 %. But if you want to choose directly, at which percentage you want to spin your fans, have a look at [afc-gui](https://github.com/Greifent/afc-gui), which has this extra functionality.

Maybe you may want to play a bit with afc-scout, from which you may find tipping points for driving fans for more than 100 %, I do not know...

Also, do you have an untested laptop device? If so, please consider adding it officially to AFC...

**Comment by LoganDark** [comment]
> Also, do you have an untested laptop device? If so, please consider adding it officially to AFC...

Yes I do, GU502LV. I'm holding off on adding it until I can verify that AFC actually does something.

**Comment by dominiksalvet** [comment]
So it does not work at all on your device, right?

**Comment by LoganDark** [comment]
I cannot tell.

**Comment by LoganDark** [comment]
(The reason I couldn't tell is because Linux keeps the CPU temperatures so low that they're literally always below the threshold. So even if this program did do something, I literally couldn't tell, because it won't allow me to set the fan speed directly, only set temperature thresholds)

**Comment by dominiksalvet** [comment]
So burn it up a little bit. Play some games, 4K video or so...

**Comment by dominiksalvet** [comment]
Also see our wiki. There is a tip there directly for your situation.

**Comment by LoganDark** [comment]
I'll check it out next time I'm booted into Linux :)

(Sorry if my comments came across as rude)
