### ISSUE TITLE
Fan speed 0 = 3000rpm

### ISSUE THREAD

**Issue by mews-se** [dominiksalvet/asus-fan-control#116]
For my UX430UA, the zero speed setting seems to be 3000 rpm for some reason.

Any ideas?
![Screenshot at 2022-07-01 22-38-37](https://user-images.githubusercontent.com/58894405/176965184-3189e31e-f0e6-48f9-90da-3cc147c251d8.png)
![Screenshot at 2022-07-01 22-39-18](https://user-images.githubusercontent.com/58894405/176965186-7485dbcd-a25a-4b35-90af-d92d5a0726e7.png)

**Comment by dominiksalvet** [comment]
What is the output of `sudo asus-fan-control get-temps`?

**Comment by mews-se** [comment]
45 45 45 50 55 60 60 70

**Comment by dominiksalvet** [comment]
That's weird. Try using different temperatures as described on our AFC GitHub Wiki... Maybe you will have some success.

BTW some sensor programs do not work on my UX430UA. So do not rely that much on numbers provided, rather try hearing the noise directly from the laptop's fan...
