### ISSUE TITLE
Add support for VivoBook X513EA/S513EA

### ISSUE THREAD

**Issue by TmDobbin** [dominiksalvet/asus-fan-control#121]
**Environment**
Latest version of AFC, Linux mint 21

**Basic configuration**
If only temperatures were set and they worked, add output of:
AE_NOT_FOUND
```
name VivoBookASUSLaptopX513EAS513EA
addresses 1335
default-temps 55 60 62 65 68 72 76 80
tested false
```
**It does not work**
AE_NOT_FOUND. If I can supply any extra information, let me know.

**Additional context**
Add any additional context.

**Comment by dominiksalvet** [comment]
Hello, this is a typical issue on some devices. Unfortunately, there is nothing you can do to make it work. At least I do not know anything so far...

**Comment by TmDobbin** [comment]
Ah, that's unfortunate. Is there some alternative I can use to change the fan profile? The fan seems to fire up randomly even under light load. Thanks for your help.

**Comment by dominiksalvet** [comment]
> Ah, that's unfortunate. Is there some alternative I can use to change the fan profile? The fan seems to fire up randomly even under light load. Thanks for your help.

Take a look [here](https://github.com/dominiksalvet/asus-fan-control/issues?q=label%3A%22alternative+found%22+is%3Aclosed). Maybe it will help you.

**Comment by TmDobbin** [comment]
Hi, thanks again for the help! While none of the options you linked worked for me, I have had some success with [nbfc](https://github.com/hirschmann/nbfc). In case it's helpful for anyone searching for an answer too, the config for the ASUS Vivobo
ok X580VD (`ASUS Vivobook X580VD`) seems to work with the Vivobook S513EA/X513EA. Once again thank you for the support!

**Comment by dominiksalvet** [comment]
Glad to hear that! Thank you for letting us know :tada:
