### ISSUE TITLE
Add support for ROG Zephyrus G15 GA503RW

### ISSUE THREAD

**Issue by RogustCarthon** [dominiksalvet/asus-fan-control#122]
**Environment**
AFC version : 3.13.0
OS version : Ubuntu 22.04.1 LTS
CPU Name : AMD® Ryzen 9 6900hs with radeon graphics × 16

**It does not work**
`sudo asus-fan-control`, `sudo asus-fan-control get-temps`, `sudo asus-fan-control set-temps default`, all fail with `acpi call failed with 'Error: AE_NOT_FOUND'`.

**Comment by dominiksalvet** [comment]
Sure. Unfortunately, devices with AMD do not work... Maybe someone can find an alternative and let us know? 😊

**Comment by RogustCarthon** [comment]
Upgraded to mainline linux kernel v6.0 due to another unrelated issue. Running `asus-fan-control` now gives
```
file /proc/acpi/call does not exist
```

**Comment by dominiksalvet** [comment]
Try `modprobe acpi_call`. Nevertheless, I think you will get the previous error again...
