### ISSUE TITLE
Add support for ROG Strix G513QM_G513QM 1.0

### ISSUE THREAD

**Issue by MahanBi** [dominiksalvet/asus-fan-control#123]
**Environment**
State your AFC version, OS version, and CPU 

ROGStrixG513QMG513QM
addresses 1335
default-temps 55 60 62 65 68 72 76 80
tested false

**Comment by dominiksalvet** [comment]
Hello @MahanBi , does AFC work for you?

**Comment by MahanBi** [comment]
Hi
```

>>> sudo asus-fan-control                                                                                                                                                                             
acpi call failed with 'Error: AE_NOT_FOUND'
```
show me this result

**Comment by dominiksalvet** [comment]
What is your CPU?

**Comment by MahanBi** [comment]
CPU: AMD Ryzen 9 5900HX with Radeon Graphics (16) @ 3.
GPU: NVIDIA GeForce RTX 3060 Mobile / Max-
GPU: AMD ATI 05:00.0 Cezanne

**Comment by dominiksalvet** [comment]
Yeah, unfortunately, AMD CPUs are not supported in the AFC. But maybe someone comes with an alternative.
