### ISSUE TITLE
Add support for Asus X5DIJ

### ISSUE THREAD

**Issue by CruxVelox** [dominiksalvet/asus-fan-control#126]
**Environment**
(?), Linux Mint Cinnamon 20.2, Intel Pentium IV 2.20GHz x2.

2008/2009 Asus X5DIJ laptop, 4G ram, 1/2 TB HDD, igfx

**Comment by dominiksalvet** [comment]
Does it work for you?

**Comment by CruxVelox** [comment]
No
It doesn't work for me :|

Il sab 15 ott 2022, 16:11 Dominik Salvet ***@***.***> ha
scritto:

**Comment by dominiksalvet** [comment]
Any errors?

**Comment by CruxVelox** [comment]
I am not getting any errors, it's just doesn't show the info...

Il sab 15 ott 2022, 16:14 Dominik Salvet ***@***.***> ha
scritto:

**Comment by dominiksalvet** [comment]
I need a terminal log.
