### ISSUE TITLE
Add support for Vivobook Pro X3400PH K3400PH

### ISSUE THREAD

**Issue by biji** [dominiksalvet/asus-fan-control#128]
**Environment**
State your AFC version, OS version, and CPU name.

```
AFC 3.13.0
Fedora : 37
Intel i7-11370H
```

* `sudo asus-fan-control get-temps`
```
acpi call failed with 'Error: AE_NOT_FOUND'
```

* `sudo asus-fan-control model-info`
```
name VivobookASUSLaptopX3400PHK3400PH
addresses 1335
default-temps 55 60 62 65 68 72 76 80
tested false
```

**It does not work**

Can not get-temps , set-temps
module `acpi_call` is loaded

Thanks

**Comment by dominiksalvet** [comment]
Hello and thank you for your post! Unfortunately, this is a notorious issue with many new devices and it has not been solved. It may never will (see issue with the associated label). However, I will keep the issue open for while, should someone find an alternative and like to share it with us.

**Comment by dharmann** [comment]
I've the same problem. Following are my infos:

**Product Name: ASUS EXPERTBOOK B9400CEA_B9400CEA**

```
AFC 3.13.0
Kubuntu 22.04.1 LTS
Intel i7-1165G7
```

*asus-fan-control model-info*

```
name ASUSEXPERTBOOKB9400CEAB9400CEA
addresses 1335
default-temps 55 60 62 65 68 72 76 80
tested false
```

My 2¢
