### ISSUE TITLE
Fan speeds reset to defaul values after resuming from hibernate

### ISSUE THREAD

**Issue by agura-lex** [dominiksalvet/asus-fan-control#13]
**Environment**
asus-fan-control version: 2.11.0
model: X512UA
distro: Arch Linux

**Describe the bug**
After resuming from hibernate, `asus-fan-control -get-temps` reports default fan speed values. Not the bug in `asus-fan-control` itself since it doesn't provide any active control, but we can mitigate that, I guess.

**To Reproduce**
1. Set temps via `asus-fan-control`
2. Hibernate and resume
3. Run `asus-fan-control -get-temps`
4. Get your default from-the-factory fan speeds

**Possible solution**
Add systemd service which will run after `hibernate.target`. And that's what I'm gonna do.

**Comment by agura-lex** [comment]
Okay, this unit seems to do the job:
```ini
# /etc/systemd/system/asus-fan-control-resume.service
#-------------------------------------------------------------------------------
# Copyright 2019 Alexander Agura
# github.com/dominiksalvet/asus-fan-control
#-------------------------------------------------------------------------------

[Unit]
Description=Run asus-fan-control after resuming from hibernate.
After=hibernate.target

[Service]
Type=oneshot
ExecStart=/usr/bin/asus-fan-control

[Install]
WantedBy=hibernate.target
```

I'll create a PR when I get time to

**Comment by agura-lex** [comment]
We can also make it a dependency for `asus-fan-control.service`, so enabling that will enable this as well.

**Comment by dominiksalvet** [comment]
I do not have time right know, but tomorrow, I will leave you a comment on this (it does not affect the PR in any way I guess)... :smile:

**Comment by dominiksalvet** [comment]
Never mind, I was thinking about suspend (not hibernate) as I was testing it and it should be working. Feel free to prepare the PR. Thank you! :heart:

**Comment by dominiksalvet** [comment]
Continuing in #15, so closing this issue.

**Comment by agura-lex** [comment]
It seems that it's still the case after using `suspend-then-hibernate` (it's kinda like suspend in Windows: the device goes in suspend-to-ram and if not awaken for a while hibernates). I guess, it uses different target other than `hibernate.target`. Will dig into that and see if I can fix it. I know that almost nobody uses `suspend-then-hibernate` in Linux (but AFAIK Gnome does that by default nowadays).

**Comment by dominiksalvet** [comment]
Well, I haven't knew about any `suspend-then-hibernate` until now. Examining that in #16.
