### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by davidcortesortuno** [dominiksalvet/asus-fan-control#131]
Short question. How can I install `afc` in another Linux distribution? I'm using Opensuse. Should I just try to execute the script in the `src` folder?

**Comment by dominiksalvet** [comment]
I do not recommend running AFC without proper installation. Did GitPack installation not work for you? If so, why?

**Comment by davidcortesortuno** [comment]
I haven't tried Gitpack yet, so I will give it a go
