### ISSUE TITLE
Add support for Fedora Workstation 37

### ISSUE THREAD

**Issue by kity-linuxero** [dominiksalvet/asus-fan-control#132]
Hi there!.

I try install `asus-fan-control` in Fedora 37, but `acpi_call` is not available for kernels 5.6+. [link](https://github.com/nix-community/acpi_call/commit/2554f05ec7a0fb042e6454c39e28faf4de159ac0).

**Environment**
Fedora 37 Workstation.
Asus UX410UA

**It does not work**

```bash
mar 05 17:22:34 fedora systemd[1]: afc.service: Control process exited, code=exited, status=1/FAILURE
mar 05 17:22:34 fedora systemd[1]: afc.service: Failed with result 'exit-code'.
mar 05 17:22:34 fedora systemd[1]: Failed to start afc.service - Executes asus-fan-control whenever necessary..
```

To try load the kernel module
```bash
cris@fedora:~$ sudo modprobe acpi_call
modprobe: FATAL: Module acpi_call not found in directory /lib/modules/6.1.11-200.fc37.x86_64
```
Any idea?

**Comment by dominiksalvet** [comment]
Hello @kity-linuxero! I am sorry but I do not use Fedora and I am kind of clueless here... 😕 But I searched on Google and this seems to be a problem with some kernel 5.6+ changes and requires an updated version of acpi_call. Have you tried to compile and install the most recent version of acpi_call manually?

**Comment by propertunist** [comment]
I just got acpi call installed in fedora 37 using this: https://github.com/marcoDallas/acpi_call_GUI_systemd
However, I am getting the AE_NOT_FOUND error now.

**Comment by dominiksalvet** [comment]
> I just got acpi call installed in fedora 37 using this: https://github.com/marcoDallas/acpi_call_GUI_systemd However, I am getting the AE_NOT_FOUND error now.

I believe you have acpi_call installed correctly. The issue is probably with your device because it has different internals than expected by AFC. Have a look to issues with label AE_NOT_FOUND for more information.
