### ISSUE TITLE
[Typo] Uninstallation hooks through pacman

### ISSUE THREAD

**Issue by H2-san** [dominiksalvet/asus-fan-control#133]
In the two lines echoed to stdout, there is a typo in the first line.
```
You mihgt want to reboot your system to restore the default fan speed
You might also want to remove '/etc/asus-fan-control/temps'
```
Suggesting replacing "mihgt" with "might"

**Comment by dominiksalvet** [comment]
@agura-lex Please, can you have a look at it?

**Comment by agura-lex** [comment]
Hello there, I'm no longer maintaining the package on AUR since I rarely fire up my Arch Linux laptop. It's now maintained by `isinyaaa`, feel free to leave a comment here https://aur.archlinux.org/packages/asus-fan-control or reach out to the maintainer by their email.

**Comment by agura-lex** [comment]
@isinyaaa

**Comment by isinyaaa** [comment]
@H2-san @agura-lex sorry I haven't used the package in a long while, totally missed the typo. Will update soon.

**Comment by isinyaaa** [comment]
Done.

**Comment by agura-lex** [comment]
Haha, no worries, that was my typo I suppose, I often leave a good lot of those. Thanks a bunch for fixing it promptly!
