### ISSUE TITLE
Add support for TP550LAB

### ISSUE THREAD

**Issue by HamzaLakhani01** [dominiksalvet/asus-fan-control#134]
**Environment**
AFC 3.12.0 (AUR), Arch Linux x86_64 Kernel 6.2-9, Intel Core i5-5500U.*
*This platform loves to go full fan speed only at 100 degrees Celsius. I will supply another set of _recommended_ temperatures based on testing.

**Basic configuration**
`get-temps` returns factory stock values of `55 60 65 75 82 89 95 100`
`model-info` returns: 
```
name TP550LAB
addresses 1335
```

**Additional context**
Program default recommended values are what I would recommend for this platform with values `55 60 62 65 68 72 76 80`
Values I'll be using for a more active cooling preset are `45 50 55 60 65 70 75 80`

**Comment by dominiksalvet** [comment]
Hello @HamzaLakhani01! So did I understand you correctly that AFC is working for your device and your preferred temperatures are `45 50 55 60 65 70 75 80`? Would you like to prepare a pull request yourself? :rocket:

**Comment by HamzaLakhani01** [comment]
> Hello @HamzaLakhani01! So did I understand you correctly that AFC is working for your device and your preferred temperatures are `45 50 55 60 65 70 75 80`? Would you like to prepare a pull request yourself? :rocket:

@dominiksalvet Affirm for AFC working. For most people with very similar models (TP550LA), they would find default temps at `55 60 62 65 68 72 76 80` would work.

Does AFC support setting nicknames for temperatures?
`factory` for example would have temps `55 60 65 75 82 89 95 100`, `recommended` having `55 60 62 65 68 72 76 80`, `cooler` containing my preferred temperatures at `45 50 55 60 65 70 75 80`.

**Comment by dominiksalvet** [comment]
Ok, I will add the support as soon as I have some time. Nicknames for temperatures are not supported.
