### ISSUE TITLE
Add support for FX505GT

### ISSUE THREAD

**Issue by zukurnaz** [dominiksalvet/asus-fan-control#135]
**Environment**
AFC:asus-fan-control 3.13.0-1 (AUR)
OS:Arch Linux x86_64 Kernel 6.2.8-arch1-1
CPU: i5-9300H

**Basic configuration**

* `sudo asus-fan-control get-temps` `45 50 55 60 65 70 75 80`
* `sudo asus-fan-control model-info`

```
name TUFGamingFX505GTFX505GT
addresses 1335
default-temps 45 50 55 60 65 70 75 80
tested false
```
**Additional context**

afc-scout 
```
[1334] = 102
[1335] = 55 <- possible start
[1336] = 60
[1337] = 62
[1338] = 65
[1339] = 68
[1340] = 72
[1341] = 76
[1342] = 80 <- possible end
[1343] = 105
------ base address 1431 ------
[1430] = 0
[1431] = 50 <- possible start
[1432] = 57
[1433] = 62
[1434] = 67
[1435] = 67
[1436] = 67
[1437] = 67
[1438] = 67 <- possible end
[1439] = 105
```
adding 1431 makes gpu fan work

`TUFGamingFX505GTFX505GT|1335 1431|45 50 55 60 65 70 75 80`

temp values goes back to laptop's default values after a while,
journalctl returns this

```
Apr 01 21:03:52 arch kernel: ACPI Error: Divide by zero (20221020/utmath-478)

Apr 01 21:03:52 arch kernel: ACPI Error: Aborting method \_SB.ATKD.WMNB due to previous error (AE_AML_DIVIDE_BY_ZERO)>
```

**Comment by dominiksalvet** [comment]
Hello @zukurnaz! Well, I have similar issue but it occurs very rarely and is always after updating system. I did not look at the associated log record but it might be the same problem... Restart should help -- please let me know.

BTW, what temperatures do you recommend for your laptop model?

**Comment by zukurnaz** [comment]
`TUFGamingFX505GTFX505GT|1335 1431|60 62 64 66 68 70 72 74`
Probably something like this for less noise,

After a clean arch install values are stable and everything working as intended, A thousand thanks!

**Comment by dominiksalvet** [comment]
@zukurnaz Glad to hear that! :-) I will add the support when I have some time or you can create a PR yourself if you want. Thanks for testing it out!

**Comment by dominiksalvet** [comment]
@zukurnaz Thank you for your cooperation! The changes will appear in an upcoming release.
