### ISSUE TITLE
Add support for G751JY

### ISSUE THREAD

**Issue by nick-dimitrov** [dominiksalvet/asus-fan-control#139]
**Environment**:
$ asus-fan-control about
asus-fan-control 3.14.0
Fan control for ASUS devices running Linux         

OS version="Debian GNU/Linux 11 (bullseye)"

CPU:Info: Quad Core model: Intel Core i7-4860HQ bits: 64 type: MT MCP arch: Haswell 
           family: 6 model-id: 46 (70) stepping: 1 microcode: 1C cache: L2: 6 MiB 
           

**Basic configuration**:
$ sudo asus-fan-control get-temps
45 50 55 60 65 70 75 80         
       
$ sudo asus-fan-control model-info
name G751JY
addresses 1335
default-temps 55 60 62 65 68 72 76 80
tested false

**Additional context**:
Hello,
The program works for me and I can see the differences in the revolutions at different values of set-temps.
Unfortunately,programs such as lm-sensors, psensor, xsensors, conky,gkrellm... in my opinion, do not show the real revolutions of the fan.
At set temperatures 70 73 75 77 80 85 90 95 I feel the fan stops working but I see this{cpu_fan:2300 RPM}:
$ sensors | grep -i fan
cpu_fan:     2300 RPM

graphics card fan not recognized:
$ sensors
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +47.0°C  (high = +84.0°C, crit = +100.0°C)
Core 0:        +43.0°C  (high = +84.0°C, crit = +100.0°C)
Core 1:        +40.0°C  (high = +84.0°C, crit = +100.0°C)
Core 2:        +40.0°C  (high = +84.0°C, crit = +100.0°C)
Core 3:        +44.0°C  (high = +84.0°C, crit = +100.0°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +46.0°C  (crit = +103.0°C)

asus-isa-0000
Adapter: ISA adapter
cpu_fan:     2300 RPM
temp1:        +46.0°C  

BAT0-acpi-0
Adapter: ACPI interface
in0:              N/A  

$ nvidia-smi -L
GPU 0: NVIDIA GeForce GTX 980M (UUID: GPU-0d78d352-9e81-f097-dea2-469251ff2439)

Graphics:  Device-1: NVIDIA GM204M [GeForce GTX 980M] vendor: ASUSTeK driver: nvidia v: 470.182.03 
           bus-ID: 01:00.0 chip-ID: 10de:13d7 class-ID: 0300 
           Display: x11 server: X.Org 1.20.11 compositor: xfwm4 v: 4.18.0 driver: loaded: nvid

Kernel: 5.10.0-23-amd64 [5.10.179-1] x86_64 bits: 64 compiler: gcc v: 10.2.1 
           parameters: BOOT_IMAGE=/boot/vmlinuz-5.10.0-23-amd64 root=UUID=<filter> ro quiet 
           loglevel=0 init=/lib/systemd/systemd 
           
           Machine: Type: Laptop System: ASUSTeK product: G751JY v: 1.0  
Mobo: ASUSTeK model: G751JY v: 1.0 serial: <filter> UEFI: American Megatrends 
v: G751JY.202 date: 09/10/2014
           

  $ sudo afc-scout
------ base address 1335 ------
[1334] = 12
[1335] = 65 <- possible start
[1336] = 65
[1337] = 68
[1338] = 70
[1339] = 74
[1340] = 75
[1341] = 80
[1342] = 85 <- possible end
[1343] = 98
------ base address 1431 ------
[1430] = 12
[1431] = 45 <- possible start
[1432] = 58
[1433] = 64
[1434] = 68
[1435] = 76
[1436] = 88
[1437] = 88
[1438] = 88 <- possible end
[1439] = 98

**Comment by nick-dimitrov** [comment]
Here's what else I can say:
I added this module to the Linux kernel and modules.conf under coretemp:
asus_fan - to make both fans work
https://github.com/daringer/asus-fan

Thermald package installed

At system startup I automatically remove the module:
asus-nb-wmi - it can control one fan
https://wiki.archlinux.org/title/fan_speed_control
Psensor now shows both fans (GPU,CPU)

I test with rc.local - when the system boots it runs:
FALLBACK_ADDRS='1335 1431' FALLBACK_TEMPS='60 62 65 68 70 72 76 80' asus-fan-control set-temps default
[https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi0yeMR2IYsGjPeHF9fJqD3OUuK6z1RuKPmb2RbMgxxOSX_Sr43EYciy10FHvPM1hR9BBPpvbarg9C7RpTip8Tdx8cVjX6g6uu6_S26qfAW089nv4R95apaKMIpPQ8hqy7gXzoXIg8Z9JI9IAaQcPg-rVJ4pYsVIXIg1x4B1hNuG0_duNSXWFjxeJKKVhs/s1920/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BA%D0%B0%20%D0%BD%D0%B0%20%D0%B5%D0%BA%D1%80%D0%B0%D0%BD%D0%B0_2023-07-21_21-02-15.png](url)
I thought everything was ok, but...

The problem:
After one of the restarts, the fans disappeared from Psensor ...lm-sensors
I'm not sure what the reason is yet.

**Comment by dominiksalvet** [comment]
Hello @nick-dimitrov, I am sorry but I cannot help with any sensors. All I do is this utility, nothing more... I will add the support for your device in the next release.
