### ISSUE TITLE
ASUSPRO B9440UA

### ISSUE THREAD

**Issue by fzwoch** [dominiksalvet/asus-fan-control#14]
**Environment**
Debian Sid (Debian 5.4.6-1 (2019-12-27) x86_64 GNU/Linux)
asus-fan-control 2.11.0 (4be140b3a39c0ab7c5d9e453b8dae25594cb5e4c)

**Temperature configuration**
`60 65 68 70 72 74 76 80`

**Notebook model name**
`B9440UA`

Finally! Thanks for this work. I'm no fan/thermal expert, so I looked at default values for the default laptop and adjusted from gut feeling.

This model for me is notorious for spinning up its fans for every (short) action you take - loading a new tab in Firefox, opening applications etc.. So my main purpose was just to raise the lower threshold a bit so I could do daily work in a more peaceful environment.

It feels like the fans kick in a little earlier than their thresholds set when I compare to what I read out of `/sys/class/thermal/thermal_zone0/temp`. But that may be due to the accuracy and interval I read out these values.

**Comment by dominiksalvet** [comment]
I am really glad that you like this program. It originally was only for my personal purpose, I am really happy seeing all the people using it! :heart: 

Thank you so much for the contribution! :rocket: I have added the support for your model in [2.12.0](https://github.com/dominiksalvet/asus-fan-control/releases/tag/2.12.0). Feel free to use `sudo gitpack install github.com/dominiksalvet/asus-fan-control` to install the latest release and your model should be recognized automatically... I am closing this issue as resolved. **Nevertheless, let me know whether it works.**

---

> It feels like the fans kick in a little earlier than their thresholds set when I compare to what I read out of `/sys/class/thermal/thermal_zone0/temp`. But that may be due to the accuracy and interval I read out these values.

Yeah, it looks like there are some `<temperature>-<speed level>` deviations while driving the fans. I still can't say why, but I suspect that hardware is responsible for it. E.g., I can think of averaging multiple thermal zones temperatures to get the final controlling temperature. Still, I do not consider this a problem.

**Comment by fzwoch** [comment]
I did not try with `gitpack` yet, but I assume that system works. I manually `cp data/default-temps /usr/share/asus-fan-control/.` and run the program. No errors or output seen with `-set-default-temps` and `-get-temps` showed the expected values. Looking good.

**Comment by dominiksalvet** [comment]
Glad to hear that! :smile:
