### ISSUE TITLE
Add support for F515EA

### ISSUE THREAD

**Issue by LiSiTuS12** [dominiksalvet/asus-fan-control#143]
**Environment**
AFC version 3.15.0, Debian 12, and 11th Gen Intel® Core™ i3-1115G4 @ 3.00GHz

**Basic configuration**

(not work)

**Advanced configuration**
(not work)

**It does not work**
If neither configuration was working for your device, community involvement is required. Please provide some information so the community can build on something. Why does AFC not work? What have you tried?

acpi call failed with 'Error: AE_NOT_FOUND'

**Additional context**

I have tried to uninstall but i can't uninstall either

**Comment by dominiksalvet** [comment]
What is the error report during uninstallation?

**Comment by LiSiTuS10** [comment]
I tried apt --purge remove but no uninstall the program in error "the program not exist" WTF

**Comment by dominiksalvet** [comment]
I assume you installed it using GitPack. You need to run `sudo gitpack uninstall https://github.com/dominiksalvet/asus-fan-control`.
