### ISSUE TITLE
Add support for X540LA

### ISSUE THREAD

**Issue by anzepintar** [dominiksalvet/asus-fan-control#144]
**Environment**
Asus Fan Control Version: 3.15.0
OS: Debian GNU/Linux 12 (bookworm) x86_64
Kernel: 6.1.0-11-amd64
CPU: Intel i3-5005U (4) @ 1.900GHz

**Basic configuration**

* `sudo asus-fan-control get-temps`
40 45 50 55 60 65 70 75
* `sudo asus-fan-control model-info` 
name X540LA
addresses 1335
default-temps 55 60 62 65 68 72 76 80
tested false

**Additional context**
Everything works

**Comment by dominiksalvet** [comment]
@anzepintar please can you prepare a PR? You can use cc9f9719cedd270977817676c238d2d7b4f1d6d4 as inspiration...
