### ISSUE TITLE
Add support for Zenbook UP6502ZD

### ISSUE THREAD

**Issue by aspizu** [dominiksalvet/asus-fan-control#145]
**Environment**
State your AFC version, OS version, and CPU name.

* `sudo asus-fan-control model-info`
name ZenbookUP6502ZDUP6502ZD
addresses 1335
default-temps 55 60 62 65 68 72 76 80
tested false

**It does not work**

**Comment by dominiksalvet** [comment]
When you run `sudo asus-fan-control`, does it report something?

**Comment by dominiksalvet** [comment]
Unfortunately, this issue cannot be fixed.

**Comment by aspizu** [comment]
bruh
