### ISSUE TITLE
Add support for UM3504D

### ISSUE THREAD

**Issue by flav-code** [dominiksalvet/asus-fan-control#146]
**Environment**
fedora with gnome
UM3504D
![image](https://github.com/dominiksalvet/asus-fan-control/assets/48295189/9dd20449-fd7e-4ed1-b13d-f095077ce39b)

**Comment by dominiksalvet** [comment]
Please fill the following template:

**Environment**
State your AFC version, OS version, and CPU name.

**Basic configuration**
If only temperatures were set and they worked, add output of:
* `sudo asus-fan-control get-temps` (new default temperatures for your device)
* `sudo asus-fan-control model-info`

**Advanced configuration**
If advanced configuration was used, add output of:
* `sudo FALLBACK_ADDRS='<addrs>' FALLBACK_TEMPS='<temps>' asus-fan-control model-info`

**It does not work**
If neither configuration was working for your device, community involvement is required. Please provide some information so the community can build on something. Why does AFC not work? What have you tried?

**Additional context**
Add any additional context.
