### ISSUE TITLE
Add support for K6502HE

### ISSUE THREAD

**Issue by 428-cobrajet** [dominiksalvet/asus-fan-control#148]
**
* Version 3.15.0 (latest git)
* [Asus Vivobook Pro 15](https://www.asus.com/uk/laptops/for-creators/vivobook/asus-vivobook-pro-15-oled-k6502/techspec/)
* Neofetch
    * ![image](https://github.com/dominiksalvet/asus-fan-control/assets/72269635/ddef3e2c-6afe-42af-95d2-8efe114adf87)

**It does not work**

* I am unable to run`afc-scout`
```
 sudo afc-scout
------ base address 1335 ------
acpi call failed with 'Error: AE_NOT_FOUND'
```
When installing `asus-fan-control` I have the same error
```
running script .install/install-global-Linux
copying files
enabling systemd service
loading acpi_call module first time
applying fan speed changes
acpi call failed with 'Error: AE_NOT_FOUND'
failed to apply changes now; reboot may help
adding to status database
```

I have the `asus-wmi` driver loaded which also has an error loading default fan curves  
`asus_wmi: fan_curve_get_factory_default (0x00110024) failed: -19`

**Additional context**
This laptop relies on the MyAsus app on Windows

**Comment by dominiksalvet** [comment]
Unfortunately, this is a known issue without any solution so far.
