### ISSUE TITLE
Add support for UX3402ZA

### ISSUE THREAD

**Issue by irvng-wav** [dominiksalvet/asus-fan-control#151]
**Environment**
AFC Version: 3.15.0
OS version: Arch Linux with Kernel Linux 6.7.9-arch1-1
CPU Name: 12th Gen Intel® Core™ i7-1260P × 16

**It does not work**
I get the infamous `acpi call failed with 'Error: AE_NOT_FOUND'`. I know that right now there's no solution for it but I want to keep the conversation going. 

**Additional context**
I found [this article](https://wiki.archlinux.org/title/ASUS_Zenbook_UM3402YAR#Fan_control) on the Arch Wiki about the ASUS Zenbook UM3402YAR, which is basically the same laptop but with an AMD cpu and gpu. There's a tutorial on how to change the fan profiles with a tool called [nbfc](https://github.com/hirschmann/nbfc) which looks like it isn't maintained anymore, so I found an up to date Linux fork called [nbfc-linux](https://github.com/nbfc-linux/nbfc-linux).

In Windows, you get the MyAsus App which lets you choose between three different fan profiles: Quiet, Balanced, and Performance. As I understand, each one of those modes has an hexadecimal value that you can manually set with the nbfc or nbfc-linux tool, that's explained in the Arch Wiki. I'm able to change between those fan modes, and it actually works. When I write the value for the quiet mode, the fans go quiet, and when I write it for the performance mode, the fans do start spinning faster but not as they do with Windows.

That's where I'm at. It kinda works. I installed the DOOM 2016 game both in Windows and Linux. In Windows, when the fan profile is either at Quiet or Balanced, the game runs at around 30 to 40 fps. But then if I engage the performance mode, the fans start working intensely and the game ramps up to a stable 60 fps. That doesn't happen on Linux. Either one of the three modes basically offers the same performance as Quiet or Balanced in Windows, meaning 30 to 40 fps.

Also I do music production as a part time freelance job. There's one piece of software called [Vital](https://vital.audio/), which runs perfectly on Windows with the performance mode, but sometimes struggles with the other two fan modes. In Linux I get the same performance with all three modes, and like with DOOM, it doesn't run quite as great as Windows with the performance mode.

Still, Linux is an awesome experience with this machine, and most of my needs are covered in it's current state. But dammit Asus, I want a true performance mode in Linux.

I hope we can get it to that state someday. Thank you @dominiksalvet for your work!

**Comment by dominiksalvet** [comment]
Hmmm... I think I saw similar behavior somewhere in the AFC issues. Unfortunately, I do not remember where, so I can't point you to the issue. Maybe try searching "max" among all issues.

Should you find something interesting, definitely link this issue with it, so people have more context. I can keep this issue open as long as it is relevant.

**Comment by akvadrako** [comment]
I also get this `acpi call failed with 'Error: AE_NOT_FOUND'` error with my Asus Zenbook UX3404VC. Same with `afc-scout` for the recommended ranges.

I gather this is a common issue, but what does it mean? Is there anything I can do to help?

**Comment by akvadrako** [comment]
Well I have figured out how to read the fan mode with acpi_call:

```
echo '\_SB_.PC00.LPCB.H_EC.ECRD "QFAN"'> /proc/acpi/call
cat /proc/acpi/call
```

To write the fan mode, one can use `\.ATKD.FANL 1` (1=silent, 0=default, 2=performance)

**Comment by dominiksalvet** [comment]
@akvadrako Well, I believe that your examination could help someone (at least with the same laptop). :rocket:  Maybe you could create a simple script and publish it on GitHub. If so, you can use, just like AFC, GitPack for its distribution since it's completely effortless. Think about it :smiley:

**Comment by akvadrako** [comment]
For now if anyone has this issue they can find it here. And it should be fixed in a near future kernel version so anybody can use the standard `/sys/firmware/acpi/platform_profile`.

https://lore.kernel.org/platform-driver-x86/20240609144849.2532-1-mohamed.ghanmi@supcom.tn/T/

**Comment by akvadrako** [comment]
That seems correct. It says your fan mode is Standard.

To set silent mode use `echo '\.ATKD.FANL 1' > /proc/acpi/call`

**Comment by akvadrako** [comment]
Then I guess that laptop is different. If you want to try to discover the right call, you have to investigate the ACPI tables. https://wiki.archlinux.org/title/DSDT is a good intro, but it's basically a bunch of guesswork.

**Comment by irvng-wav** [comment]
@barolo you got me excited, but unfortunately it's not working the way it's working for you. I have set `0x61` to `0x02` (performance mode) and `0x74` was already set to `3A`, but the fans are still wimpy:

```
[irvng@arch-zenbook ~]$ sudo ec_probe read 0x61
2 (02)
[irvng@arch-zenbook ~]$ sudo ec_probe read 0x74
58 (3A)
``` 

But I'm still on Kernel 6.9.10, so that makes me think that maybe they fixed this issue in kernel 6.10. I will have to wait until the Arch Linux team pushes it to the main repo to put it to the test.

I'm so glad you got it working!

**Comment by irvng-wav** [comment]
Hey @barolo I just upgraded my system to kernel 6.10 and followed your advice but for some reason the fan behavior doesn't change. Here are all the steps I did:

1. Updated my system to kernel 6.10, then restarted the machine to boot into the new kernel.
2. Changed the fan profile to performance with `sudo ec_probe write 0x61 0x02`.
3. Put my pc under a stress test using the `s-tui` tool to see if anything had changed but the behavior was the same: The CPU usage went up to 100% with (CPU) temps of around 70° C and avg frequency of 2250 MHz. Fan speed didn't change.

So then I followed the advice of your last comment. I use the tool `auto-cpufreq` to set the CPU governor and EPP to performance when the laptop is connected to the charger. Here's a screenshot of that tool:
![imagen](https://github.com/user-attachments/assets/27069ddb-4a50-4f72-81c9-57a53b4c89de)
Is EPP the "performance platform profile" you're talking about?

Then I visited the arch wiki article you linked, checked the status of ASPM and it already was enabled:
```
[irvng@arch-zenbook ~]$ sudo lspci -vv | grep 'ASPM.*abled;'
[sudo] contraseña para irvng: 
		LnkCtl:	ASPM L1 Enabled; RCB 64 bytes, LnkDisable- CommClk-
		LnkCtl:	ASPM L1 Enabled; RCB 64 bytes, LnkDisable- CommClk-
		LnkCtl:	ASPM L1 Enabled; RCB 64 bytes, LnkDisable- CommClk-
		LnkCtl:	ASPM L1 Enabled; RCB 64 bytes, LnkDisable- CommClk-
		LnkCtl:	ASPM L1 Enabled; RCB 64 bytes, LnkDisable- CommClk+
		LnkCtl:	ASPM L1 Enabled; RCB 64 bytes, LnkDisable- CommClk+
``` 
So I changed the policy to performance with
```
# echo performance > /sys/module/pcie_aspm/parameters/policy
``` 

With all of that done I again engaged the stress test but nothing changes. I even disabled and uninstalled thermald to see if that changed anything but nope.

Note that I'm not using `asus-fan-control`. I don't have it installed.

Am I missing something?

**Comment by irvng-wav** [comment]
@barolo I just played for a little bit with TLP following your instructions but I still couldn't get it to sound like a hair dryer as you describe. Maybe I'll come back to it again in the following days.

I'm curious, could you do a Geekbench 6 benchmark with your current setup to compare it to the benchmarks I've done on my laptop?

Here's one with Windows using performance fan mode:
[Geekbench 6: UX3402ZA - Windows 11 Pro - 2347 Single-Core Score - 10155 Multi-Core Score](https://browser.geekbench.com/v6/cpu/5683707)

Here's one with my current Linux setup and everything also set to performance:
[Geekbench 6: UX3402ZA - Arch Linux - 2341 Single-Core Score - 8020 Multi-Core Score](https://browser.geekbench.com/v6/cpu/7104869)

**Comment by irvng-wav** [comment]
@barolo Amazing news! It's giving you even better results than Windows. I'll try to do the same later in the day. Can you tell me specifically what you did?

**Comment by irvng-wav** [comment]
@barolo you're the bomb! Take a look at this:
![imagen](https://github.com/user-attachments/assets/b22e9dbf-75d4-4c8e-9c0f-7e71f0486361)
Now the cpu is clocked way higher than it was before. But I'm kinda worried about the temps. What do you think?

**Comment by irvng-wav** [comment]
@barolo thank you for helping figuring out this issue! I've seen threads on the internet posted years ago complaining about the CPU performance on Linux with these newer Zenbook laptops and I think some Vivobooks too. I myself started this project of making the best possible Linux experience that this machine can offer, and now virtually everything is working.

As you said, sound didn't work for a while but with kernel 6.7 or 6.8 (can't remember which one) the sound started working without manual patches. The fingerprint works thanks to [this](https://gitlab.freedesktop.org/libfprint/libfprint/-/merge_requests/330) (Installed it on my system thanks to [this](https://aur.archlinux.org/packages/libfprint-elanmoc2-working-git)), although that one took me a while to get the hang of. The numpad works even better than on Windows thanks to [this project](https://github.com/asus-linux-drivers/asus-numberpad-driver), where I got involved reporting as many bugs and improvements to the developer, and now you helped me solve the CPU throttling issue! Thank you again!

I did some music production tests after raising the power constraints and it performed better, but then I launched the software I use (Bitwig Studio) with performance cores only and it got even better performance. I'll compare it to how it behaves on Windows.

The next steps for me are doing more performance tests with this new configuration, and also gaming tests with the new [Xe graphics driver](https://wiki.archlinux.org/title/Intel_graphics#Testing_the_new_experimental_Xe_driver) that you mentioned. I'm using GNOME and looks like HDR is still an experimental feature but I don't mind, the screen still looks amazing without it and also I need color accuracy for design work.

Would love to keep in touch to further discuss and share our findings about how we can improve the Linux experience on this machine. My discord username is `irvng.` (dot included) if you want to add me, also if anyone else is interested feel free to add me also.

Cheers!

**Comment by dominiksalvet** [comment]
@irvng-wav Can I mark this issue with `alternative found` label?

**Comment by irvng-wav** [comment]
> @irvng-wav Can I mark this issue with `alternative found` label?

Sure! Thank you. 😁

**Comment by Acorde17** [comment]
Any news on this? AFAIK this problem still exist in 6.12.10-arch1-1 and i am unable to fix it with the steps described above 🤕

**Comment by irvng-wav** [comment]
> Any news on this? AFAIK this problem still exist in 6.12.10-arch1-1 and i am unable to fix it with the steps described above 🤕

Do you have the same computer (UX3402ZA)?

Since closing this thread, @barolo and me have discovered a better and simpler way to solve this issue, here's how it works on my system:

I created three different bash scripts inside `/bin`, one for each power profile:

### performance-mode.sh
```bash
#!/bin/sh
echo performance | tee /sys/firmware/acpi/platform_profile
powercap-set intel-rapl --zone=0 --constraint=2 -l 88000000
systemctl stop thermald
```  

### balanced-mode.sh
```bash
#!/bin/sh
echo balanced | tee /sys/firmware/acpi/platform_profile
powercap-set intel-rapl --zone=0 --constraint=2 -l 64000000
systemctl start thermald
``` 

### quiet-mode.sh
```bash
#!/bin/sh
echo quiet | tee /sys/firmware/acpi/platform_profile
powercap-set intel-rapl --zone=0 --constraint=2 -l 45000000
systemctl start thermald
``` 

There are three commands in each script, the first one controls the fan mode, the second one changes the power constraint [TDP] for CPU zone, and the third one enables or disables thermald, which has to be disabled in order for the performance mode to work at it's fullest.

Then I configured those scripts to launch with different keyboard shortcuts:
`pkexec /bin/performance-mode.sh` with Ctrl + Super + P
`pkexec /bin/balanced-mode.sh` with Ctrl + Super + B
`pkexec /bin/quiet-mode.sh` with Ctrl + Super + Q

`pkexec` allows you to execute the scripts with sudo privileges, which is needed for the commands inside the scripts to work.

### Additional info

From my understanding, the first command should also set the correct power constraints for the CPU but it doesn't, I arrived at those values through experimentation using the `s-tui` stress test and the game DOOM (2016) as benchmarks, I'll share the results from the later if anyone's curious:

| Power constraints*             | FPS inside DOOM | Fan noise** | Notes                                                                                                             |
| ------------------------------ | --------------- | ----------- | ----------------------------------------------------------------------------------------------------------------- |
| c1 = 64 watts<br>c2 = 45 watts | 28              | 31.6 dB     | These are the default values at boot.                                                                             |
| c1= 64 watts<br>c2 = 64 watts  | 36 - 37         | 38.3 dB     |                                                                                                                   |
| c1 = 64 watts<br>c2 = 88 watts | 44              | 45 dB       | From my tests, any value above 85 watts delivers the same results, so there's no point in setting a higher limit, I set it a 88 just in case. |

*c1 is constraint=1 and c2 is constraint=2
**Measured at my head level

As you can see, now DOOM behaves as it does on Windows, getting a remarkable FPS boost when the performance mode is engaged.

**Comment by Acorde17** [comment]
I have the UX3402VA model with a i7-1360p instead of the i7-1260p you both have but I assume that shouldn't matter, CPU aside the models seem to be pretty much the same so this should work for me too.

**Comment by Acorde17** [comment]
![Image](https://github.com/user-attachments/assets/6343628e-896a-4b34-9701-00d2b90c111d)

Well, seems that this fix doesn't work with 13th gen CPUs.

**Comment by irvng-wav** [comment]
@Acorde17 what's your output of these commands? `cat /sys/firmware/acpi/platform_profile_choices` and `powercap-info`

**Comment by Acorde17** [comment]
`cat /sys/firmware/acpi/platform_profile_choices` outputs:
 `quiet balanced performance`

`powercap-info` outputs:
`intel-rapl-mmio
  enabled: 1
  Zone 0
    name: package-0
    enabled: 1
    max_energy_range_uj: 262143328850
    Constraint 0
      name: long_term
      power_limit_uw: 28000000
      time_window_us: 27983872
      max_power_uw: 28000000
    Constraint 1
      name: short_term
      power_limit_uw: 30000000
      time_window_us: 2440
      max_power_uw: 0
    Constraint 2
      name: peak_power
      power_limit_uw: 126000000
      max_power_uw: 0
intel-rapl
  enabled: 1
  Zone 0
    name: package-0
    enabled: 1
    max_energy_range_uj: 262143328850
    Constraint 0
      name: long_term
      power_limit_uw: 35000000
      time_window_us: 27983872
      max_power_uw: 28000000
    Constraint 1
      name: short_term
      power_limit_uw: 44000000
      time_window_us: 2440
      max_power_uw: 0
    Constraint 2
      name: peak_power
      power_limit_uw: 126000000
      max_power_uw: 0
    Zone 0:0
      name: core
      enabled: 0
      max_energy_range_uj: 262143328850
      Constraint 0
        name: long_term
        power_limit_uw: 0
        time_window_us: 976
    Zone 0:1
      name: uncore
      enabled: 0
      max_energy_range_uj: 262143328850
      Constraint 0
        name: long_term
        power_limit_uw: 0
        time_window_us: 976
  Zone 1
    name: psys
    enabled: 1
    max_energy_range_uj: 262143328850
    Constraint 0
      name: long_term
      power_limit_uw: 28000000
      time_window_us: 27983872
    Constraint 1
      name: short_term
      power_limit_uw: 35000000
      time_window_us: 976
`

**Comment by irvng-wav** [comment]
@Acorde17 could you change the formatting of the powercap output? to make it look like this:

```
intel-rapl-mmio
  enabled: 1
  Zone 0
    name: package-0
    enabled: 1
    max_energy_range_uj: 262143328850
    Constraint 0
      name: long_term
      power_limit_uw: 40000000
      time_window_us: 27983872
      max_power_uw: 28000000
    Constraint 1
      name: short_term
      power_limit_uw: 30000000
      time_window_us: 2440
      max_power_uw: 0
    Constraint 2
      name: peak_power
      power_limit_uw: 64000000
      max_power_uw: 0
intel-rapl
  enabled: 1
  Zone 0
    name: package-0
    enabled: 1
    max_energy_range_uj: 262143328850
    Constraint 0
      name: long_term
      power_limit_uw: 200000000
      time_window_us: 27983872
      max_power_uw: 28000000
    Constraint 1
      name: short_term
      power_limit_uw: 64000000
      time_window_us: 2440
      max_power_uw: 0
    Constraint 2
      name: peak_power
      power_limit_uw: 64000000
      max_power_uw: 0
    Zone 0:0
      name: core
      enabled: 0
      max_energy_range_uj: 262143328850
      Constraint 0
        name: long_term
        power_limit_uw: 0
        time_window_us: 976
    Zone 0:1
      name: uncore
      enabled: 0
      max_energy_range_uj: 262143328850
      Constraint 0
        name: long_term
        power_limit_uw: 0
        time_window_us: 976
  Zone 1
    name: psys
    enabled: 1
    max_energy_range_uj: 262143328850
    Constraint 0
      name: long_term
      power_limit_uw: 58000000
      time_window_us: 4997120
    Constraint 1
      name: short_term
      power_limit_uw: 58000000
      time_window_us: 976
``` 

Use the code block instead

**Comment by Acorde17** [comment]
My bad 😅, here is the output of Performance and Quiet mode:

`/bin/performance-mode.sh`:
```
intel-rapl-mmio
  enabled: 1
  Zone 0
    name: package-0
    enabled: 1
    max_energy_range_uj: 262143328850
    Constraint 0
      name: long_term
      power_limit_uw: 28000000
      time_window_us: 27983872
      max_power_uw: 28000000
    Constraint 1
      name: short_term
      power_limit_uw: 30000000
      time_window_us: 2440
      max_power_uw: 0
    Constraint 2
      name: peak_power
      power_limit_uw: 88000000
      max_power_uw: 0
intel-rapl
  enabled: 1
  Zone 0
    name: package-0
    enabled: 1
    max_energy_range_uj: 262143328850
    Constraint 0
      name: long_term
      power_limit_uw: 35000000
      time_window_us: 27983872
      max_power_uw: 28000000
    Constraint 1
      name: short_term
      power_limit_uw: 88000000
      time_window_us: 2440
      max_power_uw: 0
    Constraint 2
      name: peak_power
      power_limit_uw: 88000000
      max_power_uw: 0
    Zone 0:0
      name: core
      enabled: 0
      max_energy_range_uj: 262143328850
      Constraint 0
        name: long_term
        power_limit_uw: 0
        time_window_us: 976
    Zone 0:1
      name: uncore
      enabled: 0
      max_energy_range_uj: 262143328850
      Constraint 0
        name: long_term
        power_limit_uw: 0
        time_window_us: 976
  Zone 1
    name: psys
    enabled: 1
    max_energy_range_uj: 262143328850
    Constraint 0
      name: long_term
      power_limit_uw: 28000000
      time_window_us: 27983872
    Constraint 1
      name: short_term
      power_limit_uw: 35000000
      time_window_us: 976
```

`/bin/quiet-mode.sh`:
```
intel-rapl-mmio
  enabled: 1
  Zone 0
    name: package-0
    enabled: 1
    max_energy_range_uj: 262143328850
    Constraint 0
      name: long_term
      power_limit_uw: 35000000
      time_window_us: 27983872
      max_power_uw: 28000000
    Constraint 1
      name: short_term
      power_limit_uw: 30000000
      time_window_us: 2440
      max_power_uw: 0
    Constraint 2
      name: peak_power
      power_limit_uw: 45000000
      max_power_uw: 0
intel-rapl
  enabled: 1
  Zone 0
    name: package-0
    enabled: 1
    max_energy_range_uj: 262143328850
    Constraint 0
      name: long_term
      power_limit_uw: 35000000
      time_window_us: 27983872
      max_power_uw: 28000000
    Constraint 1
      name: short_term
      power_limit_uw: 45000000
      time_window_us: 2440
      max_power_uw: 0
    Constraint 2
      name: peak_power
      power_limit_uw: 45000000
      max_power_uw: 0
    Zone 0:0
      name: core
      enabled: 0
      max_energy_range_uj: 262143328850
      Constraint 0
        name: long_term
        power_limit_uw: 0
        time_window_us: 976
    Zone 0:1
      name: uncore
      enabled: 0
      max_energy_range_uj: 262143328850
      Constraint 0
        name: long_term
        power_limit_uw: 0
        time_window_us: 976
  Zone 1
    name: psys
    enabled: 1
    max_energy_range_uj: 262143328850
    Constraint 0
      name: long_term
      power_limit_uw: 28000000
      time_window_us: 27983872
    Constraint 1
      name: short_term
      power_limit_uw: 35000000
      time_window_us: 976
```

**Comment by irvng-wav** [comment]
@Acorde17 Thank you, now can you share your `powercap-info` without it being affected by any of the scripts? Restart your computer and run the command again

**Comment by Acorde17** [comment]
The default values after rebooting are the following:
```
intel-rapl-mmio
  enabled: 1
  Zone 0
    name: package-0
    enabled: 1
    max_energy_range_uj: 262143328850
    Constraint 0
      name: long_term
      power_limit_uw: 15000000
      time_window_us: 27983872
      max_power_uw: 28000000
    Constraint 1
      name: short_term
      power_limit_uw: 30000000
      time_window_us: 2440
      max_power_uw: 0
    Constraint 2
      name: peak_power
      power_limit_uw: 126000000
      max_power_uw: 0
intel-rapl
  enabled: 1
  Zone 0
    name: package-0
    enabled: 1
    max_energy_range_uj: 262143328850
    Constraint 0
      name: long_term
      power_limit_uw: 200000000
      time_window_us: 27983872
      max_power_uw: 28000000
    Constraint 1
      name: short_term
      power_limit_uw: 44000000
      time_window_us: 2440
      max_power_uw: 0
    Constraint 2
      name: peak_power
      power_limit_uw: 126000000
      max_power_uw: 0
    Zone 0:0
      name: core
      enabled: 0
      max_energy_range_uj: 262143328850
      Constraint 0
        name: long_term
        power_limit_uw: 0
        time_window_us: 976
    Zone 0:1
      name: uncore
      enabled: 0
      max_energy_range_uj: 262143328850
      Constraint 0
        name: long_term
        power_limit_uw: 0
        time_window_us: 976
  Zone 1
    name: psys
    enabled: 1
    max_energy_range_uj: 262143328850
    Constraint 0
      name: long_term
      power_limit_uw: 28000000
      time_window_us: 27983872
    Constraint 1
      name: short_term
      power_limit_uw: 35000000
      time_window_us: 976
```

**Comment by irvng-wav** [comment]
@Acorde17 In your case I would experiment changing `Constraint 1` of `intel-rapl`, **but be careful and do it in small steps, proceed at your own risk.**

The default value is 44 watts which is quite low, so I think that could be causing the throttling. Constraint 2 for you is 126 watts so I think you shouldn't touch that value.

```
intel-rapl
  enabled: 1
  Zone 0
    name: package-0
    enabled: 1
    max_energy_range_uj: 262143328850
    Constraint 0
      name: long_term
      power_limit_uw: 200000000
      time_window_us: 27983872
      max_power_uw: 28000000
    Constraint 1
      name: short_term
      power_limit_uw: 44000000
      time_window_us: 2440
      max_power_uw: 0
    Constraint 2
      name: peak_power
      power_limit_uw: 126000000
      max_power_uw: 0
``` 

Try this:

First set the platform profile to performance.
```bash
echo performance | sudo tee /sys/firmware/acpi/platform_profile
``` 

Then stop thermald if you have it installed and enabled.
```
systemctl stop thermald
``` 

Now experiment raising `constraint 1` of `intel-rapl` in a careful manner and see if it has any effect on the stress test performance and fan noise. If it's doing anything I think you should clearly notice it with 64 watts. Also make sure your laptop is connected to AC and charging throughout this process. 
```
sudo powercap-set intel-rapl --zone=0 --constraint=1 -l 54000000
``` 
``` 
sudo powercap-set intel-rapl --zone=0 --constraint=1 -l 64000000
``` 
``` 
sudo powercap-set intel-rapl --zone=0 --constraint=1 -l 70000000
``` 
etc.

With my computer the performance gains and fan noise capped at around 85000000, **but that is for constraint 2 (peak_power)**, so **if the values above worked** maybe you can use this as a reference.

**Comment by Acorde17** [comment]
Ok, I'll try to modify the values ​​and post the results here for anyone else who finds themselves in my situation. Thanks for your help @irvng-wav  , you have helped me a lot!!
