### ISSUE TITLE
Add support for FX516PMFX516PM

### ISSUE THREAD

**Issue by Offhornet28** [dominiksalvet/asus-fan-control#152]
**Environment**
AFC Version: 3.15.0
OS Version: Ubuntu 22.04.4 LTS with kernel Linux 6.5.0-26-generic
CPU name: 11th Gen Intel® Core™ i7-11370H @ 3.30GHz × 8

**Basic configuration**
when running the command `sudo asus-fan-control model-info` I get:
name ASUSTUFDashF15FX516PMFX516PM
addresses 1335
default-temps 55 60 62 65 68 72 76 80
tested false

  Hello, I am very happy you have chosen to try out asus-fan-control (AFC).
  AFC is an open-source project and without community contributions there
  would not be so many devices tested. It appears you have an untested device
  and so if AFC works on it, please consider letting the AFC developers know
  this fact on the official AFC GitHub. Then, your device will be recognized
  as tested. It may also significantly help people with the same device. See
  the contributing.md file for more details. Thank you.
                                              - Dominik Salvet, the AFC author

When I run the command `sudo asus-fan-control get-temps` I get: 
acpi call failed with 'Error: AE_NOT_FOUND'

**It does not work**
To quote another issue posted here I get the infamous `acpi call failed with 'Error: AE_NOT_FOUND'`. It is unclear to me if it still does not work or that something else is the issue. 

**Additional context**
I do have an intel cpu and nivida 3060 laptop gpu. I have turned off secure boot. I have run the `sudo sensors-detect command`. I have tried to uninstall/purge and reinstall the `acpi-call-dkms` package with and without reboots and it still doesn't work. I mainly use this linux install for development work and I do not want to burn out my cpu accidentally when I run some of my more intensive data processing projects.

**Comment by dominiksalvet** [comment]
Well, the current status with the `AE_NOT_FOUND` issues is that it just does not work. The AFC uses some pre-defined ACPI addresses that are assumed to be controlling fans (which is true for many ASUS devices -- see README) but unfortunately, probably ASUS changed something later and it does not work with all models.

What is not clear is whether AFC can adapt to the methods of driving fans on such unsupported models, or whether they use a significantly different method of controlling fans incompatible with AFC. So far we only know that AMD-based devices do not work with AFC.

We probably won't solve the `AE_NOT_FOUND` issues here but should you find an alternative to AFC for your device, please keep us updated.
