### ISSUE TITLE
Error in UX410UA model

### ISSUE THREAD

**Issue by fsanzdev** [dominiksalvet/asus-fan-control#2]
**Environment**
Ubuntu 19.04

**Describe the bug**
When running the script I get this error

ubuntu@ubuntu:/tmp/gim$ sudo asus-fan-control
/usr/local/bin/asus-fan-control: Missing temperatures for your notebook model or they are invalid. Falling back to the UX430UA temperatures.
POSSIBLE SOLUTIONS:
  * Uninstall asus-fan-control and install it again.
  * Contact an asus-fan-control developer.

**To Reproduce**
sudo asus-fan-control

**Additional context**
Although I get the error the script looks like is working since the fan stops after a while.

ubuntu@ubuntu:/tmp/gim$ sudo asus-fan-control -get-temps
55 60 62 65 68 72 76 80

ubuntu@ubuntu:/tmp/gim$ sudo dmidecode -s system-product-name
UX410UAK

**Comment by dominiksalvet** [comment]
Hello! I understand that you would like to **add your notebook model** to the list of the supported models. There is a GitHub issue template for that called 'New notebook model', which you could have chosen during creating the issue. But let it this way in that case. :smile:

Please, make sure that your proposed temperatures are appropriate for your model load to prevent overheating. Also, make sure that the proposed model is `UX410UAK` and not `UX410UA` only. Then let me know and I will include your model to the latest release of this program.

**Comment by dominiksalvet** [comment]
BTW, you can test different temperatures by the following command: `sudo asus-fan-control -set-temps:<numbers>` to find the best ones.

**Comment by fsanzdev** [comment]
The model as it comes in the box is UX410UA, but when running `dmidecode` I get UX410UAK. About the temperatures, it looks like this model is the UX430UA with some minimal changes so I guess those temperatures are fine.

**Comment by dominiksalvet** [comment]
Your model is included in the [2.5.0](https://github.com/dominiksalvet/asus-fan-control/releases/tag/2.5.0) release. Just use `sudo gim install github.com/dominiksalvet/asus-fan-control` to update. Please, let me know whether everything is fine. :smile:
