### ISSUE TITLE
Add support for ASUS ROG GL502VSK

### ISSUE THREAD

**Issue by Mikarox** [dominiksalvet/asus-fan-control#24]
**Environment**
asus-fan-control Latest version 3.3.0 
OS: Pop_OS! 19.10 (5.3.0-7629-generic)

**Basic configuration**
If only temperatures were configured, add output of:

Use your own configurations since in general there was no ventilation operation

* `sudo asus-fan-control get-temps`
```
30 35 40 45 50 55 60 65
```

* `sudo asus-fan-control model-info`
```
name GL502VSK
address 1335
temperatures 55 60 62 65 68 72 76 80
tested false
```

**Additional context**
Before testing this contribution, temperatures ranged between 50-60 degrees with a minimum fan speed (passive), now you even notice that it has ventilation. the maximum fan speed is approximately 4500 RPM.

Maxima test configuration:
  
> sudo asus-fan-control set-temps 10 15 20 25 30 35 40 45

Normal Configuration:

>  sudo asus-fan-control set-temps 30 35 40 45 50 55 60 65

Now temperatures range from 45-55 degrees with normal ventilation. The previously made settings are applied once the user logs in and are stable after a system restart

**demicode** 
* `sudo demicode`  = https://pastebin.com/76meGcd2

**Comment by dominiksalvet** [comment]
Hello @Mikarox and welcome to the asus-fan-control community! :wave:

I will add the support for your device in a moment. Your temperatures are quite low compared to other devices, so in case you find a better temperature configuration, let me know in this issue even after closing it...

> PS: You did not have to include the dmidecode output... :smile:

**Comment by dominiksalvet** [comment]
Your model is supported in the latest version [3.4.0](https://github.com/dominiksalvet/asus-fan-control/releases/tag/3.4.0). Update to it using:
```sh
sudo gitpack install github.com/dominiksalvet/asus-fan-control
```

Thank you so much for contributing to asus-fan-control and extending the tested devices list! :heart: Asus-fan-control now recognizes **10 different ASUS devices**! :rocket:
