### ISSUE TITLE
Add support for ASUS GL553VE

### ISSUE THREAD

**Issue by arruor** [dominiksalvet/asus-fan-control#25]
**Environment**
Latest version 3.4.0
System: Ubuntu 20.04

**Basic configuration**
* `sudo asus-fan-control get-temps`
```
45 50 55 60 65 70 75 80
```
* `sudo asus-fan-control model-info`
```
name GL553VE
address 1335
temperatures 55 60 62 65 68 72 76 80
tested false
```

**Additional context**
Please note that GL553VE shares same motherboard with FX553VE (in fact GL553FX is ROG branded FX553VE) and same issue, as mentioned in #23, could appear with this model.

Also,
please let me know if any further actions and/or more information is necessary to complete the tests.

Thank you.

**Comment by dominiksalvet** [comment]
Hello @arruor and welcome to the asus-fan-control community! :wave: :smile: 

I will add the support for your model in a moment. I will also release a new version once I figure out whether to include FX553VD (#23) in the release as well.

---

Regarding the FX553VE... I appreciate your initiative but I do not add devices that are not tested by someone. This is my main criterion in the process of adding new devices.

BTW we can come up with something else... Why don't you create a [new blank issue](https://github.com/dominiksalvet/asus-fan-control/issues/new) of looking for FX553VE tester kind (similar to #11) and feel free to describe the whole context in the issue. It would be great to mention that asus-fan-control most likely will run out of the box and that your the tester of GL553VE, which should have the same motherboard, etc. Then I will pin the issue and add 'help wanted' label to make it more reachable... What do you think? :smile:

**Comment by dominiksalvet** [comment]
Done! :smile: Feel free to use GitPack to update to the latest release.

**Thank you** so much for the contribution! :heart: :rocket: 

---

I will close this issue but If you have any comments/replies, feel free to let me know.

**Comment by arruor** [comment]
Hi @dominiksalvet and thank you for the warm welcome.
Apologies for delayed response, I've created separate issue for FX553VE as requested above.
