### ISSUE TITLE
Looking for an ASUS ZenBook UX430UN tester

### ISSUE THREAD

**Issue by dominiksalvet** [dominiksalvet/asus-fan-control#27]
Hello incomers! :wave:

We are **looking for someone who has an ASUS ZenBook UX430UN** (UX430UNR) laptop and will be able to test asus-fan-control whether it works on that model. I personally have a very similar model, UX430UA, so chances are enormously high that it will work out of the box! :1st_place_medal: Also, additional [information source](https://github.com/daringer/asus-fan/issues/44#issuecomment-596829858) hints the same.

Please, make yourself heard! :rocket:

**Comment by dominiksalvet** [comment]
@klausenbusk If you change your mind about testing AFC with UX430UN (if you still have it), please let me know. :smile:

**Comment by klausenbusk** [comment]
```sh
$ sudo bash asus-fan-control get-temps
55 60 62 65 68 72 76 80
```

Also you don't need `dmidecode` you can read the model from `/sys/class/dmi/id/product_name`.

**Comment by dominiksalvet** [comment]
Thank you, sure I was thinking about removing `dmidecode` from dependencies, maybe it will happen in the next release. 😉

So the default temperatures (which come from my UX430UA) are fine for your model? Please, add also output of `model-info` subcommand and that would be all... 🚀

**Comment by klausenbusk** [comment]
> So the default temperatures (which come from my UX430UA) are fine for your model?

They are the same, if that is what you are asking :)

```sh
$ sudo bash asus-fan-control model-info
name UX430UNR
addresses 1335
default-temps 55 60 62 65 68 72 76 80
tested false

  Hello, I am very happy you have chosen to try out asus-fan-control (AFC).
  AFC is an open-source project and without community contributions there
  would not be so many devices tested. It appears you have an untested device
  and so if AFC works on it, please consider letting the AFC developers know
  this fact on the official AFC GitHub. Then, your device will be recognized
  as tested, which may significantly help people with the same device. See the
  contributing.md file for more details. Thank you.
                                              - Dominik Salvet, the AFC author
```

**Comment by dominiksalvet** [comment]
Ok, thank you. :heart:

Your device has been added and `dmidecode` is no longer used in AFC. I guess I need to take some care now so that it behaves the same as `dmidecode` for other people as well. :rocket: Nevertheless, I like simple solutions. :+1:
