### ISSUE TITLE
New notebook model

### ISSUE THREAD

**Issue by MartinMyr** [dominiksalvet/asus-fan-control#3]
**Environment**
elementary OS 5.0 Juno

**Temperature configuration**
55 56 57 58 59 60 61 62

**Notebook model name**
VivoBook_ASUSLaptop X512FA_F512FA

**Comment by dominiksalvet** [comment]
Hi, thank you for your contribution! :+1: But unfortunately, I can't accept it at this point.

First, your temperature setup is almost unreal. Second, I am not quite sure that your output for 'Notebook model name' has been generated by the `sudo dmidecode -s system-product-name` command. Do you have any explanation for those values, please?

**Comment by MartinMyr** [comment]
Hi!
My problem is that my fan don't spin up properly when the cpu get's hot so it's kind of the opposite this project is for but i wanted to give it a try.

Here is the output:
_martin@martin:~$ sudo dmidecode -s system-product-name
VivoBook_ASUSLaptop X512FA_F512FA_

**Comment by dominiksalvet** [comment]
@MartinMyr That's very interesting ... :smiley:

> ASUS, what are you doing?? x))

---

Well, recently I have removed support for [gim](https://github.com/dominiksalvet/gim) and add support for its successor, [GitPack](https://github.com/dominiksalvet/gitpack). Please, **uninstall asus-fan-control using gim** and **install it using GitPack** to get the newest version. Future versions will be also distributed using GitPack.

After doing that, would the following temperatures fit your need - 55 57 59 61 63 65 67 69? One Celsius degree differences are, in my opinion, really small.

What is the output of the `sudo asus-fan-control` command on your system?

BTW, currently there is no support for system names with a whitespace character. I.e., it may take some time for me to implement it. Nevertheless, it is good to know that in a system name there may be a whitespace character ... :+1:

**Comment by MartinMyr** [comment]
^^
I have now uninstalled with gim and installer with GitPack.

Well it's worth a try atleast. ^^

When i run sudo asus-fan-control it dosen't give me any output what so ever :/ 

Ohh alright, well no rush. Im trying to find another solution in the mean time then :)

**Comment by dominiksalvet** [comment]
@MartinMyr Well, everything is all right. I will try to add support for your model ASAP.

BTW, there is no need to find another solution. Asus-fan-control will work perfectly fine on your system even without support for automatic temperature detection of your notebook model.

Whatsmore, I would be glad if you try my proposed temperatures. Use `sudo asus-fan-control -set-temps:'55 57 59 61 63 65 67 69'` and please let me know whether they are fine.

**Comment by MartinMyr** [comment]
@dominiksalvet :+1: :1st_place_medal: 

Get this output when i try " sudo asus-fan-control -set-temps:'55 57 59 61 63 65 67 69' "
/usr/local/bin/asus-fan-control: Missing temperatures for your notebook model or they are invalid. Falling back to the UX430UA temperatures.
POSSIBLE SOLUTIONS:
  * Uninstall asus-fan-control and install it again.
  * Contact an asus-fan-control developer.

**Comment by dominiksalvet** [comment]
@MartinMyr Well, that's interesting ... what's the output of `sudo asus-fan-control -get-temps`, please?

BTW ... you have tested your proposed temperatures (55 56 57 58 59 60 61 62) the way described above?

**Comment by MartinMyr** [comment]
<code>
martin@martin:~$ sudo asus-fan-control -get-temps 
55 56 57 58 59 60 61 62
</code>

Thats what i did :) 

<code>
martin@martin:~$ sudo asus-fan-control -set-temps:'55 57 59 61 63 65 67 69'
/usr/local/bin/asus-fan-control: Missing temperatures for your notebook model or they are invalid. Falling back to the UX430UA temperatures.
POSSIBLE SOLUTIONS:
  * Uninstall asus-fan-control and install it again.
  * Contact an asus-fan-control developer.
</code>

**Comment by dominiksalvet** [comment]
@MartinMyr Now it should be OK on the master branch (the error report should be gone). You can wait until I release the upcoming version, which will include it, as well as the native support for your notebook model.

OR

You can install it directly from the master branch using `sudo gitpack install github.com/dominiksalvet/asus-fan-control=master` and stick with that version until the next release.

**Comment by dominiksalvet** [comment]
@MartinMyr Your model should be tested and so recognisable by asus-fan-control in the latest version, 2.8.0. Update it using `sudo gitpack install github.com/dominiksalvet/asus-fan-control`. Please let me know whether everything is OK.

**Comment by MartinMyr** [comment]
@dominiksalvet It's working now :) Computer running smoothly and aren't overheating when i am loading cpu. Thank you for the support!

**Comment by dominiksalvet** [comment]
@MartinMyr Glad to hear that! :smiley: Thank you for your contribution! :+1: :tada:

**Comment by sangallidavide** [comment]
Dear @dominiksalvet I also have the problem that my Ausu is heating too much and I'd like to control the fans.

```
sudo dmidecode -s system-product-name
VivoBook_ASUSLaptop X580GD_N580GD
```

```
sudo ./src/asus-fan-control -get-temps
55 56 57 58 59 60 61 62
```

I tried to set temperatures with
`sudo ./src/asus-fan-control -set-temps:"40 41 42 43 44 45 46 47"`
which created
`/etc/asus-fan-control/custom-temps`
containing
```
sudo cat /etc/asus-fan-control/custom-temps 
40 41 42 43 44 45 46 47
```
but nothing changed

After that get temps still gives me the same temperatures:
```
sudo ./src/asus-fan-control -get-temps
55 56 57 58 59 60 61 62
```

**Comment by dominiksalvet** [comment]
@sangallidavide Hi! I have some comments to your problem and maybe we can find a solution. But first, please [open a new issue](https://github.com/dominiksalvet/asus-fan-control/issues/new/choose) to keep this issue clean.

---

After creating the appropriate issue, **I will remove** your comment as well as this one, mine.
