### ISSUE TITLE
Issue with GL503VD

### ISSUE THREAD

**Issue by chshbh** [dominiksalvet/asus-fan-control#30]
**Environment**
State asus-fan-control version and OS information.
![image](https://user-images.githubusercontent.com/9166890/77961825-16e84c80-72f8-11ea-8ba2-e8f1f7026f0c.png)
``` ~> uname -a
Linux chshbh 5.5.13-1-MANJARO #1 SMP PREEMPT Wed Mar 25 17:14:28 UTC 2020 x86_64 GNU/Linux
```

**Description**
Describe the bug.
Firstly, this model was not listed but I tried installing it to check if it works with 2 fans. I think my hardware consists of 2 fans but it never shows on sensors report. The one which it shows is always at 0 RPM. I thought this might fix it since service is enabled and its status is succeeded. But, as you can see rpm is still 0. I just wanted to know if this is because of my hardware model.
   
![image](https://user-images.githubusercontent.com/9166890/77961954-4dbe6280-72f8-11ea-8157-522b0ef6b25b.png)
```
itachi@chshbh ~> sensors | grep fan
cpu_fan:        0 RPM
```
Result of  sudo systemctl status asus-fan-control is:
```
● asus-fan-control.service - Fan control for ASUS devices running Linux.
     Loaded: loaded (/usr/lib/systemd/system/asus-fan-control.service; enabled; vendor preset: disabled)
     Active: inactive (dead) since Tue 2020-03-31 02:36:28 IST; 6min ago
   Main PID: 90948 (code=exited, status=0/SUCCESS)

Mar 31 02:36:28 chshbh systemd[1]: Starting Fan control for ASUS devices running Linux....
Mar 31 02:36:28 chshbh systemd[1]: asus-fan-control.service: Succeeded.
Mar 31 02:36:28 chshbh systemd[1]: Started Fan control for ASUS devices running Linux..
```

**Replication**
State steps to replicate the bug.
Installed it on GL503
sudo systemctl enable asus-fan-control
sudo systemctl start asus-fan-control
sudo systemctl status asus-fan-control

**Comment by dominiksalvet** [comment]
Hello @chshbh and welcome to the asus-fan-control community! :wave:

Asus-fan-control has zero correlation with the issue you are describing but your assumption about the hardware model may be right. We, @greifent, @arruor and me, talked about a similar issue in #23 (you can start with [this comment](https://github.com/dominiksalvet/asus-fan-control/issues/23#issuecomment-603695946)). Please, have a look at it. :rocket:

---

And one of the most important questions from my side... does asus-fan-control work on your device? :thinking: :smile:

**Comment by chshbh** [comment]
Thank you, I will look into issue #23. Does it work? I don't think it does because my fan rpm still shows 0, but sytemctl status shows it is running. That is what I was wondering too. I will look into the issue on the weekend and let you know.

**Comment by Greifent** [comment]
Hi, the rpm don't show, idk why. And @dominiksalvet looking inside `systemctl` scrolling down i managed to found the `fancontrol` service but it says ` fancontrol.service        loaded failed     failed    fan speed regulator`

**Comment by dominiksalvet** [comment]
> Thank you, I will look into issue #23. Does it work? I don't think it does because my fan rpm still shows 0, but sytemctl status shows it is running. That is what I was wondering too. I will look into the issue on the weekend and let you know.

@chshbh As I have indicated, **RPM value may not be valid** at all. Do you hear any fan noise difference since asus-fan-control has been installed? If not, please try using various [custom temperatures](https://github.com/dominiksalvet/asus-fan-control#custom-temperatures) whether it helps. :smile: 

---

> Hi, the rpm don't show, idk why. And @dominiksalvet looking inside `systemctl` scrolling down i managed to found the `fancontrol` service but it says ` fancontrol.service loaded failed failed fan speed regulator`

@Greifent Interesting... :thinking: My `systemctl | grep fan` output (beautified a bit):

```
ubuntu-fan.service    loaded active    exited    Ubuntu FAN network setup
```

For some reason, it does not contain asus-fan-control... :smile: BTW, have you tried different solutions before asus-fan-control? It seems like a leftover of a different fan control program to me... :dart: [This](https://wiki.archlinux.org/index.php/Fan_speed_control#Fancontrol_(lm-sensors)) maybe (search for `fancontrol.service` string)?

**Comment by Greifent** [comment]
I have also the ubuntu one, the output is the same.
And i totally forgot about that previous try, it is the one that you found, I'm removing it now

**Comment by Greifent** [comment]
I removed it and I don't have the process running anymore

**Comment by Greifent** [comment]
@dominiksalvet may I suggest that you add in the wiki, since this program is meant for laptops, that if someone does not see improvement, like me, cleaning the laptop is a good idea?

**Comment by dominiksalvet** [comment]
Hello @Greifent and thank you for the suggestion. :+1:  Please, [create a new issue](https://github.com/dominiksalvet/asus-fan-control/issues/new/choose) a let us continue there.

**Comment by dominiksalvet** [comment]
Hi @chshbh, how is this matter going? :thinking:
