### ISSUE TITLE
Add info in the wiki

### ISSUE THREAD

**Issue by Greifent** [dominiksalvet/asus-fan-control#32]
Since the program is meant for laptops, if someone does not see improvement, like me, write in the wiki to clear the laptop fan (see [this post](https://github.com/dominiksalvet/asus-fan-control/issues/30#issuecomment-612590378))

**Comment by dominiksalvet** [comment]
Hello @Greifent and thank you for the suggestion! :+1: 

Unfortunately, I personally do not have time to maintain [asus-fan-control Wiki](https://github.com/dominiksalvet/asus-fan-control/wiki) but I have opened it to the public, so **you can edit it as you wish** and I will take a look at it from time to time. I would really appreciate having an asus-fan-control Wiki powered by the asus-fan-control community - it can bring valuable views to this problematics. :rocket:

I would be really happy if you could initiate this idea. :heart: What do you think? :thinking:

**Comment by Greifent** [comment]
Sure, count on me, I'll add that later.

**Comment by dominiksalvet** [comment]
Thank you so much! :heart: Once you create something, please let me know. :eyes:

**Comment by Greifent** [comment]
I added a few things, take a look and let me now.

**Comment by dominiksalvet** [comment]
Thank you so much @Greifent for your work! :heart: It is just awesome to see people not only using asus-fan-control but also their contributions to asus-fan-control. Keep up the good work if you ever feel the Wiki could be improved! :+1: :rocket: 

---

I have fixed/changed some details in the Wiki. Feel free to take a look at my changes and discuss them if you want. Still, I want to point out something - all bold capital text of disclaimer. I have completely removed it. The reasons are simple:

1. It is scary and discouraging. :fearful: 
2. If you have an untested device, you should proceed as stated in [*readme.md*](https://github.com/dominiksalvet/asus-fan-control/blob/master/readme.md) file and eventually get to [*contributing.md*](https://github.com/dominiksalvet/asus-fan-control/blob/master/contributing.md) file, where a weaker form of the disclaimer is provided.
3. If you have a tested device, you most probably do not want to see that at all.
4. If someone uses bad temperatures (yet valid - positive and non-decreasing), they should expect bad results and no disclaimer is going to prevent that, I think.

> Even in case of bad temperatures, I highly doubt that it can lead to fatal consequences.

**Comment by Greifent** [comment]
Yeah I agree, I was in doubt about that one.

> `sudo asus-fan-control get-temps` : this will show the temperature that are currently selected (those temperature may be different than the default ones if you run the `model-info` command).

Why the `model-info`? I  meant that those temperature may be different from the default ones if you set custom temperatures

**Comment by dominiksalvet** [comment]
Ah... I see... Funny thing is that `model-info` shows the default temperatures of the current device no matter what the current temperatures are set, so I thought it was a mistake. Feel free to change it.

**Comment by Greifent** [comment]
That might be confusing, I'll reformulate that one

**Comment by dominiksalvet** [comment]
Closing this issue as it has been effectively solved but we can continue in the discussion here.

**Comment by dominiksalvet** [comment]
BTW, I cannot believe that cleaning your laptop you have effectively decreased the temperature under load by 20°C. It is unbelievable. It must have been such mess... :smile:

**Comment by Greifent** [comment]
I corrected that one, and also the `set-temps` ones

**Comment by Greifent** [comment]
Yeah, there was a lot of dust in there

**Comment by dominiksalvet** [comment]
Man, the `get-temps` is even more confusing to be honest... :smile: Do you have any other idea? :thinking:

**Comment by Greifent** [comment]
I'll rewrite that tomorrow.

**Comment by dominiksalvet** [comment]
Great, thank you! :wave:

**Comment by Greifent** [comment]
I rewrote that, hope that now it is less confusing.

**Comment by dominiksalvet** [comment]
Great, good job! :smile:

**Comment by Greifent** [comment]
Thanks, I'll add something in the future maybe

**Comment by Greifent** [comment]
One question: once you have modified the temperatures, it is required the reboot?

**Comment by dominiksalvet** [comment]
No, the effect is instantaneous and persists after reboot.

**Comment by Greifent** [comment]
Oh, thanks; should I add that on to the wiki?

**Comment by dominiksalvet** [comment]
It is up to you - the wiki is community-driven and you have done a great job on making this idea a reality. :rocket: :clap: My humble opinion is that **it might be useful have it** there.

I want to intrude only in case I will strongly disagree with something but even in that case I am open to a discussion. :speech_balloon:

**Comment by Greifent** [comment]
Ok, thanks

**Comment by Greifent** [comment]
Hi, I was thinking: it might be possible for this program to have a GUI to set temperatures, see model info, etc?
If yes, I would like to try and do it, just to improve my knowledge.
Let me know if you are already working on it.

**Comment by dominiksalvet** [comment]
Hey @Greifent! Glad to hear that! :rocket: 

Nope, I am not working on a GUI for asus-fan-control. Please, [create a new issue](https://github.com/dominiksalvet/asus-fan-control/issues/new/choose) and we can discuss it there. :+1:
