### ISSUE TITLE
Add support for Asus Rog Strix15 GL503GE

### ISSUE THREAD

**Issue by sniper7398** [dominiksalvet/asus-fan-control#34]
**Environment**
State asus-fan-control version and OS information. - 3.6.0(install via gitpack) and Ubuntu 19.10.

**Basic configuration**
If only temperatures were configured, add output of:
* `sudo asus-fan-control get-temps`
Above code give following error- `/usr/local/bin/asus-fan-control: 400: Illegal number: Erro`

* `sudo asus-fan-control model-info`
above code give following msg- 
`name Strix15GL503GE`
`address 1335`
`temperatures 55 60 62 65 68 72 76 80`
`tested false`

**Advanced configuration** --(Not used any Advanced configuration)

**Additional context**
Also, additionally I tried fancontrol + lm-sensors but they too won't works.
Also, my temps are low but only fans are running continously, see [images](https://paste.pics/e3f736476abb4ae7a9d39216ee3fa882)

**Comment by dominiksalvet** [comment]
Welcome to the asus-fan-control community, @sniper7398! :wave: :smile: 

It seems that there is a problem with performing the required ACPI call to get fan temperatures. Let us run the target ACPI call manually as a root user (e.g., use `su` or `sudo -i` before proceeding further). Once you have root permissions, what is the output of the following command (include curly brackets)?

```sh
{ echo '\_SB.PCI0.LPCB.EC0.RRAM 1335' > /proc/acpi/call &&
  cat /proc/acpi/call # usually there is no newline in the output
  printf '\n%s\n' "$?"; } # hence we are using printf to make output clean
```

The output of above code on my system:

```
0x37alled
0
```

0x37 is equal to 55 in decimal, [which is](https://github.com/dominiksalvet/asus-fan-control/blob/master/data/models) the first temperature of my UX430UA device.

**Comment by sniper7398** [comment]
Hey, I have tried your command(without curly bracket and without curly bracket) as root user and I am getting below error-
`Error: AE_NOT_FOUND`
Also, I have google to first figure out on my own, but all have posted this error on OS installation.

Have a look at the [image of terminal](https://paste.pics/92b76a74ddc70e258ddf379d9fd1c1f0) for more info.

**Comment by dominiksalvet** [comment]
Well, that is noticeably similar to [this afc-scout issue](https://github.com/dominiksalvet/afc-scout/issues/1). And in fact, unfortunately, my answer is also the same as in [this post](https://github.com/dominiksalvet/afc-scout/issues/1#issuecomment-612394125). :disappointed: Feel free to read the whole issue and try [afc-scout](https://github.com/dominiksalvet/afc-scout) as well but I expect the same results as the OP of the issue.

Have you tried it and what do you think? :thinking:
