### ISSUE TITLE
Add support for B9450

### ISSUE THREAD

**Issue by Esfo** [dominiksalvet/asus-fan-control#36]
**Environment**
asus-fan-control 3.6.0-1
System: Arch 5.6.6

**Basic configuration**
If only temperatures were configured, add output of:
* `sudo asus-fan-control get-temps`
```
55 56 57 58 59 60 61 62
```
I have no idea what configuring temperatures means in this context, but these look not-legit if I had to guess.

* `sudo asus-fan-control model-info`
```
name ASUSEXPERTBOOKB9450FAB9450FA
address 1335
temperatures 55 60 62 65 68 72 76 80
tested false
```
**Additional context**
I've not had any luck using lm_sensors to get these to turn on. When I first installed the OS I was able to hear the fans turn on for brief moments. I'd not done anything computationally extensive enough until recently to notice they don't turn on at all after adding a few power configurations. Contemplating a reinstall to see if they turn on by themselves again or if I mis-heard it. Hopefully you can help!

Let me know if you have any questions/requests.

**Comment by dominiksalvet** [comment]
Hello @Esfo and welcome to the asus-fan-control community! :wave: 

> I have no idea what configuring temperatures means in this context, but these look not-legit if I had to guess.

Asus-fan-control would not allow you to use illegal temperatures, so they certainly are legal. However, as you suspect, some temperatures are better than others. For their meaning, please take a look at [Custom temperatures](https://github.com/dominiksalvet/asus-fan-control/blob/master/readme.md#custom-temperatures).

I think that using temperatures with one step difference is unfounded. After taking a look at the temperatures meaning, please think again about their values.

In case you insist on your temperatures, take a look at #3 and #29. In that case, I would also be for at least two step difference.

Let me know! :rocket:

**Comment by Esfo** [comment]
Thanks @dominiksalvet !

So the temperature output of model-info seems to be standard, and not machine-specific then, I didn't realize this. I have no strong attachment to the output of get-temperatures.

Personally, I plan to use something like: 40 44 48 52 54 56 60 64.
My reasoning is this laptop has a crazy strong battery, and keeping it from getting hot will preserve it's charge capacity in the long-term.

But I don't know if these would be good general use levels based on what the processors can handle, and spinning the fan pre-emptively at lower temperatures would drain existing battery life.

If I had to suggest something for general use I can come up with estimates based on what I see.

The output from get-temps implies a happy machine up to about ~55 degrees. The command below implies the lowest maximum happy temperature of ~80, with everything showing maxes or critical values at 100C.

Given this, I would aim for the highest fan setting to kick in ~5 degrees before 80C is reached and map ~linearly from 49-72C.

Giving: 49 52 56 59 62 65 69 72

I think using conservative estimates at ~6-8C below the values I'm inferring from the readout would be a decent safety-net for making sure people don't overheat their hardware. This has enough cpu cores to make pretty fast temperature jumps.

output of sensors -u from lm_sensors below is where I get the maxes from.

```
iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:
  temp1_input: 30.000

asus-isa-0000
Adapter: ISA adapter
cpu_fan:
  fan1_input: 0.000

nvme-pci-6d00
Adapter: PCI adapter
Composite:
  temp1_input: 16.850
  temp1_max: 80.850
  temp1_min: -273.150
  temp1_crit: 81.850
  temp1_alarm: 0.000
Sensor 1:
  temp2_input: 16.850
  temp2_max: 65261.850
  temp2_min: -273.150
Sensor 2:
  temp3_input: 22.850
  temp3_max: 65261.850
  temp3_min: -273.150

acpitz-acpi-0
Adapter: ACPI interface
temp1:
  temp1_input: 25.000
  temp1_crit: 103.000

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:
  temp1_input: 25.000
  temp1_max: 100.000
  temp1_crit: 100.000
  temp1_crit_alarm: 0.000
Core 0:
  temp2_input: 24.000
  temp2_max: 100.000
  temp2_crit: 100.000
  temp2_crit_alarm: 0.000
Core 1:
  temp3_input: 23.000
  temp3_max: 100.000
  temp3_crit: 100.000
  temp3_crit_alarm: 0.000
Core 2:
  temp4_input: 24.000
  temp4_max: 100.000
  temp4_crit: 100.000
  temp4_crit_alarm: 0.000
Core 3:
  temp5_input: 24.000
  temp5_max: 100.000
  temp5_crit: 100.000
  temp5_crit_alarm: 0.000

BAT0-acpi-0
Adapter: ACPI interface
in0:
  in0_input: 15.677

nvme-pci-6c00
Adapter: PCI adapter
Composite:
  temp1_input: 22.850
  temp1_max: 80.850
  temp1_min: -273.150
  temp1_crit: 81.850
  temp1_alarm: 0.000
Sensor 1:
  temp2_input: 22.850
  temp2_max: 65261.850
  temp2_min: -273.150
Sensor 2:
  temp3_input: 21.850
  temp3_max: 65261.850
temp3_min: -273.150
```

**Comment by dominiksalvet** [comment]
So which ones do you want to be declared default temperatures for your laptop model? :smile: The second ones - `49 52 56 59 62 65 69 72`? Everyone can always use their custom temperatures, default temperatures should be something like best fit among them.

BTW, the `model-info` command shows the default temperatures of your model and since your model is not tested yet, it uses the default temperatures of my laptop model; UX430UA. Once we add your model to asus-fan-control, you will see the here-suggested temperatures in `model-info` on your system no matter which temperatures you will have chosen using `set-temps`.

> Did you know that `set-temps` may accept `default` as an argument? That is when the default temperatures are actually applied. This and much more you can find on [our Wiki](https://github.com/dominiksalvet/asus-fan-control/wiki). :book:

**Comment by Esfo** [comment]
I'm honored that you're giving me the choice of the defaults! I feel like I'm responsible for more than I'm worth. Let the choice be my second one, ```49 52 56 59 62 65 69 72```, with my limited understanding it seems like it should be a safe bet.

Also, does this process of yours have anything to do with getting the fans to work? If not I have to experiment or find ways of getting them to turn on via controls.

**Comment by dominiksalvet** [comment]
Wait a sec, your fans are not working? 😃 Did you read the [*contributing.md*](https://github.com/dominiksalvet/asus-fan-control/blob/master/contributing.md) file before creating this issue? 🤔

I am really happy that you want to contribute to asus-fan-control. ❤️ But I cannot add your laptop as tested before being actually tested. Once asus-fan-control controls your fan speed with `set-temps`, then I can add it as tested. Why? Because not every ASUS device works with asus-fan-control.

So please, let me know once you observe that changing temperatures using `set-temps` has an effect to your device fans - your device does not need to be included in asus-fan-control to do so. Does it make sense? 😉

> Maybe you can take a look at [afc-scout](https://github.com/dominiksalvet/afc-scout) and try to inspect ACPI values manually.

**Comment by dominiksalvet** [comment]
Closing as explained in [this afc-scout issue](https://github.com/dominiksalvet/afc-scout/issues/2).

**Comment by dominiksalvet** [comment]
> I'd not done anything computationally extensive enough until recently to notice they don't turn on at all after adding a few power configurations. Contemplating a reinstall to see if they turn on by themselves again or if I mis-heard it.

BTW, I would be 100% for reinstalling the whole system because your ACPI dump [looked really weird](https://github.com/dominiksalvet/afc-scout/issues/2#issuecomment-619664723). That gets me to the idea that afc-scout/asus-fan-control may work after the reinstall. It would be great to try it (start with afc-scout) again and let me know in case something changes. Good luck! :crossed_fingers:

**Comment by dominiksalvet** [comment]
I have decided that I will leave this (and [associated](https://github.com/dominiksalvet/afc-scout/issues/2)) issue opened until you reinstall your system if you are still considering it. Then you will be able to confirm whether it works or not. It would be interesting to see [this graph](https://github.com/dominiksalvet/afc-scout/issues/2#issuecomment-619664723) after the reinstall again.

**Comment by dominiksalvet** [comment]
Hello @Esfo, any updates on this and https://github.com/dominiksalvet/afc-scout/issues/2? :thinking: Have you find any alternative for your device (if you still have it) that works? If so, please share it with us. :rocket: Hope you are doing fine these days!

**Comment by Esfo** [comment]
Hey @dominiksalvet, no real progress here. Other than being able to manually turn the fan to a single, unmodifiable, ~static speed through a binary switch, I've not gained any better control of this fan through automated means.

**Comment by dominiksalvet** [comment]
Oh, I am sorry to hear that... :disappointed: Should you find something that works for you, please let us know. :rocket:
