### ISSUE TITLE
Add support for asus tuf fx505

### ISSUE THREAD

**Issue by r-ush** [dominiksalvet/asus-fan-control#39]
**Environment**
State asus-fan-control version and OS information. pop os

**Basic configuration**
If only temperatures were configured, add output of:
* `sudo asus-fan-control get-temps`
* `sudo asus-fan-control model-info`

**Advanced configuration**
If advanced configuration was used, add output of:
* `sudo FALLBACK_ADDR=<addr> FALLBACK_TEMPS='<temps>' asus-fan-control model-info`

**Additional context**
Add any additional context.

**Comment by dominiksalvet** [comment]
Welcome to the asus-fan-control community! 😊

Your original post needs significant modifications. You need to replace the command fields with actual output of these commands on your system. And choose only one configuration category. Feel free to get inspired from [other issues](https://github.com/dominiksalvet/asus-fan-control/issues).

 Please add missing information and then we can examine this issue further.

---

Maybe @AnasR7 can add something to this as this user seems to have the same laptop model (see #35).

**Comment by Rakesh-rules** [comment]
I would like to continue this issue. I have an Asus tuf fx505GM. It is a dual fan system. I have done 'sudo afc-scout 1334 1343' and output as follows:

[1334] = 102
[1335] = 55
[1336] = 60
[1337] = 62
[1338] = 65
[1339] = 68
[1340] = 72
[1341] = 76
[1342] = 80
[1343] = 105

**Comment by Rakesh-rules** [comment]
> I would like to continue this issue. I have an Asus tuf fx505GM. It is a dual fan system. 

lm-senor readings :

```
iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +38.0°C  

asus-isa-0000
Adapter: ISA adapter
cpu_fan:        0 RPM

BAT0-acpi-0
Adapter: ACPI interface
in0:          11.93 V  
curr1:       560.00 mA 

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +44.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +42.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +44.0°C  (high = +100.0°C, crit = +100.0°C)
Core 2:        +44.0°C  (high = +100.0°C, crit = +100.0°C)
Core 3:        +42.0°C  (high = +100.0°C, crit = +100.0°C)

pch_cannonlake-virtual-0
Adapter: Virtual device
temp1:        +48.0°C  

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +44.0°C  (crit = +98.0°C)
temp2:        +27.8°C  (crit = +119.0°C)
```

**Comment by dominiksalvet** [comment]
@Rakesh-rules Hello! :wave: Since there are signs of temperatures in your afc-scout output, does asus-fan-control work for your device (at least for one fan)? Based on #38, what is your output for `sudo afc-scout 1430 1439`? The second fan address range may be present here.

**Comment by Rakesh-rules** [comment]
Hii @dominiksalvet , thanks for your swift reply ! I am not sure how to check whether Asus-fan-control works properly, I am not getting my fan speed in sensors. My output for 
>sudo afc-scout 1430 1439 
is 

`
[1430] = 0
[1431] = 46
[1432] = 54
[1433] = 62
[1434] = 62
[1435] = 62
[1436] = 62
[1437] = 62
[1438] = 62
[1439] = 105
`

further I checked output for 
> sudo asus-fan-control get-temps

`45 50 55 60 65 70 75 80`

and also for 
> sudo asus-fan-control model-info

`
name TUFGamingFX505GMFX505GM
addresses 1335
temperatures 55 60 62 65 68 72 76 80
tested false
`

Hope, this is okay 😁

**Comment by dominiksalvet** [comment]
> I am not sure how to check whether Asus-fan-control works properly, I am not getting my fan speed in sensors.

Some sensors might be completely independent of asus-fan-control. RPM one does not even work at all for some laptops (mine included). Try two very different temperatures setups as described on [our wiki](https://github.com/dominiksalvet/asus-fan-control/wiki) in the Troubleshooting section and you should hear the difference.

> My output for `sudo afc-scout 1430 1439` is

Yeah, that might be the second fan temperatures. Once it works as described above, you may try it with the second fan used as well. You will need to use the following command to apply temperatures:

```
sudo FALLBACK_ADDRS='1335 1431' FALLBACK_TEMPS='<temps>' asus-fan-control set-temps default
```

instead of

```
sudo asus-fan-conrol set-temps <temps>
```

> **Make sure you have the latest asus-fan-control** installed before doing the above. Use `sudo gitpack install github.com/dominiksalvet/asus-fan-control` to check and update.

---

> further I checked output for `sudo asus-fan-control get-temps`
> and also for `sudo asus-fan-control model-info`
> Hope, this is okay

Thanks! That will be very useful once it works on your device and we are on the point of adding support for your device. Do not worry -- once support is added for your device, you will simply use a standard asus-fan-control API without any `FALLBACK` variables whatsoever. :smile:

**Comment by Rakesh-rules** [comment]
I tested both fans separately with GPU, CPU workloads.

> For CPU fan : 
```
sudo asus-fan-control set-temps 30 35 40 45 50 55 60 65
sudo asus-fan-control set-temps 60 65 70 75 80 85 90 95
```

> For GPU fan :
```
sudo FALLBACK_ADDRS='1335 1431' FALLBACK_TEMPS='30 35 40 45 50 55 60 65' asus-fan-control set-temps default
sudo FALLBACK_ADDRS='1335 1431' FALLBACK_TEMPS='60 65 70 75 80 85 90 95' asus-fan-control set-temps default
```

I used different sets of temperatures as mentioned and it's working.

> Thanks! That will be very useful once it works on your device and we are on the point of adding support for your device. Do not worry -- once support is added for your device, you will simply use a standard asus-fan-control API without any FALLBACK variables whatsoever. smile

Excited for this one. Thanks a lot.🤓🙌

**Comment by dominiksalvet** [comment]
@Rakesh-rules The support for your model has been added in [3.8.0 version](https://github.com/dominiksalvet/asus-fan-control/releases/tag/3.8.0). Update as described in readme file and you will be able to use it normally, without any `FALLBACK` variables.

Thank you for your contribution! :heart: :rocket: Should you have any problems, feel free to continue in the discussion.

---

BTW, `sudo FALLBACK_ADDRS='1335 1431' FALLBACK_TEMPS='<temps>' asus-fan-control set-temps default` controlled both fans, not the GPU one.

@r-ush Closing as solved. If it does not work for you, leave me a message here and I will reopen the issue.

**Comment by Rakesh-rules** [comment]
Thanks a lot @dominiksalvet . 😌

> BTW, sudo FALLBACK_ADDRS='1335 1431' FALLBACK_TEMPS='<temps>' asus-fan-control set-temps default controlled both fans, not the GPU one.

yes, it controlled both the fans. I mentioned it as I changed only the FALLBACK_TEMPS. 

Thanks for this project. Good work.👏

**Comment by AnasR7** [comment]
can i opened  new issues here ?

> @Rakesh-rules The support for your model has been added in [3.8.0 version](https://github.com/dominiksalvet/asus-fan-control/releases/tag/3.8.0). Update as described in readme file and you will be able to use it normally, without any `FALLBACK` variables.
> 
> Thank you for your contribution!   Should you have any problems, feel free to continue in the discussion.
> 
> BTW, `sudo FALLBACK_ADDRS='1335 1431' FALLBACK_TEMPS='<temps>' asus-fan-control set-temps default` controlled both fans, not the GPU one.
> 
> @r-ush Closing as solved. If it does not work for you, leave me a message here and I will reopen the issue. There are multiple FX505 models.

hello sorry, lately I'm very busy with campus activities. and didn't have time to adjust my laptop settings. here the result after installation with gitpack in ASUS TUF FX505DY and installation is success with state is anable but my vendor present is disable.

```
sudo systemctl status asus-fan-control.service                                                                                                                                 ✘ 130 
● asus-fan-control.service - Fan control for ASUS devices running Linux.
     Loaded: loaded (/etc/systemd/system/asus-fan-control.service; enabled; vendor preset: disabled)
     Active: inactive (dead) since Sat 2020-05-16 13:00:54 WIB; 8min ago
    Process: 5372 ExecStartPre=/sbin/modprobe acpi_call (code=exited, status=0/SUCCESS)
    Process: 5373 ExecStart=/usr/local/bin/asus-fan-control (code=exited, status=0/SUCCESS)
   Main PID: 5373 (code=exited, status=0/SUCCESS)

Mei 16 13:00:54 incubieos-pc systemd[1]: Starting Fan control for ASUS devices running Linux....
Mei 16 13:00:54 incubieos-pc systemd[1]: asus-fan-control.service: Succeeded.
Mei 16 13:00:54 incubieos-pc systemd[1]: Finished Fan control for ASUS devices running Linux..
```

when I check with systemctl list
```
systemctl list-unit-files                                                                                                                                                      ✘ 130 
UNIT FILE                                  STATE           VENDOR PRESET
proc-sys-fs-binfmt_misc.automount          static          disabled     
-.mount                                    generated       disabled     
boot-efi.mount                             generated       disabled     
dev-hugepages.mount                        static          disabled     
dev-mqueue.mount                           static          disabled     
etc-pacman.d-gnupg.mount                   static          disabled     
proc-fs-nfsd.mount                         static          disabled     
proc-sys-fs-binfmt_misc.mount              disabled        disabled     
sys-fs-fuse-connections.mount              static          disabled     
sys-kernel-config.mount                    static          disabled     
sys-kernel-debug.mount                     static          disabled     
sys-kernel-tracing.mount                   static          disabled     
tmp.mount                                  static          disabled     
var-lib-machines.mount                     static          disabled     
var-lib-nfs-rpc_pipefs.mount               static          disabled     
systemd-ask-password-console.path          static          disabled     
sys-kernel-config.mount                    static          disabled     
sys-kernel-debug.mount                     static          disabled     
sys-kernel-tracing.mount                   static          disabled     
tmp.mount                                  static          disabled     
var-lib-machines.mount                     static          disabled     
var-lib-nfs-rpc_pipefs.mount               static          disabled     
systemd-ask-password-console.path          static          disabled     
systemd-ask-password-wall.path             static          disabled     
session-2.scope                            transient       disabled     
accounts-daemon.service                    disabled        disabled     
acpid.service                              disabled        disabled     
alsa-restore.service                       static          disabled     
alsa-state.service                         static          disabled     
--> asus-fan-control.service                   enabled         disabled <--     
auditd.service                             disabled        disabled     
auth-rpcgss-module.service                 static          disabled     
autovt@.service                            enabled         disabled     
avahi-daemon.service                       enabled         disabled     
avahi-dnsconfd.service                     disabled        disabled     
blk-availability.service                   disabled        disabled     
bluetooth-mesh.service                     disabled        disabled     

```
its like is not running in my system.

thanks.

**Comment by dominiksalvet** [comment]
@AnasR7 As far as I understand your problem it is unrelated to this very issue. So please create a new one and include more information in the new issue as well, such as:

1. How did you install asus-fan-control? GitPack or AUR?
2. Your asus-fan-control version.
3. Your OS and version.
4. Does it work on your system? See [our wiki](https://github.com/dominiksalvet/asus-fan-control/wiki) (Troubleshooting section) if you do not know.

**Comment by mthw0** [comment]
Hi, I have Asus TUF FX505DY and I have been trying to get this working but I wasn't able to.
I have tried finding the right adresses with afc-scout but I haven't found anything, only zeros between adresses 0 and 5000. Is there something I can try, or do you have any advice? Am I doing something wrong?

**Comment by dominiksalvet** [comment]
Hello @mthw0, your model is different from the tested one. You have FX505DY and the tested one is FX505GM - I will rename this issue to stop confusing people... :smiley: :+1: 

> I have tried finding the right adresses with afc-scout but I haven't found anything, only zeros between adresses 0 and 5000. Is there something I can try, or do you have any advice? Am I doing something wrong?

This looks like one of signs that asus-fan-control is not working on the device as per its current state. However, feel free to create a new issue and we can discuss it there in more detail and come to a conclusion. :rocket:
