### ISSUE TITLE
Support for Windows devices is possible?

### ISSUE THREAD

**Issue by RYSKZ** [dominiksalvet/asus-fan-control#40]
Hi, I really appreciate the effort you put in developing this program. I wanted to know if support for Windows devices is possible, and if it is,  I will be pleased if it is implemented eventually.

Thank you.

**Comment by dominiksalvet** [comment]
Hello @RYSKZ and welcome to the asus-fan-control community! :wave:

Unfortunately, the support for Windows is not going to happen. At least not from my side -- I am sorry. The major reason for this is that I do not use Windows. But if anyone is interested, feel free to do so. :rocket:

**Comment by RYSKZ** [comment]
Okay, I totally understand that.

Thanks anyway.
