### ISSUE TITLE
file /proc/acpi/call does not exist

### ISSUE THREAD

**Issue by Greifent** [dominiksalvet/asus-fan-control#42]
Hi, i recently updated to Pop_OS! 20.04, and while trying to working on the GUI, i noticed that it can't found that file, I have already reinstalled asus-fan-control using gitpack but nothing. What can be the issue?

**Comment by Greifent** [comment]
Never mind, the update somehow broke the gitpack installation, now it work.

**Comment by Greifent** [comment]
Reinstalled gitpack, now i don't have the message during the installation of asus-fan-control, but when i run `sudo asus-fan-control model-info` i have as only output: `file /proc/acpi/call does not exist`

**Comment by dominiksalvet** [comment]
Hi @Greifent! Please try rebooting your system first. If that does not help, it might be caused by the asus-fan-control service, which does not get loaded or is failing for some reason.

Run `sudo systemctl start asus-fan-control.service` and try again. If that does not help, run `sudo modprobe acpi_call` and try again -- now it should work, hopefully.

If there are any error outputs, please include them in the next post. Nevertheless, we need to find out why the error occurs in the first place.

**Comment by Greifent** [comment]
Thanks, I'll try and let you know

**Comment by Greifent** [comment]
I think I understood the problem, i had recently done a kernel update, and it can't found that module in the kernel. Anyway the `sudo modprobe acpi_call` output is: `modprobe: FATAL: Module acpi_call not found in directory /lib/modules/5.6.11-050611-generic`

**Comment by Greifent** [comment]
I reverted to the version of the kernel 5.4.0. When I try to install `acpi-call` I see: ``Note, selecting 'acpi-call-dkms' instead of 'acpi-call'
acpi-call-dkms is already the newest version (1.1.0-5).
``

**Comment by dominiksalvet** [comment]
Hmmm... does `sudo depmod` make the difference? :thinking:

**Comment by Greifent** [comment]
Run `sudo depmod`, no outpu, run `sudo modprobe acpi_call`, same output as before

**Comment by dominiksalvet** [comment]
Well then... try reinstall the `acpi-call-dkms` package. If that does not help... do you use secure boot on your device? :thinking: I think it was mentioned somewhere in the issues and it causes problems with loading kernel modules. I could not find the issue, though.

**Comment by Greifent** [comment]
Yesssss, it work, i purged that package, rebooted, reinstalled, rebooted and it work. Thanks for the help!

**Comment by dominiksalvet** [comment]
Great! Glad to be of help. :smile: :rocket:
