### ISSUE TITLE
G752VL: change default temperature set

### ISSUE THREAD

**Issue by icegood** [dominiksalvet/asus-fan-control#43]
**Environment**
asus-fan-control 3.8.0
Fan control for ASUS devices running Linux.

Copyright 2017-2020 Dominik Salvet
github.com/dominiksalvet/asus-fan-control

**Description**
It seems when I first tried the program, I did wrong thing. I applied set-temps before I got get-temps. At that moment program seems didn't work correctly for my laptop. For now, I could obtain the next values if i not start service after reboot:
 
afc-scout
```

------ base address 1335 ------
[1334] = 0
[1335] = 49 <- possible start
[1336] = 58
[1337] = 66
[1338] = 72
[1339] = 78
[1340] = 86
[1341] = 94
[1342] = 97 <- possible end
[1343] = 98
------ base address 1431 ------
[1430] = 0
[1431] = 46 <- possible start
[1432] = 53
[1433] = 58
[1434] = 65
[1435] = 75
[1436] = 79
[1437] = 81
[1438] = 83 <- possible end
[1439] = 93

```
and i'm not sure what temperature set should be applied in this case.

Also, 
afc-scout 1335 1350
```

[1335] = 49
[1336] = 58
[1337] = 66
[1338] = 72
[1339] = 78
[1340] = 86
[1341] = 94
[1342] = 97
[1343] = 98
[1344] = 3
[1345] = 3
[1346] = 3
[1347] = 3
[1348] = 3
[1349] = 3
[1350] = 3
```
root@ice-ubuntu:/home/ice# afc-scout 1431 1445
```

[1431] = 46
[1432] = 53
[1433] = 58
[1434] = 65
[1435] = 75
[1436] = 79
[1437] = 81
[1438] = 83
[1439] = 93
[1440] = 4
[1441] = 3
[1442] = 3
[1443] = 5
[1444] = 4
[1445] = 3

```
seems acpi has 9 presets instead of 8.

**Additional context**
#7

**Comment by dominiksalvet** [comment]
Hello @icegood! Glad to hear from you. :wave: 

I assume that your laptop has two fans. Feel free to play with the following command and it's variants:

```
sudo FALLBACK_ADDRS='1335 1431' FALLBACK_TEMPS='<9-temps>' asus-fan-control set-temps default
```

Try some low temperatures and some high ones in place of `<9-temps>`... Does it do something? Can you say that it affects both fans? 🤔

**Comment by dominiksalvet** [comment]
BTW, before running the command above, first remove the line with your laptop model from the */usr/share/asus-fan-control/models* file.

**Comment by icegood** [comment]
Hi, @dominiksalvet .
Sorry for the delay. Seems temperatures above are from my range. However, I'm trying to resolve a bit of another issue. From some moment my both fans work at max. Files from 
/sys/devices/platform/asus-nb-wmi/hwmon/hwmon5/power became useless.

 And I could confirm that afilipovich  was right regarding purpose of memories:
0x0521 and 0x0522
how he has described at 
https://github.com/daringer/asus-fan/issues/44#issuecomment-304731915
A bit amendment: values should be or-ed to 0x40 to set max mode and and-ed with 0xBF to remove it. 
I have these values as :
`8D 9B`
in normal mode and
`CD DB`
in maximal one.

I tried it
https://github.com/icegood/fan_restore_to_manual
but have no luck. Seems my DSDT does destructive action for me. In particular, I found in [my DSDT.dsl](https://github.com/icegood/my_dsdts/blob/master/DSDT.dsl):

```

If (LEqual (IIA0, 0x00110013))
                    {
                        Store (^^PCI0.LPCB.EC0.RRAM (0x0521), Local0)
                        If (LEqual (IIA1, Zero))
                        {
                            And (Local0, 0xFFFFFFFFFFFFFFBF, Local1)
                        }
                        ElseIf (LEqual (IIA1, One))
                        {
                            Or (Local0, 0x40, Local1)
                        }

                        ^^PCI0.LPCB.EC0.WRAM (0x0521, Local1)
                        Return (One)
                    }

                    If (LEqual (IIA0, 0x00110014))
                    {
                        Store (^^PCI0.LPCB.EC0.RRAM (0x0520), Local0)
                        If (And (Local0, 0x02))
                        {
                            Store (^^PCI0.LPCB.EC0.RRAM (0x0522), Local0)
                            If (LEqual (IIA1, Zero))
                            {
                                And (Local0, 0xFFFFFFFFFFFFFFBF, Local1)
                            }
                            ElseIf (LEqual (IIA1, One))
                            {
                                Or (Local0, 0x40, Local1)
                            }

                            ^^PCI0.LPCB.EC0.WRAM (0x0522, Local1)
                            Return (One)
                        }

                        Return (Zero)
                    }
```
and i wonder what IIA0 and IIA1 mean....

**Comment by dominiksalvet** [comment]
Sorry @icegood, but the above is completely out of my scope... Unfortunately, I cannot help you with that very much.

Nevertheless, I am thinking about something. As long as I know, ACPI values should be reset on each boot (at least in asus-fan-control scope), so if there is something wrong with your laptop, it is probably caused on each boot. I would personally start with uninstalling asus-fan-control. If it does not help, try to think about other programs/scripts you could have on your system that may use ACPI calls. As a definitive solution (hopefully) I would consider reinstalling the whole system, or at least try to boot from a "Live CD" linux to see if the issue occurs here as well...

And what about the number of temperatures and two base fan addresses for your laptop model? Considering your current state, are you able to state where it works/worked or not? :thinking:

**Comment by icegood** [comment]
yeah, i see. And i know that fan-control does nothing with that, so no need to remove. For this moment i removed asus-nb-wmi, it might be a reason.  
No, for this moment the only remedy is to reboot with shutdown. Even removing kernel modules at runtime with running of my script doesn't work.

**Comment by icegood** [comment]
this issue could be closed, since temperatures are checked properly. BTW, 2nd temperature set is valid as well, since my laptop should have two fans (personally i don't feel 2nd....). And ACPI software support checking for two fans as well. As you can see from snippet above, they checked 2nd bit from 0x520 to get know, whether fan is actually installed and in my case value is 0x97 always => 2nd fan should be adjusted.

**Comment by dominiksalvet** [comment]
> And ACPI software support checking for two fans as well. As you can see from snippet above, they checked 2nd bit from 0x520 to get know, whether fan is actually installed and in my case value is 0x97 always => 2nd fan should be adjusted.

Very good observation! :rocket: :+1: 

> this issue could be closed, since temperatures are checked properly. BTW, 2nd temperature set is valid as well, since my laptop should have two fans (personally i don't feel 2nd....).

Ok, so instead of `G752VL|1335|45 50 55 60 65 70 75 80` record in *data/models*, there will something like `G752VL|1335 1431|a b c d e f g h i` based on the set temperatures using the approach described in [the posts above](https://github.com/dominiksalvet/asus-fan-control/issues/43#issuecomment-633431845). So what are your new recommended 9 temperatures to be used as the default temperatures for all asus-fan-control users with the same laptop model?

**Comment by icegood** [comment]
Personally, i would leave them as default:
[1335] = 49
[1336] = 58
[1337] = 66
[1338] = 72
[1339] = 78
[1340] = 86
[1341] = 94
[1342] = 97
[1343] = 98

and 

[1431] = 46
[1432] = 53
[1433] = 58
[1434] = 65
[1435] = 75
[1436] = 79
[1437] = 81
[1438] = 83
[1439] = 93

at least I don't have issues with noisy fans at low temperatures unless the maximal mode is not activated. Moreover, sometimes I feel that nb is overheating a bit at 'normal' mode. But maybe I just biased because of working at maximal mode due to my bug that i fight with.

**Comment by dominiksalvet** [comment]
Well there is a technical limitation. The temperatures for multiple addresses must be the same. So what do you think about using something more similar to the current asus-fan-control default ones - `45 50 55 60 65 70 75 80 85`? Try them and let me know whether it is better.

**Comment by dominiksalvet** [comment]
Hello, any updates on this?
