### ISSUE TITLE
Cannot set temps for Zenbook UX480F

### ISSUE THREAD

**Issue by TeoConan** [dominiksalvet/asus-fan-control#44]
**Environment**
Ubuntu 20
```
$ asus-fan-control model-info
name ZenBookUX450FDXUX480FD
addresses 1335
temperatures 55 60 62 65 68 72 76 80
tested false
```

**Description**
I cannot set temps, here my terminal :
```
$ sudo asus-fan-control set-temps 40 42 45 48 50 52 55 58
$ sudo asus-fan-control get-temps 
55 56 57 58 59 60 61 62
$ sudo asus-fan-control set-temps 45 50 55 60 65 70 75 80
$ sudo asus-fan-control get-temps 
55 56 57 58 59 60 61 62
```

**Additional context**
I don't know if I misunderstood something... But temps don't want to change on my laptop
If you need additional info ask me ! I'll answer you quick as possible :)

**Comment by dominiksalvet** [comment]
Hello @TeoConan and welcome to the asus-fan-control community! :wave:

This is a known symptom of not yet working models... Please see #4, #5 and #6 issues. You need to find your ACPI fan base as it seems it is different or maybe incompatible at all based on your values. Try afc-scout as mentioned in the contributing file.

Let us know! :+1:
