### ISSUE TITLE
support for VivoBookASUSLaptopX409FAX409FA

### ISSUE THREAD

**Issue by milangm89** [dominiksalvet/asus-fan-control#45]
**Description**
I tried adding this tool but i could see that the service is not in running status.

**Reason**
this feature will improve the battery life in linux

**Additional context**
logs:
++++++
➜  ~ sudo systemctl status asus-fan-control 
● asus-fan-control.service - Fan control for ASUS devices running Linux.
     Loaded: loaded (/etc/systemd/system/asus-fan-control.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Tue 2020-06-02 12:24:31 IST; 22min ago
    Process: 71355 ExecStartPre=/sbin/modprobe acpi_call (code=exited, status=0/SUCCESS)
    Process: 71362 ExecStart=/usr/local/bin/asus-fan-control (code=exited, status=0/SUCCESS)
   Main PID: 71362 (code=exited, status=0/SUCCESS)

Jun 02 12:24:31 milans-vivobook systemd[1]: Starting Fan control for ASUS devices running Linux....
Jun 02 12:24:31 milans-vivobook systemd[1]: asus-fan-control.service: Succeeded.
Jun 02 12:24:31 milans-vivobook systemd[1]: Finished Fan control for ASUS devices running Linux..
++++++

it starts the command and exiting.
How it will work if it is not running it as a service?

**Comment by dominiksalvet** [comment]
Hello @milangm89 and welcome to the asus-fan-control community! :wave: :smile:

> How it will work if it is not running it as a service?

This questions has already been answered in #22. Please take a look at it since I do not want to repeat myself. :rocket: 

---

And the most important question from my side. **Does asus-fan-control work** on your device? :thinking:

**Comment by dominiksalvet** [comment]
Hello again, I am really interested in whether AFC works for your device. Please, can we have a look at this? :smile: :rocket: Thank you for your time! :+1:
