### ISSUE TITLE
[SOLVED] Add support for ASUS X70ID-TY004V motherboard K70ID Ubuntu and Budgie 20.04, Linux Mint 19.3

### ISSUE THREAD

**Issue by leukimi** [dominiksalvet/asus-fan-control#48]
**[SOLVED]**
Solved with a recent linux kernel update by magic. Tested on Ubuntu Budgie 20.04.
[Jump to comment](https://github.com/dominiksalvet/asus-fan-control/issues/48#issuecomment-678985717).

**Environment**
asus-fan-control 3.8.0 Ubuntu 20.04.

**Basic configuration**
* `sudo asus-fan-control get-temps`
/usr/local/bin/asus-fan-control: 411: Illegal number: Erro
* `sudo asus-fan-control model-info`
name K70ID
addresses 1335
temperatures 55 60 62 65 68 72 76 80
tested false

**Additional context**
afc-gui not working. First, the file `afc-gui` is not found directly. Path does not contain $HOME/.local/share/bin/
Then:
```
$ ./afc-gui 
/usr/local/bin/asus-fan-control: 411: Illegal number: Erro
Traceback (most recent call last):
  File "./afc-gui", line 193, in <module>
    window = asuswindow()
  File "./afc-gui", line 89, in __init__
    label.set_text(gettemps_fun())
  File "./afc-gui", line 41, in gettemps_fun
    gettemps = sub.check_output("sudo asus-fan-control get-temps", shell=True)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'sudo asus-fan-control get-temps' returned non-zero exit status 2.

```

**Comment by leukimi** [comment]
```
user@linux:~$ su root
Password:
root@linux:~$ { echo '\_SB.PCI0.LPCB.EC0.RRAM 1335' > /proc/acpi/call &&
  cat /proc/acpi/call # usually there is no newline in the output
  printf '\n%s\n' "$?"; } # hence we are using printf to make output clean
bash: /proc/acpi/call: No such file or directory

1
root@linux:~$
```
The response is as you see:
**bash: /proc/acpi/call: No such file or directory**
exit code: 1

If it helps: I add a text file with the specifications about this [laptop ASUS X70ID-TY004V (picture)](https://cnet3.cbsistatic.com/img/Ktu2y7CEiL_OiqeNLAq_NCu0y2g=/fit-in/0x420/filters:no_upscale()/2017/01/21/f0edb4a4-990b-4ba5-abdd-e14003ea0c75/f0edb4a4-990b-4ba5-abdd-e14003ea0c75.jpg) motherboard K70ID.
[ASUS-X70ID-TY004V-K70ID-specs.txt](https://github.com/dominiksalvet/asus-fan-control/files/4776128/ASUS-X70ID-TY004V-K70ID-specs.txt)

**Comment by dominiksalvet** [comment]
> bash: /proc/acpi/call: No such file or directory

I suspect that you do not have acpi_call installed - GitPack installs it automatically in normal circumstances. Try `sudo apt update && sudo apt install acpi-call-dkms`. That should fix it.

> I noticed you manage to use colors in your post, and I wonder how you manage to do that. It increases readability. I don't see any buttons in the header that would allow me to add color information to text.

Take a look at your post - I have modified it so that it has colors as well. See its history and changes.

**Comment by dominiksalvet** [comment]
> Take a look at your post - I have modified it so that it has colors as well. See its history and changes.

Oh, there is no raw view... instead of \`\`\` at the beginning of the code block, I used \`\`\`sh.

**Comment by leukimi** [comment]
Thank you for the explanation!
```sh
user@linux:~$ sudo apt update && sudo apt install acpi-call-dkms
...
user@linux:~$ su root
Password:
root@linux:~$ modprobe acpi_call # without this command the following would not execute
root@linux:~$ { echo '\_SB.PCI0.LPCB.EC0.RRAM 1335' > /proc/acpi/call &&
>   cat /proc/acpi/call # usually there is no newline in the output
>   printf '\n%s\n' "$?"; } # hence we are using printf to make output clean
Error: AE_NOT_FOUND
0
root@linux~$
```
Not sure if this is expected... Someone posted in another forum that you have to load the `acpi_call` first before using it. Exit code 0 tells me this went "well" but Error: AE_NOT_FOUND seems it didn't go well.

**Comment by dominiksalvet** [comment]
> Someone posted in another forum that you have to load the `acpi_call` first before using it.

Definitely the right step - I have forgotten about it. :+1:

> Exit code 0 tells me this went "well" but Error: AE_NOT_FOUND seems it didn't go well.

It means that the ACPI call has been performed correctly but it ended up with an ACPI error. Unfortunately, AE_NOT_FOUND is a notorious issue that some laptop models suffer from. I interpret it as Access Entry NOT FOUND, so your laptop probably does not have the EC0 interface/entry.

So far there is no solution to that. Even then, asus-fan-control would need to be modified accordingly as it currently uses the ACPI path as a constant, not per-device. It wouldn't be hard to implement it, though.

See #34 and [this afc-scout issue](https://github.com/dominiksalvet/afc-scout/issues/1) for more information. Unfortunately, I am not able to help you as per the current state. :disappointed:

**Comment by leukimi** [comment]
All of a sudden, the fan control works. Magic! Not sure how it got fixed, but probably a recent kernel update (5.4.0-42?) or something suddenly controls the fan and it is no longer noisy. Probably a linux developer fixed it somehow.

**Comment by dominiksalvet** [comment]
Well, that's very good news! 👏 Thank you for the information. ❤️ The ASUS community will appreciate it.

I expect that asus-fan-control still does not work on your device, does it? 🤔 If not, feel free to close the issue as it is effectively solved. Otherwise, maybe asus-fan-control started to work due ACPI/kernel update... who knows...

**Comment by leukimi** [comment]
That is correct! **asus-fan-control** did not actually solve the famous "ASUS constant fan on top speed" issue, but a later kernel update apparently did. The fans are now working as expected and continue to do so at the time of writing. Tested on Ubuntu Budgie 20.04.

**Comment by leukimi** [comment]
I am trying to add a label "**solved**" (maybe you can add the label **solved**?) or marking it somehow as **solved** (apart from just closing the issue without an outcome note like **solved** or **not solved**) but I can't find the appropriate button so I write [SOVLED] before the title. Hope that is what you asked for.

**Comment by dominiksalvet** [comment]
@leukimi Once any AFC issue is closed, it is considered solved. So no need to add any "solved" indicator. It is rather confusing in this particular case as it does not really solve the issue described in the title "Add support for ASUS X70ID-TY004V motherboard K70ID"... Furthermore, this issue is labeled with `AE_NOT_FOUND` and it may indicate that it solves the infamous `AE_NOT_FOUND` problem that AFC suffers from.

Due to the reasons stated above, I am removing the "solved" indicator.

**Comment by dominiksalvet** [comment]
But anyway, thank you for your contribution! :heart:
