### ISSUE TITLE
Add support for ASUS TUF FX505DY

### ISSUE THREAD

**Issue by mthw0** [dominiksalvet/asus-fan-control#49]
**Environment**
Version 3.8.0 from AUR
System: Arch Linux

**Basic configuration**
* `sudo asus-fan-control get-temps`

>0 0 0 0 0 0 0 0

* `sudo asus-fan-control model-info`

> name TUFGamingFX505DYTUF505
addresses 1335
temperatures 55 60 62 65 68 72 76 80
tested false

**Additional context**
I have tried finding the right adresses with afc-scout but I haven't found anything, only zeros between adresses 0 and 5000.
https://github.com/dominiksalvet/asus-fan-control/issues/39#issuecomment-646713921

**Comment by dominiksalvet** [comment]
Hello @mthw0 and welcome to the asus-fan-control community! :wave:

1. Once you set values with `set-temps`, does `get-temps` report them?
2. Have you tried different versions of acpi_call?
3. Do other fan control solutions work (at least partially)?

**Comment by mthw0** [comment]
>     1. Once you set values with `set-temps`, does `get-temps` report them?
No, they don't change. 
>     2. Have you tried different versions of acpi_call?
No, but I will try with acpi_call-dkms. Do you have any specific version in mind? I use the latest acpi_call and latest kernel 5.7.4. I will try linux-mainline after rc2 is released.
>     3. Do other fan control solutions work (at least partially)?
I have tried pretty much everything from https://wiki.archlinux.org/index.php/Fan_speed_control but none of it works. I have come to a conclusion that I don't have PWM. The only thing that can change my fan speeds is `echo X >> /sys/devices/platform/asus-nb-wmi/throttle_thermal_policy` where  X={0,1,2}. Pressing Fn+f5 cycles through these values similar to Windows. 2 - quiet (but for some reason not as quiet as on W10), 1 - turbo (full speed), and 0 - balanced (about half speed). This only works since Kernel 5.6. 
I originally thought that this should work on my laptop because FX505GM is supported but that laptop is Intel+Nvidia and mine is AMD+AMD meaning the important parts are most likely completely different.
This is output from `sensors`: https://pastebin.com/crFTM686
Fan speed is reported correctly and CPU temps are also reported.

**Comment by dominiksalvet** [comment]
> No, but I will try with acpi_call-dkms. Do you have any specific version in mind? I use the latest acpi_call and latest kernel 5.7.4. I will try linux-mainline after rc2 is released.

Sorry, but I personally do not use Arch, so I cannot recommend you anything... However, let me know once you try something else.

> I originally thought that this should work on my laptop because FX505GM is supported but that laptop is Intel+Nvidia and mine is AMD+AMD meaning the important parts are most likely completely different.

Yeah, it seems so. Even ASUS distinguishes individual models when [downloading drivers](https://www.asus.com/Laptops/ASUS-TUF-Gaming-FX505/HelpDesk_Download/) for FX505 series - see *Please select your CPU or BIOS model name*.

What's more, your model belongs to another series. The mentioned series is only **FX505** series, you have **FX505DY** and those are different. It has its own [support page](https://www.asus.com/Laptops/ASUS-TUF-Gaming-FX505DY/HelpDesk_Download/). Interesting. :thinking:

**Comment by dominiksalvet** [comment]
Hello, BTW have you tried https://github.com/leonmaxx/asus_fanmode? :-)

**Comment by mthw0** [comment]
Thanks for the suggestion, I will try it and post results.

**Comment by mthw0** [comment]
So, the project you linked allows you to automatically select one of the existing profiles (quiet,balanced,turbo) based on the temperature. For me the quiet profile is already too loud and editing it to turn on the fans at a higher temperature is what I would like to do. (For example, now my temperature is ~40° and I can hear the fans from across the room.) Unfortunately setting manual fan speeds is only possible on more expensive models from the ROG line.

**Comment by dominiksalvet** [comment]
Well... And have you tried https://github.com/FlyGoat/RyzenAdj (there should be more options)? For more information, see #56.

**Comment by mthw0** [comment]
I have tried it, but there are no options related to fan control. This might be a coincidence, but around the time I used the tool, my power button stopped working (while the laptop is on). I had to reset my BIOS to get it working again so the tool might be touching something it is not supposed to. It might be a good idea to report it there.

**Comment by dominiksalvet** [comment]
Okay, I will close this issue but feel free to continue posting relevant updates if you want.
