### ISSUE TITLE
Asus VivoBook Pro 17 (X705FD)

### ISSUE THREAD

**Issue by StoyanYonkov** [dominiksalvet/asus-fan-control#50]
Hello ,
I have gone through pretty everything i can find on the internet trying to controll the fan's on this laptop.

I am running Windows 10. I have tried RWEverything but when i go to EC the whole EC register is 0x00.

i have addtionally tried to set

Hyper-Threading (on/off)
Intel Virtualization (on/off)
Intel AES-NI (on/off)
VT-D (on/off)
Memory Integrity (off/on)
Windows Test Mode (off/on)

But nothing seems to help i am opening this issue as to try and gather more information on how i can change the speeds of my fans.

Picture of RWEverything with EC open : https://i.imgur.com/r3ksmbL.png

**Comment by dominiksalvet** [comment]
Hello @StoyanYonkov and welcome to the asus-fan-control community! :wave:

Maybe you have already noticed that asus-fan-control is not supported on Windows as mentioned in #40. Nevertheless, I could at least direct you towards the solution used in asus-fan-control and that may be potentially applied on Windows using some supportive programs like one you mentioned.

> Hyper-Threading (on/off)
> Intel Virtualization (on/off)
> Intel AES-NI (on/off)
> VT-D (on/off)
> Memory Integrity (off/on)
> Windows Test Mode (off/on)

Should be unrelated at all. Try to avoid changing these and similar settings.

> I have tried RWEverything but when i go to EC the whole EC register is 0x00.

Asus-fan-control uses EC0 — full paths:

* `\_SB.PCI0.LPCB.EC0.WRAM` to set temperatures
* `\_SB.PCI0.LPCB.EC0.RRAM` to get temperatures

As base addresses (first address with a temperature value), it uses either `1335` (single fan) or `1335` together with `1431` (dual fan). Typical number of temperatures is 8. All values are in decimal form. Just for the sake of completeness: `1335` is `0x537` in hexadecimal form, `1431` is `0x597`.

---

Please note that not all ASUS laptops are designed this way - e.g., #49 has similar symptoms. In your particular case, issues may be cause by Windows permissions, your laptop model-specific configuration or it may be a BIOS issue. Anyway, I would recommend you to make sure that you have the latest BIOS for your model.

> BTW: Maybe you will be able to control fans from BIOS... :thinking:

**Comment by StoyanYonkov** [comment]
> Hello @StoyanYonkov and welcome to the asus-fan-control community! 👋
> 
> Maybe you have already noticed that asus-fan-control is not supported on Windows as mentioned in #40. Nevertheless, I could at least direct you towards the solution used in asus-fan-control and that may be potentially applied on Windows using some supportive programs like one you mentioned.
> 
> > Hyper-Threading (on/off)
> > Intel Virtualization (on/off)
> > Intel AES-NI (on/off)
> > VT-D (on/off)
> > Memory Integrity (off/on)
> > Windows Test Mode (off/on)
> 
> Should be unrelated at all. Try to avoid changing these and similar settings.
> 
> > I have tried RWEverything but when i go to EC the whole EC register is 0x00.
> 
> Asus-fan-control uses EC0 — full paths:
> 
> * `\_SB.PCI0.LPCB.EC0.WRAM` to set temperatures
> * `\_SB.PCI0.LPCB.EC0.RRAM` to get temperatures
> 
> As base addresses (first address with a temperature value), it uses either `1335` (single fan) or `1335` together with `1431` (dual fan). Typical number of temperatures is 8. All values are in decimal form. Just for the sake of completeness: `1335` is `0x537` in hexadecimal form, `1431` is `0x597`.
> 
> Please note that not all ASUS laptops are designed this way - e.g., #49 has similar symptoms. In your particular case, issues may be cause by Windows permissions, your laptop model-specific configuration or it may be a BIOS issue. Anyway, I would recommend you to make sure that you have the latest BIOS for your model.
> 
> > BTW: Maybe you will be able to control fans from BIOS... 🤔

Hello,
Thank you for the response.
Yes i am aware that Asus-fan-control is Linux only.

Are you aware of any program on windows that i can use to look for or modify with those adresses.

Also to my understanding arent those two adresses offsets ? how can i find the base adress and add them to that.
Example = 0x000000 + 0x537

Also i am on the latest BIOS for my model.

**Comment by dominiksalvet** [comment]
> Are you aware of any program on windows that i can use to look for or modify with those adresses.

Sorry, Linux-only user here. But maybe @RYSKZ can add something to this question?

> Also to my understanding arent those two adresses offsets ? how can i find the base adress and add them to that.
> Example = 0x000000 + 0x537

Do not know what you mean.

**Comment by StoyanYonkov** [comment]
> > Also to my understanding arent those two adresses offsets ? how can i find the base adress and add them to that.
> > Example = 0x000000 + 0x537
> 
> Do not know what you mean.

Let me see if i fully understand what is happening isn't this adress 0x537 added to a base address to calculate the location of let's say speed of fan1 and from there on it gets modified ? Similar to modifying game memory
Example 
Player base adress is 0x000100
0x000100 + 0x25 = Player X cordinate
0x000100 + 0x35 = Player Y
0x000100 + 0x45 = Player Z

Im sorry if this doesn't make sense im kind of new to all this.

**Comment by dominiksalvet** [comment]
No. Quoting myself:

> As base addresses (**first address with a temperature value**), it uses either `1335` (single fan) or `1335` together with `1431` (dual fan).

If you still do not get, take a look [here](https://github.com/dominiksalvet/asus-fan-control#custom-temperatures). Speed level 0 is at 0x537, speed level 1 at 0x538, etc.

Maybe the final address itself is composed of base + offset in the whole ACPI address space but in this case, the base would be determined by the entry point, EC0, and we do not know it. Otherwise it is just 0x537 to EC0 address space. That's all I know.

**Comment by RYSKZ** [comment]
> > Are you aware of any program on windows that i can use to look for or modify with those adresses.
> 
> Sorry, Linux-only user here. But maybe @RYSKZ can add something to this question?
> 
> > Also to my understanding arent those two adresses offsets ? how can i find the base adress and add them to that.
> > Example = 0x000000 + 0x537
> 
> Do not know what you mean.

I came across this repo: https://github.com/hirschmann/nbfc

Is cross-platform, but it only supports a limited range of laptop models, but still you can write your own configuration to make it compatible with your specific model, take a look here: https://github.com/hirschmann/nbfc/wiki/How-to-create-a-NBFC-config

**Comment by StoyanYonkov** [comment]
> > > Are you aware of any program on windows that i can use to look for or modify with those adresses.
> > 
> > 
> > Sorry, Linux-only user here. But maybe @RYSKZ can add something to this question?
> > > Also to my understanding arent those two adresses offsets ? how can i find the base adress and add them to that.
> > > Example = 0x000000 + 0x537
> > 
> > 
> > Do not know what you mean.
> 
> I came across this repo: https://github.com/hirschmann/nbfc
> 
> Is cross-platform, but it only supports a limited range of laptop models, but still you can write your own configuration to make it compatible with your specific model, take a look here: https://github.com/hirschmann/nbfc/wiki/How-to-create-a-NBFC-config

I have already tried NBFC problem is it also gives no output the EC is all 00 same as RWEverything.

**Comment by StoyanYonkov** [comment]
Hello , I decided to try afc-scout on Linux i downloaded Kali Linux because thats the only one im familiar with and live booted it. 
Here is the output of afc-scout i dont think its similar to the examples provided.
especialy the range between 1431-1438

I have not tried to edit the numbers but im pretty sure there will be no effect i also traced the numbers they are basiclly starting from 0 and they end at 255 somewhere after 1439

afc-scout output = https://i.imgur.com/RK68tFO.jpg

Any suggestions ? Ideas ?

**Comment by dominiksalvet** [comment]
Hello @StoyanYonkov! Unfortunately, this is a notorious issue with some ASUS models and they, as per the current state, do not work with asus-fan-control. Nevertheless, thank you so much for trying it on Linux — I really appreciate it since other users with the some laptop know what they could expect. :+1: :heart:

I would suggest that you take a look at [this particular afc-scout issue](https://github.com/dominiksalvet/afc-scout/issues/2). You will find a very similar situation and also how the ACPI values should look like from my UX430UA — plotted in graphs. Most of [these asus-fan-control issues](https://github.com/dominiksalvet/asus-fan-control/issues?q=is%3Aissue+is%3Aopen+label%3A%22set+but+not+get%22) also have the same problem. Feel free to take a look at them as well.

Sorry but I cannot help you in this situation. :disappointed:

**Comment by dominiksalvet** [comment]
> Most of [these asus-fan-control issues](https://github.com/dominiksalvet/asus-fan-control/issues?q=is%3Aissue+is%3Aopen+label%3A%22set+but+not+get%22) also have the same problem.

BTW, I would add the label to this issue as well but since you haven't tried to modify the temperatures, I cannot. Asus-fan-control modifies the first range of temperatures, 1335-1342, in default if you want to try it...

**Comment by StoyanYonkov** [comment]
Hello @dominiksalvet , I will try to set the values and come back with a result im not getting my hopes up tho as my values look exactly the same as these other people with the same issue. 
My plan as of now is to try and contact Asus directly and see what they respond with i kind of doubt they will give me any info that would help but who knows.

I have also fount out that my EC chip is ( ITE IT8995E-128 ) which is not supported by RWEverything most possibly the reason i get all 00 on Windows.

If Asus responds with anything that could help i will share the information here as i see alot of other people have this issue including on the NBFC issues

**Comment by dominiksalvet** [comment]
Thank you for all the information. Good work! :+1:

> My plan as of now is to try and contact Asus directly and see what they respond with i kind of doubt they will give me any info that would help but who knows.

Yeah, that's a good idea. I have done the same about the power management of my laptop a few months after I bought it. It had taken some time but eventually they helped me! :smile: 

> If Asus responds with anything that could help i will share the information here as i see alot of other people have this issue including on the NBFC issues

Definitely! :+1: Wish you the best of luck.

**Comment by StoyanYonkov** [comment]
Hello @dominiksalvet , I have tried asus-fan-control but it sandly does not work :(

I did receive a response from Asus they basiclly told me that there is no official information on controlling the fans for my laptop and that there is no BIOS setting or software that i can install to do that.

I responded with a more indepth explanation of the information i want from them i hope they undestand this time what im asking for.

Hopefully they respond with something usefull this time.

**Comment by StoyanYonkov** [comment]
Hello , i got a second response from Asus. Literally a copy paste of their last response. Sadly nothing helpful came from them.

**Comment by dominiksalvet** [comment]
I suspect that your issue ends in the support office instead of on the desk of a hardware guy who knows something about it. Still, it would be unofficial and thus they probably have zero interest to do that. That's unfortunate. 😞

Anyway, let us know if you find out something useful.
