### ISSUE TITLE
Need help to get the program working.

### ISSUE THREAD

**Issue by vaishnavnegi** [dominiksalvet/asus-fan-control#51]
I recently shifted to using Linux from Windows 10 which had ASUS's own software for fan control. In current setup fans are dead
OS:Ubuntu 20.04
Model :Asus ROG Strix GL503GE-EN270T Gaming Laptop

So I installed the program using git pack and following happened:
```
sudo gitpack install github.com/dominiksalvet/asus-fan-control
modprobe: ERROR: could not insert 'acpi_call': Operation not permitted
file /proc/acpi/call does not exist
failed to apply changes immediately
[install] github.com/dominiksalvet/asus-fan-control 3.8.0
```
I scoured the net for possible solutions, improvised some of them for this, but nothing seems to work. I keep getting this error : 
**file /proc/acpi/call does not exist**

And I apologize for my informal style of asking for help in advance, I am a novice when it comes to using online forums for tech help.SORRY.

**Comment by dominiksalvet** [comment]
Hello @vaishnavnegi and welcome here! :wave:

Before using asus-fan-control, the `acpi_call` module must be loaded. GitPack tried it after installation and, after each boot, asus-fan-control tries to do the same. Once loaded, the file `/proc/acpi/call` is created and can be used as an entry point for ACPI calls.

So actually the most important error report is `modprobe: ERROR: could not insert 'acpi_call': Operation not permitted`. I strongly suspect that you have secure boot enabled on your device in BIOS. Once disabled, everything should be fine.

Please read about the consequences of disabling secure boot on the Internet. In short, on Linux system it is generally disabled unless you need all hardware drivers signed. I personally do not use secure boot.

Hope it will solve the issue. 😉
