### ISSUE TITLE
Add command to run fan at a desired speed

### ISSUE THREAD

**Issue by ezio-ac** [dominiksalvet/asus-fan-control#52]
**Description**
A command to run the fan at a desired speed regardless of the temp
like this command sets fan speed to 50% (level 4)
`sudo asus-fan-control setspeed 4`
 
a workaround could be like for 50% (level 4) you set temps below that level to very low and above that level to very high
example `sudo asus-fan-control set-temps 20 20 20 20 20 100 100 100`
 it would be a great to have a command for that

**Reason**
Sometimes you need to adjust the speed without caring about the temps, like if you are about to start an intensive task just set the speed to 100% before starting, thus making temps rise slowly

**Comment by dominiksalvet** [comment]
Hello @ezio-ac and welcome to the asus-fan-control community! :wave: :speech_balloon: 

First thank you for your suggestion — I understand the mind behind it. :bulb: Unfortunately, that does not fit asus-fan-control's simplicity and I believe it is not so important for most people. Hence, I am not going to work on that, either I will not merge it if someone else adds it. :no_entry_sign:

NEVERTHELESS, this kind of suggestion is not a newcomer here. There were some requested features that are related to asus-fan-control but they are not that important to include them in asus-fan-control itself. Please, take a look at [afc-scout](https://github.com/dominiksalvet/afc-scout) and [afc-gui](https://github.com/Greifent/afc-gui). Those are basically asus-fan-control extensions.

So if you or anyone want to implement the proposed feature (and even more later), I would suggest creating a new repository called [afc-plus](https://github.com/ezio-ac/afc-plus) or so and implement this feature there. You should be fine with the asus-fan-control API as you have mentioned. Provided it is going to happen, do not forget to use the [afc topic](https://github.com/topics/afc) in the repository.

> Then I would take care about the propagation of the repository here in asus-fan-control as an optional extension.

What do you think? :thinking:

**Comment by Greifent** [comment]
Hi @ezio-ac I was thinking on adding that function on [afc-gui](https://github.com/Greifent/afc-gui), you can expect that in the future!

**Comment by dominiksalvet** [comment]
@Greifent Would it be better to create a new repository as mentioned previously, e.g. [afc-plus](https://github.com/Greifent/afc-plus), and add all extra functionality there? Then add support to afc-gui afterwards to better apply *divide and conquer* pattern and to prevent confusing people... :thinking: 

The afc-plus itself does not have to be written in a shell, you can use your favorite language! :rocket: Please think about it. :star:

> I do not insist on this approach, I just want you to consider it and express your opinion on that. :smile: :+1:

**Comment by Greifent** [comment]
![Screenshot from 2020-08-03 10-34-16](https://user-images.githubusercontent.com/59480824/89162865-fb76a200-d574-11ea-9f21-d180e762d7cd.png)

![Screenshot from 2020-08-03 10-39-17](https://user-images.githubusercontent.com/59480824/89163272-9cfdf380-d575-11ea-8a44-60f692899a02.png)

![Screenshot from 2020-08-03 10-39-25](https://user-images.githubusercontent.com/59480824/89163284-a0917a80-d575-11ea-91f0-e7e121f0d5ce.png)


That could also work but, as you can see for the previous photos (Ignore the error message, I've a new computer and I don't have asus-fan-controll installed), I'm working to completely remake the GUI in a way that will allow me to have more things. What I was thinking is adding another page and in that one allow the user to set the fan speed: for example 100%, 75%... 

I was thinking of adding that one directly on the GUI, but also the afc-plus is a good idea, unfortunately I don't think that I can follow both project at the same time, so for now it will be added directly to the GUI. And is someone in the future want more feature that we did not think of, the other repository may be a good idea.

**Comment by dominiksalvet** [comment]
Okay, it makes sense. Thank you for the new afc-gui demo! Glad to see it moving forward.

Please, let us know if you implement the desired feature so that I can close this issue. :+1: :sun_with_face: 

---

> I've a new computer and I don't have asus-fan-controll installed

BTW do you have an ASUS again? Is it one of tested devices? Just curious... :smile:

**Comment by Greifent** [comment]
I'm using a desktop (gaming), so I don't need asus-fan-control, i still have the old computer to test.
Specs:
Ryzen 9 3900x
16 GB ram @ 3600MHz
RX 5700 XT
Dual boot Pop os & Windows 10, both in a dedicated NVME SSD and with 1TB Hdd each

**Comment by Greifent** [comment]
I'll let you know when the update is released!
