### ISSUE TITLE
error precp script failed with 100 on Ubuntu 20.04

### ISSUE THREAD

**Issue by romarmorales** [dominiksalvet/asus-fan-control#53]
Receiving the following message during installation:

$ sudo gitpack install github.com/dominiksalvet/asus-fan-control
E: Sub-process /usr/bin/dpkg returned an error code (1)
precp script failed with 100
<ERROR> install github.com/dominiksalvet/asus-fan-control

On Ubuntu 20.04:
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal

uname -a
Linux dbzen 5.6.0-1019-oem #19-Ubuntu SMP Wed Jul 1 14:34:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

acpi_call is already installed:

acpi-call-dkms/focal,focal,now 1.1.0-5 all [installed]
  Kernel module that enables you to call ACPI methods

**Comment by dominiksalvet** [comment]
Hi @romarmorales! :wave:

That does not look like an asus-fan-control related issue. Neither GitPack's, I think. Try search for `E: Sub-process /usr/bin/dpkg returned an error code (1)` a bit. You may have broken dpkg on your system. There is a ton of guides of possible fixes on the Internet. Have you looked at them? I would suggest you to follow some trustworthy guide and try it again.

Anyway, what is the output of the following commands?

* `dpkg -l dmidecode`
* `sudo apt-get install -y dmidecode`

**Comment by romarmorales** [comment]
Thanks, I googled focusing on the wrong string. Turns out it was a dependency issue as I was on a kernel newer than the acpi-call-dkms version would support for ubuntu 20.04. I had to grab the acpi-call-dkms deb file from 20.10. It appears to be working now. For reference, the ASUS model I'm on is the ZenBook Pro Duo UX581.

**Comment by dominiksalvet** [comment]
> For reference, the ASUS model I'm on is the ZenBook Pro Duo UX581.

If asus-fan-control is working on your device, please read [contributing.md](https://github.com/dominiksalvet/asus-fan-control/blob/master/contributing.md) and create a [new issue](https://github.com/dominiksalvet/asus-fan-control/issues/new/choose) to make asus-fan-control recognize your device model. You may help others with the same device and you will be declared its first tester. I have put a lot of effort into making contributing easy and straightforward.
