### ISSUE TITLE
Add support for Asus ROG G53SW

### ISSUE THREAD

**Issue by mohamadali-halwani** [dominiksalvet/asus-fan-control#54]
Greetings everyone, 
I would like to thank you for this wonderful opportunity and wonderful work, I'd love it if the fans in my notebook work as they should be, I've been dealing with this issue since i migrated from windows, and now with summer heat i get critical temperature shutdowns whenever i put extra load on my laptop.
Generally an Asus G53SW has 2 fans on the back, one for the CPU and the other is for the GPU
normally, the GPU fan can run to max, but I failed to run the CPU fan (roughly speaking) any higher than the speed of 1 (by the measures of your asus-fan-control)
so I hope we can work together through this to make G53SW supported
thanks again, here's the requested info : 

**Environment**
```
OS: Arch Linux x86_64 
Host: G53SW 1.0 
Kernel: 5.5.7-arch1-1 
Shell: zsh 5.8 
CPU: Intel i7-2630QM (8) @ 2.900GHz 
GPU: NVIDIA GeForce GTX 460M 
Memory: 1357MiB / 7938MiB 
asus-fan-control version :  3.8.0-1
asus-fan-dkms-git version : v0.9.1.r89.g6d5f558-1
asus-wmi-sensors-dkms-git version :  55.320a68e-1
```

**Basic configuration**
* `sudo asus-fan-control get-temps` output : 
`0 0 0 0 0 0 0 0`

* `sudo asus-fan-control model-info` output : 
```
name G53SW 
addresses 1335 
temperatures 55 60 62 65 68 72 76 80 
tested false 
```

**Advanced configuration**
* `sudo FALLBACK_ADDRS='<addrs>' FALLBACK_TEMPS='<temps>' asus-fan-control model-info` output : 
```
name G53SW 
addresses 1335 
temperatures 10 
tested false 
```

**Additional context**
afc-scout output : 

```
------ base address 1335 ------ 
[1334] = 0 
[1335] = 0 <- possible start 
[1336] = 0 
[1337] = 0 
[1338] = 0 
[1339] = 0 
[1340] = 0 
[1341] = 0 
[1342] = 0 <- possible end 
[1343] = 0 
------ base address 1431 ------ 
[1430] = 0 
[1431] = 0 <- possible start 
[1432] = 0 
[1433] = 0 
[1434] = 0 
[1435] = 0 
[1436] = 0 
[1437] = 0 
[1438] = 0 <- possible end 
[1439] = 0 


```

**Comment by dominiksalvet** [comment]
Hello @mohamadali-halwani! Sorry but I do not have time right now, will get to it later. Feel free to take a look at [this issues](https://github.com/dominiksalvet/asus-fan-control/labels/set%20but%20not%20get) in the meantime as they may be helpful. Should I forget about this issue, please remind me later.

**Comment by mohamadali-halwani** [comment]
> Hello @mohamadali-halwani! Sorry but I do not have time right now, will get to it later. Feel free to take a look at [these issues](https://github.com/dominiksalvet/asus-fan-control/labels/set%20but%20not%20get) in the meantime as they may be helpful. Should I forget about this issue, please remind me later.

@dominiksalvet 
No problems at all, just tell me when is the best time for you so i can schedule it and work on it with you.
Also if you think that I can be of a help in anyways possible (in adding support to my laptop) I would be glad to help.
please accept my deepest thanks, have a nice day.

**Comment by dominiksalvet** [comment]
After the 20th is fine for me.

**Comment by mohamadali-halwani** [comment]
> After the 20th, it is fine for me.
Hi @dominiksalvet 
this is just a reminder, that if you're free nowadays, let's work on this 💚

**Comment by dominiksalvet** [comment]
So yeah, I am finally here! :sweat_smile:

Unfortunately, it doesn't look good to be honest. See #49. I have the same questions...

1. Once you set values with `set-temps`, does `get-temps` report them?
2. Have you tried different versions of acpi_call?
3. Do other fan control solutions work (at least partially)?

**Comment by mohamadali-halwani** [comment]
>     1. Once you set values with `set-temps`, does `get-temps` report them?
Unfortunately no, they still persist on being zeros
 
>     2. Have you tried different versions of acpi_call?
I'm currently running these versions of acpi packages:
acpi 1.7-2 
acpi_call 1.1.0-293 
and didn't try any other versions, is it possible that my notebook is not supported by the acpi_call package ?

>     3. Do other fan control solutions work (at least partially)?
Nothing works so far, pwmconfig only controls the gpu fan and cannot reach the cpu's fan, which results in the same result : "Critical temperature shutdown"s on load

**Comment by dominiksalvet** [comment]
That's not good. Unfortunately, at this point I am not able to anything... :disappointed: Sorry for letting you wait for this trivial answer but I was really busy.

> is it possible that my notebook is not supported by the acpi_call package ? How can we test that ?

I think it is possible but not probable -- some old devices may suffer from that I would say. I am talking about ACPI as a whole. I do not expect that there are some limitation implied by acpi_call... Nevertheless, devices have different ACPI address space layout and functionality than others. So this may be the problem...

Initially, asus-fan-control was developed for my own personal needs and later was discovered that it implicitly supports other devices as well. The asus-fan-control's core itself is still the same.

I am really sorry that I cannot help you. Your desire to cooperate, which is not something all issue creators have, also amplifies it. Maybe we could cross our paths again in different projects! :rocket:

**Comment by dominiksalvet** [comment]
BTW, I have just realized a simple thing. It may sound stupid but have you tried cleaning your laptop? See #32, whose author originally came with it and it helped him very much. He is also the creator of asus-fan-control wiki.

**Comment by dominiksalvet** [comment]
@mohamadali-halwani Please let us know whether it helps.

**Comment by mohamadali-halwani** [comment]
> BTW, I have just realized a simple thing. It may sound stupid but have you tried cleaning your laptop? See #32, whose author originally came with it and it helped him very much. He is also the creator of asus-fan-control wiki.

unfortunately I cleaned my laptop 2 months ago, the base temperature went down from 50 to 40, but the inability to control the fan speed is still the same before and after cleaning, I can't do anything that is demanding like compiling and even opening more than one browser.
I'm still gonna try, but if I couldn't figure a solution, I may go back to windows or see if there's a descent distro that doesn't have such substantial core issues

**Comment by mohamadali-halwani** [comment]
as a last resort, I'm going to focus on getting the asus kernel module to work
[https://wiki.archlinux.org/index.php/Fan_speed_control](Fan Speed control)

**Comment by dominiksalvet** [comment]
Yeah... certainly let us know if you find something that actually works for you. :smile:
