### ISSUE TITLE
Getting Error while installing in Ubuntu 20.04

### ISSUE THREAD

**Issue by aman-roy** [dominiksalvet/asus-fan-control#55]
**Environment**
OS - Ubuntu (Kernal version 5.7.10)

**Description**
After running the installation command, I am getting this error - 

```
$ sudo gitpack install github.com/dominiksalvet/asus-fan-control

[sudo] password for aman: 
E: Sub-process /usr/bin/dpkg returned an error code (1)
precp script failed with 100
<ERROR> install github.com/dominiksalvet/asus-fan-control
```

**Replication**
State steps to replicate the bug.

**Additional context**
Add expected behavior or solution and any other context.

**Comment by dominiksalvet** [comment]
Duplicate of #53.

**Comment by dominiksalvet** [comment]
Hello, do you use asus-fan-control nowadays? If so, what device do you have please?
