### ISSUE TITLE
Add support for ASUS TUF A15 FA506IU-AL127T

### ISSUE THREAD

**Issue by ThomasThongCE** [dominiksalvet/asus-fan-control#56]
**Environment**
asus-fan-control version: 3.8.0
OS: Ubuntu 20.04
Linux Kernel: 5.6.15-050615-generic
Processor: AMD Ryzen 7 – 4800H
GeForce Geforce GTX 1660Ti
acpi-call-dkms: version 1.1.0-6

**Basic configuration**
* `sudo asus-fan-control get-temps` output:
```
/usr/local/bin/asus-fan-control: 411: Illegal number: Erro
```
* `sudo asus-fan-control model-info` output:
```
name TUFGamingFA506IUFA506IU
addresses 1335
temperatures 55 60 62 65 68 72 76 80
tested false
```

**Additional context**
The difference between TUF A15 FA506IU versions is the size of the battery and capability of insert 2.5" drive.

Because the higher version kernel, the acpi-call-dkms package download from https://packages.ubuntu.com/groovy/acpi-call-dkms

When I run `afc-scout` the ouput: 
```
------ base address 1335 ------
/usr/local/bin/afc-scout: 48: Illegal number: Erro
```
and dmesg output this line: `acpi_call: Cannot get handle: Error: AE_NOT_FOUND`

The folder `/proc/acpi` only contains three folders: button, call, and wakeup.

when I manually write it to acpi call using following command (with ### is some number):
```
echo "\_SB.PCI0.LPCB.EC0.WRAM  ### " | sudo tee /proc/acpi/call > /dev/null && sudo cat /proc/acpi/call
```
The result is  `Error: AE_NOT_FOUND% ` and dmesg still output: `acpi_call: Cannot get handle: Error: AE_NOT_FOUND`

It seems like the acpi method `\_SB.PCI0.LPCB.EC0.WRAM` doesn't exist or it has been changed.

Because right now the fan didn't even bother to change speed when the CPU almost reaches 95 degrees. I really want to help to make this work but I still a newbie in this whole acpi things. Currently I'm stuck didn't know where to go. Can you answer a few questions below: 

1. If it has been changed, then how to find the right acpi string used to control the fan?
2. Does this laptop model doesn't even support acpi fan control? If it doesn't, can we bring the method that windows control the fan into Linux?

**Comment by dominiksalvet** [comment]
@ThomasThongCE Welcome to the asus-fan-control community! 😊

Unfortunately, this is a notorious issue with some laptop models. See the [AE_NOT_FOUND](https://github.com/dominiksalvet/asus-fan-control/labels/AE_NOT_FOUND) issues. Generally, laptops with AMD processors do not work under asus-fan-control.

> 1. If it has been changed, then how to find the right acpi string used to control the fan?

I do not know. Asus-fan-control supports only EC0 entry point. You probably will need to find and check others manually or search the Internet.

> 2. Does this laptop model doesn't even support acpi fan control?

I do not know. I have just created a wrapper POSIX shell script. I am not a deep ACPI guru guy. 🤓  But I guess it does somehow since ACPI is not only about controlling fans.

> If it doesn't, can we bring the method that windows control the fan into Linux?

Here I have absolutely no idea. I don't have Windows, so I couldn't help in this manner either.

I am afraid that I am not able to help you with asus-fan-control. Nevertheless, if you somehow make it working or you find another solution that works for you, please leave a message here. It can help others with the same laptop. 🚀

**Comment by ThomasThongCE** [comment]
Hello @dominiksalvet 
Thank you for the response.
Currently, I'm investigating the acpi table (or something like that, didn't know what is that actually called) of my laptop and indeed the `\_SB.PCI0.LPCB` doesn't exist. But there is `EC0` in `\_SB.PCI0.SBRG`. I do not know if this is the `EC0` that controls the fan or not. 
Could you send me your `dsdt.dsl` file from machine which can run asus-fan-control? I will really appreciate it.

You can extract the acpi table with the following command.
```
sudo apt install acpica-tool
sudo acpidump -b -n DSDT
iasl -d dsdt.dat
```

**Comment by dominiksalvet** [comment]
I am sorry but I am not in the ACPI DSDT table stuff and hence I do not know exactly which information it contains. So I will not provide it to you unless you do the same on your device first. I think that's fair.

**Comment by ThomasThongCE** [comment]
ACPI file is a tree structure that describes the hardware the laptop has and it's stored at the BIOS. So I guess it doesn't have any security risk because you can get that file from another laptop which has the same model.

Because I doesn't familiar with this ACPI thing, It's great to have another working dsdt file to serve as a reference file. 

My laptop DSDT file in this [link](https://github.com/dominiksalvet/asus-fan-control/files/5012380/dsdt.txt). `EC0` device start at line 5786. The memory map of the `EC0` starts at line *5838* and *6069*. But it doesn't have `EC0.WRAM` method (assume it is a write to ram method).

**Comment by dominiksalvet** [comment]
Okay, [here](https://github.com/dominiksalvet/asus-fan-control/files/5015110/dsdt.txt) is mine. :+1: Interesting – my DSDT table has four times more lines than yours. :smile:

**Comment by ThomasThongCE** [comment]
Thank you for your support.

Four times more line =(((, that is not a good sign. Seem like my file and your file are very diffrence. 
It's pretty much a dead end for now, but if I figure something out, I will leave a message here.

**Comment by ThomasThongCE** [comment]
It turns out that AMD has there own embedded controller which controls the thermal and fan thing call System Management Unit (SMU). Because of this, the ACPI based solution won't work on AMD machine.
It looks like the SMU won't allow you to manually control the fan speed, or at least in this laptop model (ASUS TUF A15 FA506IU-AL127T). It controls the fan automatically depend on the mode (silent, performance, turbo) you select in windows proprietary app which preinstalled in the laptop. 

Luckily, the mode will be saved even when you restart or turn off the machine, or boot into Linux. 
There is some tool which will help to communicate with the SMU if you want to have more control over the SMU.

I hope this will help anyone who has the same problem as me.

**Comment by dominiksalvet** [comment]
Thank you so much for the analysis and the report. ❤️ If you have actual links to the mentioned SMU tools, please share it with us - maybe it will help people from other asus-fan-control issues.

Also, do you know any simple way (in terminal of course) to find out whether a device uses SMU? That would allow me to tell people that their device is unsupported straight away... That would save a lot of time...

> Hmmm... Maybe the ``

**Comment by dominiksalvet** [comment]
Sorry, did not want to close it yet... You know - editing text close to the "Close and comment" button on a smartphone... 😃

**Comment by dominiksalvet** [comment]
Ok, thanks. I will close this issue now as we have showed that this laptop is definitely incompatible with asus-fan-control. Should you have any further comments, feel free to continue in the discussion... 😊

**Comment by dominiksalvet** [comment]
Thank you so much for your contributions! ❤️

**Comment by gbaranski** [comment]
> It turns out that AMD has there own embedded controller which controls the thermal and fan thing call System Management Unit (SMU). Because of this, the ACPI based solution won't work on AMD machine.
> It looks like the SMU won't allow you to manually control the fan speed, or at least in this laptop model (ASUS TUF A15 FA506IU-AL127T). It controls the fan automatically depend on the mode (silent, performance, turbo) you select in windows proprietary app which preinstalled in the laptop.
> 
> Luckily, the mode will be saved even when you restart or turn off the machine, or boot into Linux.
> There is some tool which will help to communicate with the SMU if you want to have more control over the SMU.
> 
> I hope this will help anyone who has the same problem as me.

Instead of booting windows, you can simply write to it
```zsh
echo 0 | sudo tee /sys/devices/platform/asus-nb-wmi/throttle_thermal_policy
```
0 - Normal(default)
1 - Turob
2 - Silent

However the silent mode is still too loud for me. Below 45*C fans keep 0 RPM, but if > 45*C it goes > 2200RPM which is quite loud.

**Comment by Falcosc** [comment]
Did you look into asus-nb-wmi?

There is more to discover.
`ASUS_WMI_DEVID_CPU_FAN_CTRL`
https://github.com/torvalds/linux/blob/489e9fea66f31086f85d9a18e61e4791d94a56a4/drivers/platform/x86/asus-wmi.c#L1349

But there are currenlty no fd's available for this

**Comment by logical-and** [comment]
> ```shell
> echo 0 | sudo tee /sys/devices/platform/asus-nb-wmi/throttle_thermal_policy
> ```

Implemented in https://github.com/leonmaxx/asus_fanmode
