### ISSUE TITLE
Add support for ROG Strix SCAR III

### ISSUE THREAD

**Issue by azamet90** [dominiksalvet/asus-fan-control#6]
```
┌─[azamet@localhost]─[/tmp/gitpack]
└──╼ $sudo gitpack install github.com/dominiksalvet/asus-fan-control
/usr/local/bin/asus-fan-control: Missing temperatures for your notebook model or they are invalid. Falling back to UX430UA temperatures.
[install] github.com/dominiksalvet/asus-fan-control 2.9.1
┌─[azamet@localhost]─[/tmp/gitpack]
└──╼ $asus-fan-control
/usr/local/bin/asus-fan-control: Please run as root.
┌─[✗]─[azamet@localhost]─[/tmp/gitpack]
└──╼ $sudo asus-fan-control
/usr/local/bin/asus-fan-control: Missing temperatures for your notebook model or they are invalid. Falling back to UX430UA temperatures.
```

have the laptop model g731gv

**Comment by dominiksalvet** [comment]
@azamet90 Hello and welcome! As long as your notebook's fan is being controlled after the installation, everything is fine and expected - your model is not supported yet and hence the error reports.

However, by my search I expect that your notebook model has two fans - I do not have a clue how it reacts in this situation or whether it works at all.

Anyway, take a closer look at [this guide](https://github.com/dominiksalvet/asus-fan-control/blob/master/CONTRIBUTING.md#testing-a-new-notebook-model) on adding a new notebook model support and proceed as stated (with issue already created).

Please, let me know how things are going. Tomorrow, I can take a closer look at it.

**Comment by azamet90** [comment]
okay i will try it let this topic stay open

**Comment by dominiksalvet** [comment]
Yop, you are right - you do not have to create a new issue and use this one instead. Once I know that asus-fan-control really works on your device (see below), I change issue labels to make it more relevant.

However, I need additional information from you right now - is asus-fan-control affecting your's fan speed as per its current state? Optionally, try `asus-fan-control -set-temps:<numbers>` as shown in [this example](https://github.com/dominiksalvet/asus-fan-control#set-up-custom-fan-speed-policy) and let me know whether it affects the fan speed and how - I mean in case you really have two fans setup, I would like to also know which one is affected (CPU or GPU), or whether both are affected.

Thank you very much! :rocket:

**Comment by azamet90** [comment]
> Yop, you are right - you do not have to create a new issue and use this one instead. Once I know that asus-fan-control really works on your device (see below), I change issue labels to make it more relevant.
> 
> However, I need additional information from you right now - is asus-fan-control affecting your's fan speed as per its current state? Optionally, try `asus-fan-control -set-temps:<numbers>` as shown in [this example](https://github.com/dominiksalvet/asus-fan-control#set-up-custom-fan-speed-policy) and let me know whether it affects the fan speed and how - I mean in case you really have two fans setup, I would like to also know which one is affected (CPU or GPU), or whether both are affected.
> 
> Thank you very much! rocket

sorry for delay but i will today do it definitifly after if these things fails can i remove this tool completely? this is more important for me after fresh install because of i dont want to do fresh install again :D if you can help me with uninstall it completely i will try now this tool with that commands you give

**Comment by dominiksalvet** [comment]
All right, first things first.

**Complete uninstallation** may be performed as follows:
1. Uninstall asus-fan-control using GitPack - `sudo gitpack uninstall github.com/dominiksalvet/asus-fan-control` - that will remove the program itself.
2. Its configuration is kept in */etc/asus-fan-control* directory and may be manually removed (it is not removed by GitPack to make asus-fan-control updating possible).
3. If you had not had configured acpi_call kernel module before asus-fan-control installation (which is my case after fresh Ubuntu 18.04 install), you can also remove it. Remove lines containing `acpi_call` from */etc/modules* file. You can also remove the acpi_call provider package - use `sudo apt-get remove acpi-call-dkms` (which again is not installed in my case after fresh OS install).
4. Reboot your device.

PS: Despite of trying to be comprehensive, note that some files may left untouched but they should not affect an OS at all.

---

Please **provide more information** - output of `sudo dmidecode -s system-product-name`. So far it looks like your system has different ACPI addresses than tested models, which is not a good sign.

---

Try to **listen the fan/s** as temperature configuration changes and report what you have heard:

1. Use `sudo asus-fan-control -set-temps:'20 25 30 35 40 45 50 55'` - now you certainly should hear your fan/s quite a loudly.
2. Use `sudo asus-fan-control -set-temps:'80 81 82 83 84 85 86 87'` - now you should not hear any sound produced by fan/s at all.

PS: Use the commands above only in idle state - meaning no intensive program running alongside!

---

Please **beautify terminal output** and code properly. For inline styling, use \`echo hi\`. To style multiple lines, use:

\`\`\`
echo hi
echo hello
\`\`\`

PS: Please include this styling also in your previous posts to make them more readable for newcomers. Thank you. :heart:

**Comment by azamet90** [comment]
> All right, first things first.
> 
> **Complete uninstallation** may be performed as follows:
> 
>     1. Uninstall asus-fan-control using GitPack - `sudo gitpack uninstall github.com/dominiksalvet/asus-fan-control` - that will remove the program itself.
> 
>     2. Its configuration is kept in _/etc/asus-fan-control_ directory and may be manually removed (it is not removed by GitPack to make asus-fan-control updating possible).
> 
>     3. If you had not had configured acpi_call kernel module before asus-fan-control installation (which is my case after fresh Ubuntu 18.04 install), you can also remove it. Remove lines containing `acpi_call` from _/etc/modules_ file. You can also remove the acpi_call provider package - use `sudo apt-get remove acpi-call-dkms` (which again is not installed in my case after fresh OS install).
> 
>     4. Reboot your device.
> 
> 
> PS: Despite of trying to be comprehensive, note that some files may left untouched but they should not affect an OS at all.
> 
> Please **provide more information** - output of `sudo dmidecode -s system-product-name`. So far it looks like your system has different ACPI addresses than tested models, which is not a good sign.
> 
> Try to **listen the fan/s** as temperature configuration changes and report what you have heard:
> 
>     1. Use `sudo asus-fan-control -set-temps:'20 25 30 35 40 45 50 55'` - now you certainly should hear your fan/s quite a loudly.
> 
>     2. Use `sudo asus-fan-control -set-temps:'80 81 82 83 84 85 86 87'` - now you should not hear any sound produced by fan/s at all.
> 
> 
> PS: Use the commands above only in idle state - meaning no intensive program running alongside!
> 
> Please **beautify terminal output** and code properly. For inline styling, use `echo hi`. To style multiple lines, use:
> 
> ```
> echo hi
> echo hello
> ```
> 
> PS: Please include this styling also in your previous posts to make them more readable for newcomers. Thank you. heart

> sudo dmidecode -s system-product-name
> [sudo] password for azamet: 
> ROG Strix G731GV_G731GV

i did tryed to use video rendering to see if the fan works and it works but starting to work later then before i think something like after maybe 65 celsius :/ of course im noob i think it so because of i do watch sensors command during video rendering and listen the fan sound same time...
like i said before if i do set temp after get temp the result of get temp is same and now i do have full time for this if you are here

**Comment by dominiksalvet** [comment]
@azamet90 I am really sorry but your model seems to have symptoms of unsupported models as also seen in #4. I can't do anything. :disappointed: 

There is only one solution and it is quite dangerous; find ACPI fun addresses yourself. Then, add support for model-based addresses. I would rather recommend you to try other projects for fan control.

Still, if you are in (or anyone) and want to **add support for this model**, take a look at [this post](https://github.com/daringer/asus-fan/issues/44#issuecomment-307589414). It might be helpful as all current supported models are based on it. Please, let us know in case you find out something important.

@azamet90 Feel free to close this issue if you do not have additional comments. I am really sorry that I could not help you. :cry:

**Comment by dominiksalvet** [comment]
@azamet90 Hey, I have been thinking that it will be better for this issue to stay open to let people know that it is still not resolved and they can **contribute** by doing so. I believe that you agree.

**Comment by azamet90** [comment]
++++++

**Comment by azamet90** [comment]
any news?

**Comment by dominiksalvet** [comment]
@azamet90 Just for clarification - I am not working on it at all - I am just leaving it open for other to know that it needs to be solved. Anyways, no news from my side.

---

BTW, I recommend you to also watch #4 and #5 as it seems that they are related to each other.

**Comment by dominiksalvet** [comment]
Hi @azamet90! :wave: 

Good news here! I have just released the [3.0.0](https://github.com/dominiksalvet/asus-fan-control/releases/tag/3.0.0) version with support for different base ACPI addresses among laptop models.

That means once you know/find the base ACPI fan address for your device, asus-fan-control can fully support it. Please, let me know if you do so. It would be so exciting to see this new feature actually being used! :rocket:

**Comment by dominiksalvet** [comment]
@azamet90 Another good news! :rocket: 

I have created [afc-scout](https://github.com/dominiksalvet/afc-scout) program that can help you to find your base ACPI fan address. It is conveniently distributed using GitPack. Please give it a try. :+1:

**Comment by azamet90** [comment]
i was long time not here i see it now and is the tool now updated for my laptop model?

**Comment by dominiksalvet** [comment]
> i was long time not here i see it now and is the tool now updated for my laptop model?

Not yet, your action is demanded for that. 😉 Give it a shot! 😃

**Comment by azamet90** [comment]
> @azamet90 Another good news! rocket
> 
> I have created [afc-scout](https://github.com/dominiksalvet/afc-scout) program that can help you to find your base ACPI fan address. It is conveniently distributed using GitPack. Please give it a try. +1
> 
> Feel free to also take a look at [the contributing guide](https://github.com/dominiksalvet/asus-fan-control/blob/master/contributing.md), which has been updated to guide you through the process.

hello sorry for extreme late but i did tryed to run it without installing and i get this error: 

file /proc/acpi/call does not exist

**Comment by dominiksalvet** [comment]
> file /proc/acpi/call does not exist

GitPack installs acpi_call module as well. You need to install it manually then. You can use `sudo apt install acpi-call-dkms`.
