### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by DEBA1801** [dominiksalvet/asus-fan-control#61]
Hi, 

I am trying to install this package on my ASUS TUF Fx504 GE model. I am fairly new to Linux and have installed Ubuntu 20.04 recently by removing my windows 10. After installing i noticed that the "Fn" key + F5 which used to control the fan speeds earlier on windows is not working. 

So, I tried installing this package but I am facing some problems. 

running this command on the terminal : `sudo gitpack install github.com/dominiksalvet/asus-fan-control`
returns this error: `sudo: gitpack: command not found`

How can I solve this and install this on my system. 

Thanks in advance

**Comment by dominiksalvet** [comment]
Hello @DEBA1801 and welcome to the asus-fan-control community! :tada: :rocket: 

Have you installed GitPack first? :slightly_smiling_face: See [this guide](https://github.com/dominiksalvet/gitpack#install) and feel free to choose the global installation. Then try installing asus-fan-control again.

Please note that your model is not a tested device. That, however, does not mean it won't work, it means that we do not know yet. If it runs for you, it could close #47, which is always good to hear. :+1: 

Let us know.

**Comment by DEBA1801** [comment]
Hi, 

Yes the problem was installing the gitpack first. So I did install git first. Later installed the gitpack. But now when I run 
`sudo gitpack install github.com/dominiksalvet/asus-fan-control`

The terminal seems to be stuck there. No process is happening after that.

**Comment by DEBA1801** [comment]
Update: 

The asus-fan-control package seems to be installed. However, now I get this error: 

file /proc/acpi/call does not exist


Since earlier the process was stuck. I had to kill the process which was installing acpi_call . How do I fix this?

**Comment by dominiksalvet** [comment]
> The terminal seems to be stuck there.

I know about that... I will fix it with upcoming GitPack and asus-fan-control releases.

> How do I fix this?

Try `sudo gitpack uninstall github.com/dominiksalvet/asus-fan-control` and then `sudo gitpack install github.com/dominiksalvet/asus-fan-control` again and wait for it to finish. That should fix it all.

**Comment by Jovian-Dsouza** [comment]
I too have the same laptop as @DEBA1801 , But sadly I am getting this error : 
`acpi call failed with 'Error: AE_NOT_FOUND'`

I am using asus-fan-control version 3.9.0

**Comment by dominiksalvet** [comment]
Hello @Jovian-Dsouza. Unfortunately, there is no solution to this problem yet. See issues labeled with [AE_NOT_FOUND](https://github.com/dominiksalvet/asus-fan-control/issues?q=is%3Aissue+is%3Aopen+label%3AAE_NOT_FOUND) for more information.

**Comment by dominiksalvet** [comment]
Hello guys, do you have any experience with https://github.com/leonmaxx/asus_fanmode? It may work for your devices...
