### ISSUE TITLE
Add support for Asus Zenbook UX391FA

### ISSUE THREAD

**Issue by samuel-parra** [dominiksalvet/asus-fan-control#63]
**Environment**
asus-fan-control  3.8.0 and  Manjaro 20.0.3 Kernel 5.8.6-1-MANJARO

**Basic configuration**
If only temperatures were configured, add output of:
* `sudo asus-fan-control get-temps` 
55 56 57 58 59 60 61 62
* `sudo asus-fan-control model-info` 
name ZenBookUX391FAUX391FA
addresses 1335
temperatures 55 60 62 65 68 72 76 80
tested false

**Additional context**
i see an error on dmesg when try set the temperatures and the temperatures not change
[ 1732.026770] ACPI Warning: \_SB.PCI0.LPCB.EC0.WRAM: Insufficient arguments - Caller passed 2, method requires 3 (20200528/nsarguments-230)
[ 1732.027765] ACPI Warning: \_SB.PCI0.LPCB.EC0.WRAM: Insufficient arguments - Caller passed 2, method requires 3 (20200528/nsarguments-230)
[ 1732.028654] ACPI Warning: \_SB.PCI0.LPCB.EC0.WRAM: Insufficient arguments - Caller passed 2, method requires 3 (20200528/nsarguments-230)
[ 1732.029606] ACPI Warning: \_SB.PCI0.LPCB.EC0.WRAM: Insufficient arguments - Caller passed 2, method requires 3 (20200528/nsarguments-230)
[ 1732.030703] ACPI Warning: \_SB.PCI0.LPCB.EC0.WRAM: Insufficient arguments - Caller passed 2, method requires 3 (20200528/nsarguments-230)
[ 1732.031793] ACPI Warning: \_SB.PCI0.LPCB.EC0.WRAM: Insufficient arguments - Caller passed 2, method requires 3 (20200528/nsarguments-230)
[ 1732.032916] ACPI Warning: \_SB.PCI0.LPCB.EC0.WRAM: Insufficient arguments - Caller passed 2, method requires 3 (20200528/nsarguments-230)
[ 1732.034013] ACPI Warning: \_SB.PCI0.LPCB.EC0.WRAM: Insufficient arguments - Caller passed 2, method requires 3 (20200528/nsarguments-230)

**Comment by dominiksalvet** [comment]
Hi @samuel-parra and welcome to the asus-fan-control community! :wave:

Thank you for your analysis. Unfortunately, I can confirm that afc passes only two arguments to ACPI calls and there are no similar warnings in my dmesg output. It looks like your laptop model uses a different mechanism for the fan control behind the ACPI wall... Also, this is the first time I see this issue.

I am sorry, but for the reasons stated above, I cannot help you. There are two options, though.

1. You will add the support for your device yourself. This would include dealing with afc internals.
2. You will find a working alternative to afc for your device. Please let us know if you do so. :wink: 

> Keep in mind that the addresses that afc uses may not be the fan addresses on your device...

**Comment by dominiksalvet** [comment]
Hey @samuel-parra, how is it going? Have you managed to make asus-fan-control work on your device? Or do you use another solution, such as your [Asus-Zenbook-UX391FA](https://github.com/samuel-parra/Asus-Zenbook-UX391FA)? Please let us know since the ASUS community does not have to always use asus-fan-control. :wink:  I am open to recommending other tools if asus-fan-control does not work (even if it does :smile:).

**Comment by dominiksalvet** [comment]
Okay, I expect no progress on this issue since I am pretty much ignored... Should you, however, have something to add, let me know! :octocat:

**Comment by samuel-parra** [comment]
Hi @dominiksalvet sorry to no respond. I used a script to control the temperature disabling turbo and change the cpu frequencies. I couldn't control the Zenbook  fans with any tools.
