### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by Black-J88** [dominiksalvet/asus-fan-control#64]
How can I uninstall? I've found a better alternative.

**Comment by Black-J88** [comment]
Sorry for my silly question, I found it.

`sudo gitpack uninstall github.com/dominiksalvet/asus-fan-control`

Please delete this issue.

**Comment by dominiksalvet** [comment]
Hello @Black-J88! :wave:

> I found it.

I am glad that you didn't have long trouble with asus-fan-control/GitPack. :smile:

> Please delete this issue.

I will keep this issue for other people if you don't mind...?

> I've found a better alternative.

Please share the alternative with us. The asus-fan-control community may benefit from that as well. :wink:

**Comment by Black-J88** [comment]
My laptop is ASUS TUF FX504GD. Even with this tool, I couldn't find the fans spinning as they should. So I found an alternative for ASUS TUF Series Laptops. 

https://github.com/leonmaxx/asus_fanmode

**Comment by dominiksalvet** [comment]
Thank you! 😊

> Even with this tool, I couldn't find the fans spinning as they should.

BTW, have you tried `sudo asus-fan-control set-temps <temps>`? Does afc affect your fans at least somehow?
