### ISSUE TITLE
Add support for <Void Linux> (or any support for non systemd, specifically runit.

### ISSUE THREAD

**Issue by darkralts** [dominiksalvet/asus-fan-control#67]
my fans rly annoying and getting this to work on my os would be great ^~^ 
i have a prime x470 pro
https://www.asus.com/us/Motherboards/PRIME-X470-PRO/

**Comment by dominiksalvet** [comment]
Hello @darkralts and welcome! 😊

As you may see, there are only two AFC developers, of which only one is active right now (me). I personally use Ubuntu and I am not going to change this in the foreseeable future. The other developer uses Arch, which has systemd as well.

What I am trying to say is that we are not able to add and test this support for AFC ourselves. If you want, you can contribute to AFC. Nevertheless, I doubt it will work on your particular hardware as this program focuses on laptops. The MB of the link is not from a laptop, is it? 🤔

So what do you think?

**Comment by darkralts** [comment]
ah i guess its alot more complicated than i thought, and no it is not from a laptop, its a desktop. it just sucks not being able to control my fans as for some reason they go rly fast on linux, and the aui suite 3 software i use for windows doesnt work on linux which sucks. i would contribute for sure if i was a coder or knew anything about it but unfortunately i am not that good in that field. i hope i can find at least some way to quiet my fans :)

**Comment by darkralts** [comment]
maybe someday if more people decide fan control for asus is important and a smart non systemd coding user stumbles apon here ^~^

**Comment by dominiksalvet** [comment]
If you could test AFC on a systemd-based Linux, it would be great to see whether it works for your MB. It would be the first MB working but as I said chances are pretty low, so do not feel bad if you cannot test it.

Should you find something that works for you, do not forget to let us know. I like to connect people with ASUS devices. :smile:

**Comment by darkralts** [comment]
thats a good idea ill try that :D

**Comment by darkralts** [comment]
the main software im trying to replace is asus ai suite 3 for windows

**Comment by dominiksalvet** [comment]
> thats a good idea ill try that :D

Hello @darkralts! Is there any progress on that? :thinking:

**Comment by darkralts** [comment]
raat
