### ISSUE TITLE
Add support for Asus vivobook X412FJ

### ISSUE THREAD

**Issue by prateekp-01** [dominiksalvet/asus-fan-control#69]
*Environment*
asus-fan-control version - 3.9.0
os - ubuntu 20.04 lts

*Basic configuration*
sudo asus-fan-control get-temps - 55 56 57 58 59 60 61 62
sudo asus-fan-control model-info-
	name VivoBookASUSLaptopX412FJX412FJ
	addresses 1335
	default-temps 55 60 62 65 68 72 76 80
	tested false

**Comment by prateekp-01** [comment]
My laptop is Asus vivobook X412FJ

**Comment by dominiksalvet** [comment]
Hello @prateekp-01 and welcome to AFC community! :wave:

Please, can you tell me a bit more about the temperatures you have chosen? Namely, the increasing step of 1 – why?

**Comment by prateekp-01** [comment]
That's not the tempratures I had choosen.
I used the command
sudo asus-fan-control set-temps 60 65 68 70 72 75 78 80

**Comment by dominiksalvet** [comment]
So you set temperatures and get different temperatures, right? If so, I am in doubt that AFC works on your laptop. Do set temperatures really affect your fan speed? For more info, see our [AFC wiki](https://github.com/dominiksalvet/asus-fan-control/wiki) troubleshooting.

**Comment by prateekp-01** [comment]
I tried running the command sudo afc-scout
------ base address 1335 ------
[1334] = 54
[1335] = 55 <- possible start
[1336] = 56
[1337] = 57
[1338] = 58
[1339] = 59
[1340] = 60
[1341] = 61
[1342] = 62 <- possible end
[1343] = 63
------ base address 1431 ------
[1430] = 150
[1431] = 151 <- possible start
[1432] = 152
[1433] = 153
[1434] = 154
[1435] = 155
[1436] = 156
[1437] = 157
[1438] = 158 <- possible end
[1439] = 159

Also I tried using two very different temprature ranges but felt no change in fan speed.

**Comment by prateekp-01** [comment]
I'm really hoping that you will help me. I recently started using Ubuntu replacing Windows but I'm facing a big problem that cpu and gpu fans are constantly running at quite high speed and that's draining a lot of battery and also is too annoying. If this problem will not be solved I will have to switch back to Windows which I really don't want to. I tried almost every solution present on AskUbuntu and so you are my last hope :)

**Comment by dominiksalvet** [comment]
Unfortunately, I must tell you that this looks like one of the notorious issues with some models (see some issues with the [set but not get](https://github.com/dominiksalvet/asus-fan-control/issues?q=is%3Aissue+is%3Aopen+label%3A%22set+but+not+get%22) label), so I would not expect that asus-fan-control itself would be of any help here. :cry:

Nevertheless, have you tried https://github.com/hirschmann/nbfc and https://github.com/daringer/asus-fan? Neither should have support for your particular device but it worth the try. BTW do you know about https://wiki.archlinux.org/index.php/fan_speed_control? It may be helpful as well.

Anyway, should you find something that helps you, please let us know! :rocket: The ASUS community will appreciate it.

**Comment by prateekp-01** [comment]
Thanks @dominiksalvet . I haven't gone through those but will check them soon.

**Comment by kenohassler** [comment]
Hey there, I have the same laptop and experimented a bit:
My experience is that the return value only depends on the first byte we give to `read_acpi_value()` (beautiful plot in #5). Consequently, `read_acpi_value(55) == read_acpi_value(1335)` and `read_acpi_value(151) == read_acpi_value(1431)`.
I don't know if this holds in general or only for the set-but-not-get devices.

However, if you call `read_acpi_value(132)`, the laptop fan stops briefly. Going a bit further, if you write to this address, it seems one can set the fan duty cyle -- but only for <1s, until the fan is put back to the default. Maybe there is another register where the fan can be switched from automatic to manual mode to actually make this useful? 😅

**Comment by dominiksalvet** [comment]
@kenohassler Good findings! Should your investigation continue, let us know about the progress. :rocket:
