### ISSUE TITLE
Add support for  ROG G752VL

### ISSUE THREAD

**Issue by icegood** [dominiksalvet/asus-fan-control#7]
**Environment**
[install] github.com/dominiksalvet/asus-fan-control 2.9.1
uname -a:
Linux *********** 5.3.0-25-generic #27-Ubuntu SMP Wed Dec 4 13:36:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Temperature configuration**
45 50 55 60 65 70 75 80

**Notebook model name**
G752VL

Hi there.
I've already applied appropriate concerns into kernel org:
https://bugzilla.kernel.org/show_bug.cgi?id=153281
and waiting for new kernel releases. Meanwhile i want to apply right fan settings under my laptop. In attach you can find dmidecode and acpidump outputs

[1.zip](https://github.com/dominiksalvet/asus-fan-control/files/3964962/1.zip)

**Comment by dominiksalvet** [comment]
Hello and thank you for the contribution! Your notebook has two-fan setup, hasn't it? In that case, please, try to explain me how it behaved before and after the asus-fan-control was applied. E.g., whether both fans are affected and whether equally, etc.

**Comment by icegood** [comment]
Hi. I haven't found any information about two-fan configuration of my laptop. Both windows and linux detect the only CPU fan. You may find the only information from it under linux in attached file.

**Comment by dominiksalvet** [comment]
If there are two fans, maybe they are driven equally... Anyways, the support for your model with the delivered temperatures is included in the [2.10.0](https://github.com/dominiksalvet/asus-fan-control/releases/tag/2.10.0) release. Just use `sudo gitpack install github.com/dominiksalvet/asus-fan-control` and you are good to go. You should no longer see any warning messages of falling back to UX430UA temperatures.

I am closing this issue as resolved. Nevertheless, let me know whether everything is fine... :smile:

**Comment by dominiksalvet** [comment]
@icegood Hey man, so is it working for your device? I want to know... :smile:
