### ISSUE TITLE
Add support for Asus Vivobook X507UF

### ISSUE THREAD

**Issue by vaibhav-hexa** [dominiksalvet/asus-fan-control#73]
**Environment**
asus-fan-control 3.9.0
Linux Mint 20 Cinnamon 4.6.7
Asus Vivobook X507UF (i5-8250U)
Kernel 5.4.0-56-generic

**Basic configuration**
If only temperatures were configured, add output of:
* `sudo asus-fan-control get-temps` 
```
55 60 65 70 75 80 85 90
```

* `sudo asus-fan-control model-info`
```
name VivoBook15ASUSLaptopX507UF
addresses 1335
default-temps 55 60 62 65 68 72 76 80
tested false
```

**Advanced configuration**
If advanced configuration was used, add output of:
* `sudo FALLBACK_ADDRS='<addrs>' FALLBACK_TEMPS='<temps>' asus-fan-control model-info`

```
Advanced configuration was not used.
```

**Additional context**
Please make sure that the `Secure boot` feature is disabled if any error occurs.

**Comment by dominiksalvet** [comment]
Hello and thank you for your swift action! :+1: 

In the previous issue, you have mentioned forking and pushing the changes. Now I have enough information for adding the support for your device myself. But if you would like to contribute directly (merge request), I will be more than happy. You can take https://github.com/dominiksalvet/asus-fan-control/commit/23af1f23a50e4c055eb5b4a4c5fd736406b18ba2 as an example.

**Comment by vaibhav-hexa** [comment]
> Hello and thank you for your swift action! 
> 
> In the previous issue, you have mentioned forking and pushing the changes. Now I have enough information for adding the support for your device myself. But if you would like to contribute directly (merge request), I will be more than happy. You can take [23af1f2](https://github.com/dominiksalvet/asus-fan-control/commit/23af1f23a50e4c055eb5b4a4c5fd736406b18ba2) as an example.

Hello, happy to contribute! I have submitted a [PR #74 ](https://github.com/dominiksalvet/asus-fan-control/pull/74).
