### ISSUE TITLE
Asus Rog G752VY Fans keep running

### ISSUE THREAD

**Issue by YuliiaHavrylenko** [dominiksalvet/asus-fan-control#76]
**$ sudo asus-fan-control model-info
name G752VY
addresses 1335
default-temps 55 60 62 65 68 72 76 80**

But all fans still working on maximum. =(

**Laptop temperature:
sensors
iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +30.0°C  

pch_skylake-virtual-0
Adapter: Virtual device
temp1:        +47.5°C  

BAT0-acpi-0
Adapter: ACPI interface
in0:          15.00 V  

asus-isa-0000
Adapter: ISA adapter
cpu_fan:     25500 RPM
temp1:        +34.0°C  

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +35.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +35.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +35.0°C  (high = +100.0°C, crit = +100.0°C)
Core 2:        +35.0°C  (high = +100.0°C, crit = +100.0°C)
Core 3:        +34.0°C  (high = +100.0°C, crit = +100.0°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +34.0°C  (crit = +103.0°C)**

**Comment by dominiksalvet** [comment]
Hello @YuliiaHavrylenko and welcome to the asus-fan-control community! :wave: :smile: 

Please add a sequence of `set-temps` and `get-temps`, and their output.

**Comment by YuliiaHavrylenko** [comment]
Thank you =) @dominiksalvet and I'm happy that the community is exists.

Here is the result:
sudo asus-fan-control set-temps
no temperatures for setting provided

sudo asus-fan-control get-temps
45 50 55 60 65 70 75 80

**Comment by dominiksalvet** [comment]
> sudo asus-fan-control set-temps

You need to use some temperatures, otherwise, asus-fan-control (AFC) won't do anything and print an error message. See [our wiki](https://github.com/dominiksalvet/asus-fan-control/wiki) on how to control AFC, play a bit with various temperature configurations, and watch for any fan speed changes. :cyclone: Then, report the results. :tada:

**Comment by YuliiaHavrylenko** [comment]
I tried:
sudo asus-fan-control set-temps 55 60 62 65 68 72 76 80
sudo asus-fan-control set-temps 60 65 70 75 80 85 90 95

Same result. Fans works om maximum
asus-isa-0000
Adapter: ISA adapter
cpu_fan:
  fan1_input: 25500.000
temp1:
  temp1_input: 38.000

**Comment by dominiksalvet** [comment]
Please try temperatures mentioned in the wiki.

> If you don't know whether asus-fan-control works on your device:
>
> * Try different setups of temperatures, e.g., `sudo asus-fan-control set-temps 30 35 40 45 50 55 60 65` and then `sudo asus-fan-control set-temps 60 65 70 75 80 85 90 95`. You definitely should hear the difference.

If it does not work, try `sudo asus-fan-control set-temps 80 81 82 83 84 85 86 87` just quickly. That should turn off your fan until 80 degrees is reached. Then, you can set the default temperatures back using `sudo asus-fan-control set-temps default`.

**Comment by dominiksalvet** [comment]
And BTW are you able to set temperatures and then get the same temperatures?

**Comment by YuliiaHavrylenko** [comment]
> And BTW are you able to set temperatures and then get the same temperatures?

$ sudo asus-fan-control set-temps 30 35 40 45 50 55 60 65
$ sudo asus-fan-control set-temps 60 65 70 75 80 85 90 95
$ sudo asus-fan-control get-temps
60 65 70 75 80 85 90 95
$ sudo asus-fan-control set-temps 80 81 82 83 84 85 86 87
$ sudo asus-fan-control set-temps 45 50 55 60 65 70 75 80
$ sudo asus-fan-control set-temps default
$ sudo asus-fan-control get-temps
55 60 62 65 68 72 76 80

Still same result, fans on maximum (

**Comment by YuliiaHavrylenko** [comment]
> And BTW are you able to set temperatures and then get the same temperatures?

$ sudo asus-fan-control set-temps 30 35 40 45 50 55 60 65
$ sudo asus-fan-control set-temps 60 65 70 75 80 85 90 95
$ sudo asus-fan-control get-temps
60 65 70 75 80 85 90 95
$ sudo asus-fan-control set-temps 80 81 82 83 84 85 86 87
$ sudo asus-fan-control set-temps 45 50 55 60 65 70 75 80
$ sudo asus-fan-control set-temps default
$ sudo asus-fan-control get-temps
55 60 62 65 68 72 76 80

Still same result, fans on maximum (

**Comment by dominiksalvet** [comment]
Well, I haven't seen this issue yet. I am sorry but there is probably nothing I can do with this. Should you find out something (or other tool that works for you), let us know. :rocket:

BTW does the fan works with Windows? Is there anything different with the fan speed when you enter BIOS?

**Comment by YuliiaHavrylenko** [comment]
> BTW does the fan works with Windows? Is there anything different with the fan speed when you enter BIOS?

In Windows and in the BIOS everything goes properly, fans speed depends from tasks which I'm doing.

**Comment by dominiksalvet** [comment]
Well, at least it is not a hardware issue as hinted by your last post, which is always good... :smile: Which OS do you use? Have you considered reinstalling it?

**Comment by YuliiaHavrylenko** [comment]
> Well, at least it is not a hardware issue as hinted by your last post, which is always good... smile Which OS do you use? Have you considered reinstalling it?

First I'm used 20.04 Ubuntu, when i try to install 20.10. Same result. Also tried to use different kernel. Same (

**Comment by dominiksalvet** [comment]
Okay. Maybe you can try to play a bit with afc-scout. Uninstall asus-fan-control and **reboot**. After, install my afc-scout and run it with sudo without arguments and report the output. Then, try to run afc-scout with 0 4095 arguments and add the output as well (it will be big, please upload it as a file or a collapsible text block). We are trying to search for values that look like a temperatures sequence.

**Comment by YuliiaHavrylenko** [comment]
> Okay. Maybe you can try to play a bit with afc-scout. Uninstall asus-fan-control and **reboot**. After, install my [afc-scout](https://github.com/dominiksalvet/afc-scout) and run it with sudo without arguments and report the output. Then, try to run afc-scout with 0 4095 arguments and add the output as well (it will be big, please upload it as a file or a collapsible text block). We are trying to search for values that look like a temperatures sequence.

Hi. I get this one:
sudo gitpack install github.com/dominiksalvet/afc-scout
[installed] github.com/dominiksalvet/afc-scout 2.0.1
sudo afc-scout
file /proc/acpi/call does not exist
sudo afc-scout 0 4095
file /proc/acpi/call does not exist

**Comment by dominiksalvet** [comment]
Oh sorry, I have forgotten about that. :sweat:  Without AFC, you need to first run `sudo modprobe acpi_call` and then you can run afc-scout. I will fix it in the next release of afc-scout.

**Comment by YuliiaHavrylenko** [comment]
> Oh sorry, I have forgotten about that. 😓 Without AFC, you need to first run `sudo modprobe acpi_call` and then you can run afc-scout. I will fix it in the next release of afc-scout.

It's okay. ) So, am I'm uderstanding right, I need to remove AFC, when sudo modprobe acpi_call and when install again, or no need to remove?

**Comment by dominiksalvet** [comment]
1. Remove AFC (we do not want it to modify some ACPI addresses)
2. Reboot
3. `sudo modprobe acpi_call`
4. Use afc-scout freely :rocket:

**Comment by YuliiaHavrylenko** [comment]
>     1. Remove AFC (we do not want it to modify some ACPI addresses)
> 
>     2. Reboot
> 
>     3. `sudo modprobe acpi_call`
> 
>     4. Use afc-scout freely rocket

I'm sorry, but how to remove it? x) I tried this, but this doesn't work:

```
sudo apt remove afc-scout
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package afc-scout
sudo apt remove afc
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package afc
sudo apt remove github.com/dominiksalvet/afc-scout
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package github.com/dominiksalvet
```

**Comment by dominiksalvet** [comment]
You need to use the same way as with the installation. Instead of `install`, you will use `uninstall`. So, e.g., `sudo gitpack uninstall github.com/dominiksalvet/asus-fan-control`. AFC is an acronym of asus-fan-control. The same applies for `afc-scout`.

**Comment by dominiksalvet** [comment]
Hello @YuliiaHavrylenko, any updates? :smile:
