### ISSUE TITLE
Add support for ROG Strix Scar 17 [G732LXS]

### ISSUE THREAD

**Issue by algo7** [dominiksalvet/asus-fan-control#79]
**It does not work**
If neither configuration was working for your device, community involvement is required. Please provide some information so the community can build on something.

**Additional context**
```bash
OS: Ubuntu 20.04.1 LTS
cat /sys/class/dmi/id/product_name => ROG Strix G732LXS_G732LXS
cat /sys/class/dmi/id/board_name => G732LXS
cat /sys/devices/platform/asus-nb-wmi/hwmon/hwmon5/pwm1_enable  => 2 #auto mode
sudo pwmconfig => usr/sbin/pwmconfig: There are no pwm-capable sensor modules installed
tried GRUB_CMDLINE_LINUX="acpi_enforce_resources=lax" => no effect

# There is only one fan detected
sensors =>
iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:            N/A  

pch_cometlake-virtual-0
Adapter: Virtual device
temp1:        +43.0°C  

BAT0-acpi-0
Adapter: ACPI interface
in0:          15.68 V  

asus-isa-0000
Adapter: ISA adapter
cpu_fan:     2000 RPM

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +41.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +40.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +40.0°C  (high = +100.0°C, crit = +100.0°C)
Core 2:        +40.0°C  (high = +100.0°C, crit = +100.0°C)
Core 3:        +40.0°C  (high = +100.0°C, crit = +100.0°C)
Core 4:        +42.0°C  (high = +100.0°C, crit = +100.0°C)
Core 5:        +40.0°C  (high = +100.0°C, crit = +100.0°C)
Core 6:        +41.0°C  (high = +100.0°C, crit = +100.0°C)
Core 7:        +40.0°C  (high = +100.0°C, crit = +100.0°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +41.0°C  (crit = +103.0°C)
```

I am new to this field so I apologize if the information provided above is insufficient or irelevant. I would add extra info. if more is needed.

I am also willing to become the first tester for this model if there is a plan to support this device.

**Comment by dominiksalvet** [comment]
Hello @algo7 and welcome to the AFC community! :wave: :tada:

Please provide more information, such as output during/after installation. Have you tried to use `set-temps` and `get-temps`? If so, provide output as well. Also, `model-info` would be appreciated... :smile: Please have a look at [our wiki](https://github.com/dominiksalvet/asus-fan-control/wiki) as there is a lot of useful information here.

> ```shell
> cat /sys/class/dmi/id/board_name => G732LXS
> ```

BTW, that leads me to the idea that AFC does not need to use dmidecode and can read directly the appropriate file/s. If you could substitute `dmidecode -s system-product-name` command with manual file read/s, we can get rid of dmidecode dependency. It is used here:

https://github.com/dominiksalvet/asus-fan-control/blob/a330ec51085979cec8015189571e15dd6ccf81b4/src/asus-fan-control#L237

**Comment by algo7** [comment]
Ok. Thanks. I will get back to you with related information. As I have my final exams now, there might be some delay :)

**Comment by dominiksalvet** [comment]
Hey @algo7! :wave: Any updates on this?
