### ISSUE TITLE
missing map file gitpack

### ISSUE THREAD

**Issue by msazanov** [dominiksalvet/asus-fan-control#83]
**Environment**
3.10.0 asus-fan-control
NAME="Ubuntu"
VERSION="20.10 (Groovy Gorilla)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.10"
VERSION_ID="20.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
ASUS ROG SCAR II (gl504gw)

**Description**
When I try to install the updated version through gitpack, I get an error 
`random@random-PC:~$ sudo gitpack install github.com/dominiksalvet/asus-fan-control
[sudo] password for random: 
missing map file
<ERROR> install github.com/dominiksalvet/asus-fan-control
`

**Replication**
The error occurs immediately when trying to install

**Comment by dominiksalvet** [comment]
Hello and welcome to the AFC community!

What is your GitPack version -`gitpack about`? If it is 0.7.0 and below, you need to update GitPack first. See [this discussion](https://github.com/dominiksalvet/gitpack/discussions/10) for more info and let me know. 😉

**Comment by dominiksalvet** [comment]
Ok, I believe that the above will help. Closing as resolved.

**Comment by msazanov** [comment]
Yeep, that works! Thanks
