### ISSUE TITLE
UX310UA working

### ISSUE THREAD

**Issue by theamarin** [dominiksalvet/asus-fan-control#84]
Just wanted to let you know model UX310UA is working perfectly fine!
```
$ sudo asus-fan-control about
asus-fan-control 3.10.0
...
```
```
$ sudo asus-fan-control model-info
name UX310UA
addresses 1335
default-temps 55 60 62 65 68 72 76 80
tested false
...
```
```
$ sudo uname -a
Linux 5.10.0-3-amd64 #1 SMP Debian 5.10.13-1 (2021-02-06) x86_64 GNU/Linux
```
Thanks for your great work!

**Comment by dominiksalvet** [comment]
Oh, hello @theamarin and welcome to the community! :wave:

Thank you for letting me know and for the kind words. Do the default temperatures work for you?

**Comment by dominiksalvet** [comment]
Okay, I have used the default temperatures. Should you find better ones, let me know and I can change it. Thank you for the contribution!! :heart_eyes: :rocket:

**Comment by theamarin** [comment]
> Oh, hello @theamarin and welcome to the community! wave
> 
> Thank you for letting me know and for the kind words. Do the default temperatures work for you?

Thanks! Yes, they do!
