### ISSUE TITLE
Add support for asus GL504GW

### ISSUE THREAD

**Issue by msazanov** [dominiksalvet/asus-fan-control#86]
**Environment**
State asus-fan-control version and OS information.
3.10.0

NAME="Ubuntu"
VERSION="20.10 (Groovy Gorilla)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.10"
VERSION_ID="20.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy

H/W path           Device          Class          Description
=============================================================
                                   system         Strix GL504GW_GL504GW
/0                                 bus            GL504GW
/0/0                               memory         64KiB BIOS
/0/8                               memory         16GiB System Memory
/0/8/0                             memory         8GiB SODIMM DDR4 Synchronous 2667 MHz (0,4 ns)
/0/8/1                             memory         [empty]
/0/8/2                             memory         8GiB SODIMM DDR4 Synchronous 2667 MHz (0,4 ns)
/0/8/3                             memory         [empty]
/0/14                              memory         384KiB L1 cache
/0/15                              memory         1536KiB L2 cache
/0/16                              memory         9MiB L3 cache
/0/17                              processor      Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
/0/100                             bridge         8th Gen Core Processor Host Bridge/DRAM Registers
/0/100/1                           bridge         Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor PCIe Controller 
/0/100/1/0                         display        TU106M [GeForce RTX 2070 Mobile]
/0/100/1/0.1                       multimedia     TU106 High Definition Audio Controller
/0/100/1/0.2                       bus            TU106 USB 3.1 Host Controller
/0/100/1/0.2/0     usb3            bus            xHCI Host Controller
/0/100/1/0.2/1     usb4            bus            xHCI Host Controller
/0/100/1/0.3                       bus            TU106 USB Type-C UCSI Controller
/0/100/2                           display        UHD Graphics 630 (Mobile)
/0/100/4                           generic        Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsyste
/0/100/8                           generic        Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th/8th Gen Core Processor G
/0/100/12                          generic        Cannon Lake PCH Thermal Controller
/0/100/14                          bus            Cannon Lake PCH USB 3.1 xHCI Host Controller
/0/100/14/0        usb1            bus            xHCI Host Controller
/0/100/14/0/5                      input          ROG Gladius II
/0/100/14/0/9                      multimedia     USB2.0 HD UVC WebCam
/0/100/14/0/a                      input          N-KEY Device
/0/100/14/0/e                      communication  Bluetooth 9460/9560 Jefferson Peak (JfP)
/0/100/14/1        usb2            bus            xHCI Host Controller
/0/100/14.2                        memory         RAM memory
/0/100/14.3        wlo1            network        Wireless-AC 9560 [Jefferson Peak]
/0/100/14.5                        generic        Intel Corporation
/0/100/15                          bus            Cannon Lake PCH Serial IO I2C Controller #0
/0/100/15.1                        bus            Cannon Lake PCH Serial IO I2C Controller #1
/0/100/16                          communication  Cannon Lake PCH HECI Controller
/0/100/17                          storage        Cannon Lake Mobile PCH SATA AHCI Controller
/0/100/1d                          bridge         Cannon Lake PCH PCI Express Root Port #9
/0/100/1d/0                        storage        Realtek Semiconductor Co., Ltd.
/0/100/1d/0/0      /dev/nvme0      storage        ADATA SX6000PNP
/0/100/1d/0/0/1    /dev/nvme0n1    disk           1024GB NVMe namespace
/0/100/1d/0/0/1/1  /dev/nvme0n1p1  volume         127MiB reserved partition
/0/100/1d/0/0/1/2  /dev/nvme0n1p2  volume         528MiB Windows NTFS volume
/0/100/1d/0/0/1/3  /dev/nvme0n1p3  volume         99MiB Windows FAT volume
/0/100/1d/0/0/1/4  /dev/nvme0n1p4  volume         952GiB Windows NTFS volume
/0/100/1d/0/0/1/5  /dev/nvme0n1p5  volume         673MiB Windows NTFS volume
/0/100/1d.6                        bridge         Cannon Lake PCH PCI Express Root Port #15
/0/100/1d.6/0      eno2            network        RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
/0/100/1f                          bridge         HM470 Chipset LPC/eSPI Controller
/0/100/1f.3                        multimedia     Cannon Lake PCH cAVS
/0/100/1f.4                        bus            Cannon Lake PCH SMBus Controller
/0/100/1f.5                        bus            Cannon Lake PCH SPI Controller
/0/1                               system         PnP device PNP0c02
/0/2                               system         PnP device PNP0c02
/0/3                               generic        PnP device INT3f0d
/0/4                               generic        PnP device ATK3001
/0/5                               system         PnP device PNP0c02
/0/6                               system         PnP device PNP0c02
/0/7                               system         PnP device PNP0c02
/0/9                               system         PnP device PNP0c02
/0/a               scsi0           storage        
/0/a/0.0.0         /dev/sda        disk           500GB WDC WDS500G2B0A
/0/a/0.0.0/1       /dev/sda1       volume         127MiB reserved partition
/0/a/0.0.0/2       /dev/sda2       volume         238GiB EXT4 volume
/0/a/0.0.0/3       /dev/sda3       volume         227GiB EXT4 volume

**Basic configuration**
If only temperatures were set and they worked, add output of:
* `sudo asus-fan-control get-temps` (new default temperatures for your device)
* `sudo asus-fan-control model-info`

I execute the command  sudo asus-fan-control get-temps at the request of the fan speed, I receive it
55 56 57 58 59 60 61 62
, but I cannot change it. The command works, but after the request, the values are standard. 

**Advanced configuration**
If advanced configuration was used, add output of:
* `sudo FALLBACK_ADDRS='<addrs>' FALLBACK_TEMPS='<temps>' asus-fan-control model-info`

**It does not work**
I installed the penultimate and latest version through gitpack, nothing helps, the set-temp command is executed but does not bring any result.

**Comment by dominiksalvet** [comment]
Hello @msazanov, unfortunately this looks like an already known AFC issue that occurs with some laptop models. So far, there is no way to make AFC work on these devices, but you may take a look at the assigned issue label for possible alternatives (set but not get).
