### ISSUE TITLE
Add systemd unit

### ISSUE THREAD

**Issue by agura-lex** [dominiksalvet/asus-fan-control#9]
**Is your feature request related to a problem? Please describe.**
systemd is almost a standard in mainstream distros like Fedora, Arch, Debian etc. and some of them are lacking /etc/rc.local support

**Describe the solution you'd like**
A systemd service file to start the script at boot

**Comment by agura-lex** [comment]
I would gladly implement and test it since I'm also going to package it for Arch

**Comment by agura-lex** [comment]
Added a systemd unit in https://github.com/agura-lex/asus-fan-control/commit/91df5eb63bfd27e708903bc46098acce6f50e030
But I haven't made changes in gitpack files since I dunno if you're gonna replace rc.local stuff with it or not, neither did I test on anything other than Arch. 

BTW, [submitted](https://aur.archlinux.org/packages/asus-fan-control/) it to AUR for Arch users, I've realized that I can ship systemd service as part of the AUR package, so not having it upstream is not an issue.

**Comment by dominiksalvet** [comment]
Hi @agura-lex and thank you for contributing! First I want to say that I have zero experience with Arch distributions, so I basically trust you... :smile: Regarding systemd, it is almost the same story...

Regarding [this commit](https://github.com/agura-lex/asus-fan-control/commit/91df5eb63bfd27e708903bc46098acce6f50e030), please keep consistency and use the asus-fan-control description.

About the */etc/rc.local* - I am fine with replacing it with systemd as long as it runs fine on Ubuntu as well. If it is the case, feel free to modify GitPack files as well. Please, keep it as simple and as consistent as possible. I do not want to introduce any fragmentation.

**Comment by agura-lex** [comment]
Done, will create a PR as soon https://github.com/dominiksalvet/asus-fan-control/pull/8 is merged since a `systemd` branch is based on it

**Comment by agura-lex** [comment]
Regarding systemd, it's as simple as running `systemctl enable <unit>` / `systemctl disable <unit>`, and should work on any systemd distro accross the board as long as it doesn't use some newly introduced stuff, which this one doesn't as it's as simple as it could be. Will dig into gitpack stuff but probably not today :D

**Comment by dominiksalvet** [comment]
I just have merged #8. As you can see, I try to make my projects as simple as possible. It would be great if we can switch asus-fan-control from */etc/rc.local* to systemd entirely. I do not want to support both as you have probably understood.

So far it looks promising based on your comments - improve portability and it would be also great to get rid of the */etc/rc.local* parsing scripts as well.

**Comment by agura-lex** [comment]
Yeah, scripting adding stuff to rc.local is kinda ugly and not very robust. Will create a PR today, but let's don't merge it until it gets done completely. Thanks for prompt response and welcomeness BTW!

**Comment by dominiksalvet** [comment]
All right, please, let me know when it is ready. I like to cooperate! :smile:
