### ISSUE TITLE
Please add Asus X540LJ to working devices

### ISSUE THREAD

**Issue by garry200708** [dominiksalvet/asus-fan-control#92]

**Comment by dominiksalvet** [comment]
Hello @garry200708 and welcome to the AFC community! 👋

To add your device to AFC, please fill the information below:

> **Environment**
> State asus-fan-control version and OS information.
>
> **Basic configuration**
> If only temperatures were set and they worked, add output of:
> * `sudo asus-fan-control get-temps` (new default temperatures for your device)
> * `sudo asus-fan-control model-info`
>
> **Advanced configuration**
If advanced configuration was used, add output of:
> * `sudo FALLBACK_ADDRS='<addrs>' FALLBACK_TEMPS='<temps>' asus-fan-control model-info`
>
> **It does not work**
If neither configuration was working for your device, community involvement is required. Please provide some information so the community can build on something. Why does asus-fan-control not work? What have you tried?
>
> **Additional context**
> Add any additional context.

**Comment by dominiksalvet** [comment]
Hey @garry200708, is this issue still valid? I can assist you in adding your device to the tested ones! :rocket:
