### ISSUE TITLE
dmidecode confusion on new model

### ISSUE THREAD

**Issue by jaggzh** [dominiksalvet/asus-fan-control#93]
Okay, I'm trying to figure out how to handle this gracefully.
The dmidecode returned info for "system-product-name" is just  "`System Product Name`".
It seems `dmidecode` outputs multiple handles, and the one returned by `dmidecode -s system-product-name` seems to be the first, which is not useful for determining the system type here.  Instead, `baseboard-product-name` might be more useful?
If this isn't standardized, perhaps we can go through the system-product-names looking for a match, then baseboard-product-names?

**Comment by dominiksalvet** [comment]
Hello @jaggzh and welcome to the AFC community.

First, what device do you have? And second, what are the respective output values on your system for the provided `dmidecode` sub-commands?

**Comment by jaggzh** [comment]
Thank you :)  Welcome to my browser window and... living space.. I guess?
So, it's a "Rog Strix B450-F Gaming II".
Your subcommands aren't working, though, and that's another issue I'm trying to figure out how to figure out.
'\_SB.PCI0.LPCB.EC0.RRAM' yields `acpi call failed with 'Error: AE_NOT_FOUND'`

I wrote a script to get the DSDT data, but have no clue how to make sense of the data:

#!/bin/bash
datf=dsdt.dat
datfreadable=dsdt.dsl
fwfile=/sys/firmware/acpi/tables/DSDT
sudo cat "$fwfile" >"$datf"
iasl -d "$datf"
cat <<-EOT
Raw data from $fwfile"
  > $datf
iasl decoded file for you to read:
  > $datfreadable
EOT

(So I end up with a 500k "dsdt.dsl" text file)

**Comment by dominiksalvet** [comment]
Well, there is no MB working with AFC yet and the AE_NOT_FOUND is a typical issue even on some laptops. It basically means that AFC will not work on the device until someone figure out how to make these devices work. But it may be impossible...

The System Product Name is just a bonus to the current situation. However, if I remember correctly, even MBs tend to report their name correctly using this method.

**Comment by dominiksalvet** [comment]
Anyway, should you find something that works for you, let us know! 👍
