### ISSUE TITLE
Add support for Asus FX504 GE

### ISSUE THREAD

**Issue by ATinyLearner** [dominiksalvet/asus-fan-control#94]
**Environment**
State asus-fan-control version and OS information.

**Basic configuration**
If only temperatures were set and they worked, add output of:
* `sudo asus-fan-control get-temps` (new default temperatures for your device)
* acpi call failed with 'Error: AE_NOT_FOUND'
* `sudo asus-fan-control model-info`
* name TUFGAMINGFX504GEFX80GE
addresses 1335
default-temps 55 60 62 65 68 72 76 80
tested false
* 

**Advanced configuration**
If advanced configuration was used, add output of:
* `sudo FALLBACK_ADDRS='<addrs>' FALLBACK_TEMPS='<temps>' asus-fan-control model-info`

**It does not work**
If neither configuration was working for your device, community involvement is required. Please provide some information so the community can build on something. Why does asus-fan-control not work? What have you tried?
I have tried all the guidelines and it installed perfectly excluding the last line it shows the same 
acpi call failed with 'Error: AE_NOT_FOUND'.
Now if I want to run the program using the command:
sudo asus-fan-control
I am getting
acpi call failed with 'Error: AE_NOT_FOUND'

**Additional context**
Add any additional context.

**Comment by dominiksalvet** [comment]
Hello @ATinyLearner! :wave:

Unfortunately, this is a notorious issue with AFC and so far there is no way to fix it. See other issues labeled with `AE_NOT_FOUND`. Should you find something that works for your laptop, please let us know! :rocket:
