### ISSUE TITLE
Add support for FX505DV

### ISSUE THREAD

**Issue by Maltergate** [dominiksalvet/asus-fan-control#95]
Hi there,
I tried asus-fancontrol on my laptop but I encountered an error:
'acpi call failed with 'Error: AE_NOT_FOUND' '

I tried to get information with 'afc-scout' but I get the same error.

**Environment**
State asus-fan-control version and OS information.
Ubuntu 20.04.2, Kernel 5.8.0-59-generic

**Basic configuration**
* `sudo asus-fan-control model-info`:
`name TUFGamingFX505DVFX505DV
addresses 1335
default-temps 55 60 62 65 68 72 76 80
tested false
`

It's an AMD processor. It looks like AMD processors are not supported. If it's the case, it may be nice to state it on the main page of the project.

Thanks for your work!

**Comment by dominiksalvet** [comment]
Hello @Maltergate and welcome to the AFC community! :wave: 

That seems to be true since AMD-based devices have different internals for controlling fan speed (based on previous issues). I will include it in the readme -- thank you for the tip! :bulb: :heart_eyes:
