### ISSUE TITLE
Possible to add support for the ROG STRIX SCAR II (GL504GW)

### ISSUE THREAD

**Issue by MNS26** [dominiksalvet/asus-fan-control#99]
Adding  fan control for the 2 fans in the GL504GW.

After installing linux and testing the performance with a few games the fan never went over 5200rpm even though the GPU (RTX 2070) temperature almost got to the shutdown threshold of 99c, while in windows it had a max rpm of 8200-9000 rpm (102% - 105% according to the ROG software)

when the system was compiling/installing packages it randomly ramped up to  somewhere in the mid 6000rpm and then went down again, but no fan response when the CPU and GPU were used by the game.

I'm new to figuring this kind of things out so if there is any information missing i'm sorry

**Comment by dominiksalvet** [comment]
Hello @MNS26! 👋

Please, have a look at https://github.com/dominiksalvet/asus-fan-control/blob/master/contributing.md and https://github.com/dominiksalvet/asus-fan-control/blob/master/readme.md. Once you have it read, let us continue in the discussion based on the provided information. Thank you.

---

Here is the form you will need to fill in after reading the MD files:

> **Environment**
> State asus-fan-control version and OS information.
>
> **Basic configuration**
> If only temperatures were set and they worked, add output of:
> * `sudo asus-fan-control get-temps` (new default temperatures for your device)
> * `sudo asus-fan-control model-info`
>
> **Advanced configuration**
> If advanced configuration was used, add output of:
> * `sudo FALLBACK_ADDRS='<addrs>' FALLBACK_TEMPS='<temps>' asus-fan-control model-info`
>
> **It does not work**
> If neither configuration was working for your device, community involvement is required. Please provide some information so the community can build on something. Why does asus-fan-control not work? What have you tried?
>
> **Additional context**
> Add any additional context.

**Comment by MNS26** [comment]
Thanks for the fast response

**Environment**
Asus-fan-control version 
- Version 3.11.0-1

OS Info
- OS: Garuda Linux 
- Host: Strix GL504GW_GL504GW 1.0 
- Kernel: 5.13.5-zen1-1-zen
- DE: Plasma 5.22.4 
- WM: KWin 
- WM Theme: Sweet-Dark-transparent 
- Terminal: konsole 
- CPU: Intel i7-8750H (12) @ 4.1GHz 
- GPU: Intel CoffeeLake-H GT2 [UHD Graphics 630] 
- GPU: NVIDIA GeForce RTX 2070 Mobile 
- Memory: 2.86GiB / 15.48GiB 

**Basic Configuration**
the output of
```
sudo asus-fan-control get-temps
sudo asus-fan-control model-info
```
![image](https://user-images.githubusercontent.com/53867268/127550161-1ab84c65-2092-4242-af69-481215920c30.png)

**Advanced configuration**
using the command
```
sudo FALLBACK_ADDRS='<addrs>' FALLBACK_TEMPS='<temps>' asus-fan-control  set-temps default
```
had no change when going through all addresses listed by `afc-scout`
![image](https://user-images.githubusercontent.com/53867268/127551328-d35b2220-c883-4354-ac8d-53c0a9f96f46.png)

**Aditional context**
as a temporary solution for thermal issues i'm using the `throttle_thermal_policy` file for different fan modes
0(default)  
1(performance) 
2(silent)
and all the test with asus-fan-control have been done on the default mode

**Comment by MNS26** [comment]
@dominiksalvet i have filled in the form, is there anything i missed?
If so what are the steps needed to get the information?

**Comment by dominiksalvet** [comment]
Well, I have seen these fan modes somewhere in the previous issues. And I doubt the laptops with the modes were compatible with AFC.

Are you able to set temperatures with AFC and does it have some effect?

**Comment by MNS26** [comment]
no i was not able to change the fan speed at all with AFC

**Comment by dominiksalvet** [comment]
Well, unfortunately, I think AFC will not work on your device... See the issues of the added label for more information.
